<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>12.5 Examples of application | Forecasting and Analytics with ADAM</title>
  <meta name="description" content="This textbook explains how to do time series analysis and forecasting using Augmented Dynamic Adaptive Model, implemented in smooth package for R." />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="12.5 Examples of application | Forecasting and Analytics with ADAM" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This textbook explains how to do time series analysis and forecasting using Augmented Dynamic Adaptive Model, implemented in smooth package for R." />
  <meta name="github-repo" content="config-i1/adam" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="12.5 Examples of application | Forecasting and Analytics with ADAM" />
  
  <meta name="twitter:description" content="This textbook explains how to do time series analysis and forecasting using Augmented Dynamic Adaptive Model, implemented in smooth package for R." />
  

<meta name="author" content="Ivan Svetunkov" />


<meta name="date" content="2022-03-14" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="MultipleFrequenciesDSTandLeap.html"/>
<link rel="next" href="ADAMIntermittent.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-XH37Z8VYP8"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-XH37Z8VYP8');
</script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Forecasting and Analytics with ADAM</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#license"><i class="fa fa-check"></i>License</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#acknowledgments"><i class="fa fa-check"></i>Acknowledgments</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="forecastingPlanningAnalytics.html"><a href="forecastingPlanningAnalytics.html"><i class="fa fa-check"></i><b>1.1</b> Forecasting, planning and analytics</a></li>
<li class="chapter" data-level="1.2" data-path="forecastingPrinciples.html"><a href="forecastingPrinciples.html"><i class="fa fa-check"></i><b>1.2</b> Forecasting principles</a></li>
<li class="chapter" data-level="1.3" data-path="typesOfForecasts.html"><a href="typesOfForecasts.html"><i class="fa fa-check"></i><b>1.3</b> Types of forecasts</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="typesOfForecasts.html"><a href="typesOfForecasts.html#typesOfForecastsPoint"><i class="fa fa-check"></i><b>1.3.1</b> Point forecasts</a></li>
<li class="chapter" data-level="1.3.2" data-path="typesOfForecasts.html"><a href="typesOfForecasts.html#typesOfForecastsInterval"><i class="fa fa-check"></i><b>1.3.2</b> Quantiles and prediction intervals</a></li>
<li class="chapter" data-level="1.3.3" data-path="typesOfForecasts.html"><a href="typesOfForecasts.html#forecast-horizon"><i class="fa fa-check"></i><b>1.3.3</b> Forecast horizon</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="modelsMethods.html"><a href="modelsMethods.html"><i class="fa fa-check"></i><b>1.4</b> Models, methods and typical assumptions</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="modelsMethods.html"><a href="modelsMethods.html#assumptions"><i class="fa fa-check"></i><b>1.4.1</b> Assumptions of statistical models</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="forecastsEvaluation.html"><a href="forecastsEvaluation.html"><i class="fa fa-check"></i><b>2</b> Forecasts evaluation</a>
<ul>
<li class="chapter" data-level="2.1" data-path="errorMeasures.html"><a href="errorMeasures.html"><i class="fa fa-check"></i><b>2.1</b> Measuring accuracy of point forecasts</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="errorMeasures.html"><a href="errorMeasures.html#an-example-in-r"><i class="fa fa-check"></i><b>2.1.1</b> An example in R</a></li>
<li class="chapter" data-level="2.1.2" data-path="errorMeasures.html"><a href="errorMeasures.html#errorMeasuresAggregate"><i class="fa fa-check"></i><b>2.1.2</b> Aggregating error measures</a></li>
<li class="chapter" data-level="2.1.3" data-path="errorMeasures.html"><a href="errorMeasures.html#errorMeasuresExampleBig"><i class="fa fa-check"></i><b>2.1.3</b> Demonstration in R</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="uncertainty.html"><a href="uncertainty.html"><i class="fa fa-check"></i><b>2.2</b> Measuring uncertainty</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="uncertainty.html"><a href="uncertainty.html#example-in-r"><i class="fa fa-check"></i><b>2.2.1</b> Example in R</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="errorMeasuresSelection.html"><a href="errorMeasuresSelection.html"><i class="fa fa-check"></i><b>2.3</b> How to choose appropriate error measure</a></li>
<li class="chapter" data-level="2.4" data-path="rollingOrigin.html"><a href="rollingOrigin.html"><i class="fa fa-check"></i><b>2.4</b> Rolling origin</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="rollingOrigin.html"><a href="rollingOrigin.html#principles-of-rolling-origin"><i class="fa fa-check"></i><b>2.4.1</b> Principles of Rolling origin</a></li>
<li class="chapter" data-level="2.4.2" data-path="rollingOrigin.html"><a href="rollingOrigin.html#rolling-origin-in-r"><i class="fa fa-check"></i><b>2.4.2</b> Rolling origin in R</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="statisticalTests.html"><a href="statisticalTests.html"><i class="fa fa-check"></i><b>2.5</b> Statistical comparison of forecasts</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="tsDecomposition.html"><a href="tsDecomposition.html"><i class="fa fa-check"></i><b>3</b> From time series components to ETS</a>
<ul>
<li class="chapter" data-level="3.1" data-path="tsComponents.html"><a href="tsComponents.html"><i class="fa fa-check"></i><b>3.1</b> Time series components</a></li>
<li class="chapter" data-level="3.2" data-path="ClassicalDecomposition.html"><a href="ClassicalDecomposition.html"><i class="fa fa-check"></i><b>3.2</b> Classical Seasonal Decomposition</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="ClassicalDecomposition.html"><a href="ClassicalDecomposition.html#how-to-do"><i class="fa fa-check"></i><b>3.2.1</b> How to do?</a></li>
<li class="chapter" data-level="3.2.2" data-path="ClassicalDecomposition.html"><a href="ClassicalDecomposition.html#a-couple-of-examples"><i class="fa fa-check"></i><b>3.2.2</b> A couple of examples</a></li>
<li class="chapter" data-level="3.2.3" data-path="ClassicalDecomposition.html"><a href="ClassicalDecomposition.html#other-techniques"><i class="fa fa-check"></i><b>3.2.3</b> Other techniques</a></li>
<li class="chapter" data-level="3.2.4" data-path="ClassicalDecomposition.html"><a href="ClassicalDecomposition.html#why-bother"><i class="fa fa-check"></i><b>3.2.4</b> “Why bother?”</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="simpleForecastingMethods.html"><a href="simpleForecastingMethods.html"><i class="fa fa-check"></i><b>3.3</b> Simple forecasting methods</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="simpleForecastingMethods.html"><a href="simpleForecastingMethods.html#Naive"><i class="fa fa-check"></i><b>3.3.1</b> Naïve</a></li>
<li class="chapter" data-level="3.3.2" data-path="simpleForecastingMethods.html"><a href="simpleForecastingMethods.html#GlobalMean"><i class="fa fa-check"></i><b>3.3.2</b> Global Mean</a></li>
<li class="chapter" data-level="3.3.3" data-path="simpleForecastingMethods.html"><a href="simpleForecastingMethods.html#SMA"><i class="fa fa-check"></i><b>3.3.3</b> Simple Moving Average</a></li>
<li class="chapter" data-level="3.3.4" data-path="simpleForecastingMethods.html"><a href="simpleForecastingMethods.html#RWWithDrift"><i class="fa fa-check"></i><b>3.3.4</b> Random Walk with drift</a></li>
<li class="chapter" data-level="3.3.5" data-path="simpleForecastingMethods.html"><a href="simpleForecastingMethods.html#NaiveSeasonal"><i class="fa fa-check"></i><b>3.3.5</b> Seasonal Naïve</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="ETSTaxonomy.html"><a href="ETSTaxonomy.html"><i class="fa fa-check"></i><b>3.4</b> ETS taxonomy</a></li>
<li class="chapter" data-level="3.5" data-path="ETSTaxonomyMaths.html"><a href="ETSTaxonomyMaths.html"><i class="fa fa-check"></i><b>3.5</b> Mathematical models in the ETS taxonomy</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="ETSConventional.html"><a href="ETSConventional.html"><i class="fa fa-check"></i><b>4</b> Conventional Exponential Smoothing</a>
<ul>
<li class="chapter" data-level="4.1" data-path="SES.html"><a href="SES.html"><i class="fa fa-check"></i><b>4.1</b> Simple Exponential Smoothing</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="SES.html"><a href="SES.html#examples-of-application"><i class="fa fa-check"></i><b>4.1.1</b> Examples of application</a></li>
<li class="chapter" data-level="4.1.2" data-path="SES.html"><a href="SES.html#whyExponential"><i class="fa fa-check"></i><b>4.1.2</b> Why “exponential?”</a></li>
<li class="chapter" data-level="4.1.3" data-path="SES.html"><a href="SES.html#SESEC"><i class="fa fa-check"></i><b>4.1.3</b> Error correction form of SES</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="SESandETS.html"><a href="SESandETS.html"><i class="fa fa-check"></i><b>4.2</b> SES and ETS</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="SESandETS.html"><a href="SESandETS.html#etsann"><i class="fa fa-check"></i><b>4.2.1</b> ETS(A,N,N)</a></li>
<li class="chapter" data-level="4.2.2" data-path="SESandETS.html"><a href="SESandETS.html#etsmnn"><i class="fa fa-check"></i><b>4.2.2</b> ETS(M,N,N)</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="ETSExamples.html"><a href="ETSExamples.html"><i class="fa fa-check"></i><b>4.3</b> Several examples of ETS and related exponential smoothing methods</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="ETSExamples.html"><a href="ETSExamples.html#ETSAAN"><i class="fa fa-check"></i><b>4.3.1</b> ETS(A,A,N)</a></li>
<li class="chapter" data-level="4.3.2" data-path="ETSExamples.html"><a href="ETSExamples.html#ETSAAdN"><i class="fa fa-check"></i><b>4.3.2</b> ETS(A,Ad,N)</a></li>
<li class="chapter" data-level="4.3.3" data-path="ETSExamples.html"><a href="ETSExamples.html#ETSAAMModel"><i class="fa fa-check"></i><b>4.3.3</b> ETS(A,A,M)</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="ets-assumptions-estimation-and-selection.html"><a href="ets-assumptions-estimation-and-selection.html"><i class="fa fa-check"></i><b>4.4</b> ETS assumptions, estimation and selection</a></li>
<li class="chapter" data-level="4.5" data-path="ETSConventionalModel.html"><a href="ETSConventionalModel.html"><i class="fa fa-check"></i><b>4.5</b> State space form of ETS</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="ETSConventionalModel.html"><a href="ETSConventionalModel.html#ETSConventionalModelAdditive"><i class="fa fa-check"></i><b>4.5.1</b> Pure additive state space model</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="ETSParametersBounds.html"><a href="ETSParametersBounds.html"><i class="fa fa-check"></i><b>4.6</b> Parameters bounds</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="ADAMETSIntroduction.html"><a href="ADAMETSIntroduction.html"><i class="fa fa-check"></i><b>5</b> Pure additive ADAM ETS</a>
<ul>
<li class="chapter" data-level="5.1" data-path="ADAMETSPureAdditive.html"><a href="ADAMETSPureAdditive.html"><i class="fa fa-check"></i><b>5.1</b> Model formulation</a></li>
<li class="chapter" data-level="5.2" data-path="adamETSPureAdditiveRecursive.html"><a href="adamETSPureAdditiveRecursive.html"><i class="fa fa-check"></i><b>5.2</b> Recursive relation</a></li>
<li class="chapter" data-level="5.3" data-path="pureAdditiveExpectationAndVariance.html"><a href="pureAdditiveExpectationAndVariance.html"><i class="fa fa-check"></i><b>5.3</b> Conditional expectation and variance</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="pureAdditiveExpectationAndVariance.html"><a href="pureAdditiveExpectationAndVariance.html#example-with-etsann"><i class="fa fa-check"></i><b>5.3.1</b> Example with ETS(A,N,N)</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="stabilityConditionAdditiveError.html"><a href="stabilityConditionAdditiveError.html"><i class="fa fa-check"></i><b>5.4</b> Stability and forecastability conditions</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="stabilityConditionAdditiveError.html"><a href="stabilityConditionAdditiveError.html#example-with-etsann-1"><i class="fa fa-check"></i><b>5.4.1</b> Example with ETS(A,N,N)</a></li>
<li class="chapter" data-level="5.4.2" data-path="stabilityConditionAdditiveError.html"><a href="stabilityConditionAdditiveError.html#comming-back-to-the-general-case"><i class="fa fa-check"></i><b>5.4.2</b> Comming back to the general case</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="ADAMETSAdditiveDistributions.html"><a href="ADAMETSAdditiveDistributions.html"><i class="fa fa-check"></i><b>5.5</b> Distributional assumptions in pure additive ETS</a></li>
<li class="chapter" data-level="5.6" data-path="ADAMETSPureAdditiveExamples.html"><a href="ADAMETSPureAdditiveExamples.html"><i class="fa fa-check"></i><b>5.6</b> Examples of application</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="ADAMETSPureAdditiveExamples.html"><a href="ADAMETSPureAdditiveExamples.html#non-seasonal-data"><i class="fa fa-check"></i><b>5.6.1</b> Non-seasonal data</a></li>
<li class="chapter" data-level="5.6.2" data-path="ADAMETSPureAdditiveExamples.html"><a href="ADAMETSPureAdditiveExamples.html#ADAMETSPureAdditiveExamplesETSAAA"><i class="fa fa-check"></i><b>5.6.2</b> Seasonal data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="ADAMETSPureMultiplicativeChapter.html"><a href="ADAMETSPureMultiplicativeChapter.html"><i class="fa fa-check"></i><b>6</b> Pure multiplicative ADAM ETS</a>
<ul>
<li class="chapter" data-level="6.1" data-path="ADAMETSPureMultiplicative.html"><a href="ADAMETSPureMultiplicative.html"><i class="fa fa-check"></i><b>6.1</b> Model formulation</a></li>
<li class="chapter" data-level="6.2" data-path="adamETSPuremultiplicativeRecursive.html"><a href="adamETSPuremultiplicativeRecursive.html"><i class="fa fa-check"></i><b>6.2</b> Recursive relation</a></li>
<li class="chapter" data-level="6.3" data-path="pureMultiplicativeExpectationAndVariance.html"><a href="pureMultiplicativeExpectationAndVariance.html"><i class="fa fa-check"></i><b>6.3</b> The problem with moments in pure multiplicative ETS</a></li>
<li class="chapter" data-level="6.4" data-path="stabilityConditionMultiplicativeError.html"><a href="stabilityConditionMultiplicativeError.html"><i class="fa fa-check"></i><b>6.4</b> Smoothing parameters bounds</a></li>
<li class="chapter" data-level="6.5" data-path="ADAMETSMultiplicativeDistributions.html"><a href="ADAMETSMultiplicativeDistributions.html"><i class="fa fa-check"></i><b>6.5</b> Distributional assumptions in pure multiplicative ETS</a></li>
<li class="chapter" data-level="6.6" data-path="ADAMETSMultiplicativeExamples.html"><a href="ADAMETSMultiplicativeExamples.html"><i class="fa fa-check"></i><b>6.6</b> Examples of application</a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="ADAMETSMultiplicativeExamples.html"><a href="ADAMETSMultiplicativeExamples.html#non-seasonal-data-1"><i class="fa fa-check"></i><b>6.6.1</b> Non-seasonal data</a></li>
<li class="chapter" data-level="6.6.2" data-path="ADAMETSMultiplicativeExamples.html"><a href="ADAMETSMultiplicativeExamples.html#seasonal-data"><i class="fa fa-check"></i><b>6.6.2</b> Seasonal data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="ADAMETSOther.html"><a href="ADAMETSOther.html"><i class="fa fa-check"></i><b>7</b> General ADAM ETS model</a>
<ul>
<li class="chapter" data-level="7.1" data-path="ADAMETSGeneral.html"><a href="ADAMETSGeneral.html"><i class="fa fa-check"></i><b>7.1</b> Model formulation</a></li>
<li class="chapter" data-level="7.2" data-path="ADAMETSMixedModels.html"><a href="ADAMETSMixedModels.html"><i class="fa fa-check"></i><b>7.2</b> Mixed ADAM ETS models</a></li>
<li class="chapter" data-level="7.3" data-path="ADAMETSMixedModelsGroup3.html"><a href="ADAMETSMixedModelsGroup3.html"><i class="fa fa-check"></i><b>7.3</b> Mixed models with non-multiplicative trend</a></li>
<li class="chapter" data-level="7.4" data-path="ADAMETSMixedModelsGroup4.html"><a href="ADAMETSMixedModelsGroup4.html"><i class="fa fa-check"></i><b>7.4</b> Mixed models with multiplicative trend</a></li>
<li class="chapter" data-level="7.5" data-path="ADAMETSSeasonalNormalisation.html"><a href="ADAMETSSeasonalNormalisation.html"><i class="fa fa-check"></i><b>7.5</b> Normalisation of seasonal indices in ETS models</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="ARIMA.html"><a href="ARIMA.html"><i class="fa fa-check"></i><b>8</b> Conventional ARIMA</a>
<ul>
<li class="chapter" data-level="8.1" data-path="ARIMAIntro.html"><a href="ARIMAIntro.html"><i class="fa fa-check"></i><b>8.1</b> Introduction to ARIMA</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="ARIMAIntro.html"><a href="ARIMAIntro.html#AR"><i class="fa fa-check"></i><b>8.1.1</b> AR(p)</a></li>
<li class="chapter" data-level="8.1.2" data-path="ARIMAIntro.html"><a href="ARIMAIntro.html#MA"><i class="fa fa-check"></i><b>8.1.2</b> MA(q)</a></li>
<li class="chapter" data-level="8.1.3" data-path="ARIMAIntro.html"><a href="ARIMAIntro.html#ARMA"><i class="fa fa-check"></i><b>8.1.3</b> ARMA(p,q)</a></li>
<li class="chapter" data-level="8.1.4" data-path="ARIMAIntro.html"><a href="ARIMAIntro.html#ARMAConstant"><i class="fa fa-check"></i><b>8.1.4</b> ARMA with constant</a></li>
<li class="chapter" data-level="8.1.5" data-path="ARIMAIntro.html"><a href="ARIMAIntro.html#Differences"><i class="fa fa-check"></i><b>8.1.5</b> I(d)</a></li>
<li class="chapter" data-level="8.1.6" data-path="ARIMAIntro.html"><a href="ARIMAIntro.html#arimapdq"><i class="fa fa-check"></i><b>8.1.6</b> ARIMA(p,d,q)</a></li>
<li class="chapter" data-level="8.1.7" data-path="ARIMAIntro.html"><a href="ARIMAIntro.html#ARIMABounds"><i class="fa fa-check"></i><b>8.1.7</b> Parameters bounds</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="seasonal-arima.html"><a href="seasonal-arima.html"><i class="fa fa-check"></i><b>8.2</b> Seasonal ARIMA</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="seasonal-arima.html"><a href="seasonal-arima.html#single-seasonal-arima"><i class="fa fa-check"></i><b>8.2.1</b> Single seasonal ARIMA</a></li>
<li class="chapter" data-level="8.2.2" data-path="seasonal-arima.html"><a href="seasonal-arima.html#sarima-with-constant"><i class="fa fa-check"></i><b>8.2.2</b> SARIMA with constant</a></li>
<li class="chapter" data-level="8.2.3" data-path="seasonal-arima.html"><a href="seasonal-arima.html#MSARIMA"><i class="fa fa-check"></i><b>8.2.3</b> Multiple seasonal ARIMA</a></li>
<li class="chapter" data-level="8.2.4" data-path="seasonal-arima.html"><a href="seasonal-arima.html#MSARIMABounds"><i class="fa fa-check"></i><b>8.2.4</b> Parameters bounds for MSARIMA</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="BJApproach.html"><a href="BJApproach.html"><i class="fa fa-check"></i><b>8.3</b> Box-Jenkins approach</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="BJApproach.html"><a href="BJApproach.html#identifying-stationarity"><i class="fa fa-check"></i><b>8.3.1</b> Identifying stationarity</a></li>
<li class="chapter" data-level="8.3.2" data-path="BJApproach.html"><a href="BJApproach.html#ACF"><i class="fa fa-check"></i><b>8.3.2</b> Autocorrelation function (ACF)</a></li>
<li class="chapter" data-level="8.3.3" data-path="BJApproach.html"><a href="BJApproach.html#PACF"><i class="fa fa-check"></i><b>8.3.3</b> Partial autocorrelation function (PACF)</a></li>
<li class="chapter" data-level="8.3.4" data-path="BJApproach.html"><a href="BJApproach.html#BJApproachSummary"><i class="fa fa-check"></i><b>8.3.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="ARIMAandETS.html"><a href="ARIMAandETS.html"><i class="fa fa-check"></i><b>8.4</b> ARIMA and ETS</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="ARIMAandETS.html"><a href="ARIMAandETS.html#ARIMAETS011"><i class="fa fa-check"></i><b>8.4.1</b> ARIMA(0,1,1) and ETS(A,N,N)</a></li>
<li class="chapter" data-level="8.4.2" data-path="ARIMAandETS.html"><a href="ARIMAandETS.html#ARIMAETS022"><i class="fa fa-check"></i><b>8.4.2</b> ARIMA(0,2,2) and ETS(A,A,N)</a></li>
<li class="chapter" data-level="8.4.3" data-path="ARIMAandETS.html"><a href="ARIMAandETS.html#ARIMAETS112"><i class="fa fa-check"></i><b>8.4.3</b> ARIMA(1,1,2) and ETS(A,Ad,N)</a></li>
<li class="chapter" data-level="8.4.4" data-path="ARIMAandETS.html"><a href="ARIMAandETS.html#ARIMAETSOther"><i class="fa fa-check"></i><b>8.4.4</b> ARIMA and other ETS models</a></li>
<li class="chapter" data-level="8.4.5" data-path="ARIMAandETS.html"><a href="ARIMAandETS.html#ets-arima"><i class="fa fa-check"></i><b>8.4.5</b> ETS + ARIMA</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="ARIMAExampleInR.html"><a href="ARIMAExampleInR.html"><i class="fa fa-check"></i><b>8.5</b> Examples of application</a>
<ul>
<li class="chapter" data-level="8.5.1" data-path="ARIMAExampleInR.html"><a href="ARIMAExampleInR.html#non-seasonal-data-2"><i class="fa fa-check"></i><b>8.5.1</b> Non-seasonal data</a></li>
<li class="chapter" data-level="8.5.2" data-path="ARIMAExampleInR.html"><a href="ARIMAExampleInR.html#ARIMAExampleInRSeasonal"><i class="fa fa-check"></i><b>8.5.2</b> Seasonal data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="ADAMARIMA.html"><a href="ADAMARIMA.html"><i class="fa fa-check"></i><b>9</b> ADAM ARIMA</a>
<ul>
<li class="chapter" data-level="9.1" data-path="StateSpaceARIMA.html"><a href="StateSpaceARIMA.html"><i class="fa fa-check"></i><b>9.1</b> State space ARIMA</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="StateSpaceARIMA.html"><a href="StateSpaceARIMA.html#an-example-of-state-space-arima"><i class="fa fa-check"></i><b>9.1.1</b> An example of State Space ARIMA</a></li>
<li class="chapter" data-level="9.1.2" data-path="StateSpaceARIMA.html"><a href="StateSpaceARIMA.html#StateSpaceARIMAAdditive"><i class="fa fa-check"></i><b>9.1.2</b> Additive ARIMA</a></li>
<li class="chapter" data-level="9.1.3" data-path="StateSpaceARIMA.html"><a href="StateSpaceARIMA.html#state-space-arima-with-constant"><i class="fa fa-check"></i><b>9.1.3</b> State space ARIMA with constant</a></li>
<li class="chapter" data-level="9.1.4" data-path="StateSpaceARIMA.html"><a href="StateSpaceARIMA.html#ADAMARIMAPureMultiplicative"><i class="fa fa-check"></i><b>9.1.4</b> Multiplicative ARIMA</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="ADAMARIMARecursive.html"><a href="ADAMARIMARecursive.html"><i class="fa fa-check"></i><b>9.2</b> Recursive relation</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="ADAMARIMARecursive.html"><a href="ADAMARIMARecursive.html#ADAMARIMARecursiveMoments"><i class="fa fa-check"></i><b>9.2.1</b> Conditional moments of ADAM ARIMA</a></li>
<li class="chapter" data-level="9.2.2" data-path="ADAMARIMARecursive.html"><a href="ADAMARIMARecursive.html#parameters-bounds"><i class="fa fa-check"></i><b>9.2.2</b> Parameters bounds</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="ADAMARIMADistributions.html"><a href="ADAMARIMADistributions.html"><i class="fa fa-check"></i><b>9.3</b> Distributional assumptions of ADAM ARIMA</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="ADAMARIMADistributions.html"><a href="ADAMARIMADistributions.html#conditional-distributions"><i class="fa fa-check"></i><b>9.3.1</b> Conditional distributions</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="ETSAndARIMA.html"><a href="ETSAndARIMA.html"><i class="fa fa-check"></i><b>9.4</b> ETS + ARIMA</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="ETSAndARIMA.html"><a href="ETSAndARIMA.html#pure-additive-models"><i class="fa fa-check"></i><b>9.4.1</b> Pure additive models</a></li>
<li class="chapter" data-level="9.4.2" data-path="ETSAndARIMA.html"><a href="ETSAndARIMA.html#ADAMARIMAMultiplicative"><i class="fa fa-check"></i><b>9.4.2</b> Pure multiplicative models</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="ADAMARIMAExamples.html"><a href="ADAMARIMAExamples.html"><i class="fa fa-check"></i><b>9.5</b> Examples of application</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="ADAMX.html"><a href="ADAMX.html"><i class="fa fa-check"></i><b>10</b> Explanatory variables in ADAM</a>
<ul>
<li class="chapter" data-level="10.1" data-path="ADAMXFormulation.html"><a href="ADAMXFormulation.html"><i class="fa fa-check"></i><b>10.1</b> ADAMX: Model formulation</a></li>
<li class="chapter" data-level="10.2" data-path="ADAMXConventionalConditionalMoments.html"><a href="ADAMXConventionalConditionalMoments.html"><i class="fa fa-check"></i><b>10.2</b> Conditional expectation and variance of ADAMX</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="ADAMXConventionalConditionalMoments.html"><a href="ADAMXConventionalConditionalMoments.html#adamx-with-deterministic-explanatory-variables"><i class="fa fa-check"></i><b>10.2.1</b> ADAMX with deterministic explanatory variables</a></li>
<li class="chapter" data-level="10.2.2" data-path="ADAMXConventionalConditionalMoments.html"><a href="ADAMXConventionalConditionalMoments.html#ADAMXConventionalConditionalMomentsRandom"><i class="fa fa-check"></i><b>10.2.2</b> ADAMX with stochastic explanatory variables</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="ADAMXDynamic.html"><a href="ADAMXDynamic.html"><i class="fa fa-check"></i><b>10.3</b> Dynamic X in ADAMX</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="ADAMXDynamic.html"><a href="ADAMXDynamic.html#ADAMXDynamicMoments"><i class="fa fa-check"></i><b>10.3.1</b> Recursion for dynamic ADAMX</a></li>
<li class="chapter" data-level="10.3.2" data-path="ADAMXDynamic.html"><a href="ADAMXDynamic.html#conditional-moments-for-deterministic-explanatory-variables-in-adamxd"><i class="fa fa-check"></i><b>10.3.2</b> Conditional moments for deterministic explanatory variables in ADAMX{D}</a></li>
<li class="chapter" data-level="10.3.3" data-path="ADAMXDynamic.html"><a href="ADAMXDynamic.html#conditional-mean-for-stochastic-explanatory-variables-in-adamxd"><i class="fa fa-check"></i><b>10.3.3</b> Conditional mean for stochastic explanatory variables in ADAMX{D}</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="stability-and-forecastability-conditions-of-adamx.html"><a href="stability-and-forecastability-conditions-of-adamx.html"><i class="fa fa-check"></i><b>10.4</b> Stability and forecastability conditions of ADAMX</a></li>
<li class="chapter" data-level="10.5" data-path="ETSXDynamicCategories.html"><a href="ETSXDynamicCategories.html"><i class="fa fa-check"></i><b>10.5</b> Dealing with categorical variables in ADAMX</a></li>
<li class="chapter" data-level="10.6" data-path="ETSXRExample.html"><a href="ETSXRExample.html"><i class="fa fa-check"></i><b>10.6</b> Examples of application</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="ADAMETSEstimation.html"><a href="ADAMETSEstimation.html"><i class="fa fa-check"></i><b>11</b> Estimation of ADAM models</a>
<ul>
<li class="chapter" data-level="11.1" data-path="ADAMETSEstimationLikelihood.html"><a href="ADAMETSEstimationLikelihood.html"><i class="fa fa-check"></i><b>11.1</b> Maximum Likelihood Estimation</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="ADAMETSEstimationLikelihood.html"><a href="ADAMETSEstimationLikelihood.html#an-example-in-r-1"><i class="fa fa-check"></i><b>11.1.1</b> An example in R</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="non-mle-based-loss-functions.html"><a href="non-mle-based-loss-functions.html"><i class="fa fa-check"></i><b>11.2</b> Non MLE-based loss functions</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="non-mle-based-loss-functions.html"><a href="non-mle-based-loss-functions.html#MSEandMAEEstimators"><i class="fa fa-check"></i><b>11.2.1</b> MSE and MAE</a></li>
<li class="chapter" data-level="11.2.2" data-path="non-mle-based-loss-functions.html"><a href="non-mle-based-loss-functions.html#ham"><i class="fa fa-check"></i><b>11.2.2</b> HAM</a></li>
<li class="chapter" data-level="11.2.3" data-path="non-mle-based-loss-functions.html"><a href="non-mle-based-loss-functions.html#lasso-and-ridge"><i class="fa fa-check"></i><b>11.2.3</b> LASSO and RIDGE</a></li>
<li class="chapter" data-level="11.2.4" data-path="non-mle-based-loss-functions.html"><a href="non-mle-based-loss-functions.html#custom-losses"><i class="fa fa-check"></i><b>11.2.4</b> Custom losses</a></li>
<li class="chapter" data-level="11.2.5" data-path="non-mle-based-loss-functions.html"><a href="non-mle-based-loss-functions.html#examples-in-r"><i class="fa fa-check"></i><b>11.2.5</b> Examples in R</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="multistepLosses.html"><a href="multistepLosses.html"><i class="fa fa-check"></i><b>11.3</b> Multistep losses</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="multistepLosses.html"><a href="multistepLosses.html#mathrmmse_h-mse-for-h-steps-ahead"><i class="fa fa-check"></i><b>11.3.1</b> <span class="math inline">\(\mathrm{MSE}_h\)</span> – MSE for h steps ahead</a></li>
<li class="chapter" data-level="11.3.2" data-path="multistepLosses.html"><a href="multistepLosses.html#multistepLossesTMSE"><i class="fa fa-check"></i><b>11.3.2</b> TMSE – Trace MSE</a></li>
<li class="chapter" data-level="11.3.3" data-path="multistepLosses.html"><a href="multistepLosses.html#multistepLossesGTMSE"><i class="fa fa-check"></i><b>11.3.3</b> GTMSE – Geometric Trace MSE</a></li>
<li class="chapter" data-level="11.3.4" data-path="multistepLosses.html"><a href="multistepLosses.html#msce-mean-squared-cumulative-error"><i class="fa fa-check"></i><b>11.3.4</b> MSCE – Mean Squared Cumulative Error</a></li>
<li class="chapter" data-level="11.3.5" data-path="multistepLosses.html"><a href="multistepLosses.html#gpl-general-predictive-likelihood"><i class="fa fa-check"></i><b>11.3.5</b> GPL – General Predictive Likelihood</a></li>
<li class="chapter" data-level="11.3.6" data-path="multistepLosses.html"><a href="multistepLosses.html#other-multistep-estimators"><i class="fa fa-check"></i><b>11.3.6</b> Other multistep estimators</a></li>
<li class="chapter" data-level="11.3.7" data-path="multistepLosses.html"><a href="multistepLosses.html#an-example-in-r-2"><i class="fa fa-check"></i><b>11.3.7</b> An example in R</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="ADAMInitialisation.html"><a href="ADAMInitialisation.html"><i class="fa fa-check"></i><b>11.4</b> Initialisation of ADAM</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="ADAMInitialisation.html"><a href="ADAMInitialisation.html#ADAMInitialisationOptAndBack"><i class="fa fa-check"></i><b>11.4.1</b> Optimisation vs backcasting</a></li>
<li class="chapter" data-level="11.4.2" data-path="ADAMInitialisation.html"><a href="ADAMInitialisation.html#pre-initialisation-of-adam-parameters"><i class="fa fa-check"></i><b>11.4.2</b> Pre-initialisation of ADAM parameters</a></li>
<li class="chapter" data-level="11.4.3" data-path="ADAMInitialisation.html"><a href="ADAMInitialisation.html#pre-initialisation-of-adam-states-ets"><i class="fa fa-check"></i><b>11.4.3</b> Pre-initialisation of ADAM states, ETS</a></li>
<li class="chapter" data-level="11.4.4" data-path="ADAMInitialisation.html"><a href="ADAMInitialisation.html#pre-initialisation-of-adam-states-arima"><i class="fa fa-check"></i><b>11.4.4</b> Pre-initialisation of ADAM states, ARIMA</a></li>
<li class="chapter" data-level="11.4.5" data-path="ADAMInitialisation.html"><a href="ADAMInitialisation.html#pre-initialisation-of-adam-states-regressors-and-constant"><i class="fa fa-check"></i><b>11.4.5</b> Pre-initialisation of ADAM states, Regressors and constant</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="multiple-frequencies-in-adam.html"><a href="multiple-frequencies-in-adam.html"><i class="fa fa-check"></i><b>12</b> Multiple frequencies in ADAM</a>
<ul>
<li class="chapter" data-level="12.1" data-path="model-formulation.html"><a href="model-formulation.html"><i class="fa fa-check"></i><b>12.1</b> Model formulation</a></li>
<li class="chapter" data-level="12.2" data-path="ADAMMultiplIssues.html"><a href="ADAMMultiplIssues.html"><i class="fa fa-check"></i><b>12.2</b> Estimation of multiple seasonal model</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="ADAMMultiplIssues.html"><a href="ADAMMultiplIssues.html#adam-ets-issues"><i class="fa fa-check"></i><b>12.2.1</b> ADAM ETS issues</a></li>
<li class="chapter" data-level="12.2.2" data-path="ADAMMultiplIssues.html"><a href="ADAMMultiplIssues.html#adam-arima-issues"><i class="fa fa-check"></i><b>12.2.2</b> ADAM ARIMA issues</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="ETSXMultipleSeasonality.html"><a href="ETSXMultipleSeasonality.html"><i class="fa fa-check"></i><b>12.3</b> Using explanatory variables for multiple seasonalities</a></li>
<li class="chapter" data-level="12.4" data-path="MultipleFrequenciesDSTandLeap.html"><a href="MultipleFrequenciesDSTandLeap.html"><i class="fa fa-check"></i><b>12.4</b> Dealing with daylight saving and leap years</a></li>
<li class="chapter" data-level="12.5" data-path="ADAMMultipleFrequenciesExamples.html"><a href="ADAMMultipleFrequenciesExamples.html"><i class="fa fa-check"></i><b>12.5</b> Examples of application</a>
<ul>
<li class="chapter" data-level="12.5.1" data-path="ADAMMultipleFrequenciesExamples.html"><a href="ADAMMultipleFrequenciesExamples.html#adam-ets"><i class="fa fa-check"></i><b>12.5.1</b> ADAM ETS</a></li>
<li class="chapter" data-level="12.5.2" data-path="ADAMMultipleFrequenciesExamples.html"><a href="ADAMMultipleFrequenciesExamples.html#adam-etsx"><i class="fa fa-check"></i><b>12.5.2</b> ADAM ETSX</a></li>
<li class="chapter" data-level="12.5.3" data-path="ADAMMultipleFrequenciesExamples.html"><a href="ADAMMultipleFrequenciesExamples.html#adam-arima"><i class="fa fa-check"></i><b>12.5.3</b> ADAM ARIMA</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="ADAMIntermittent.html"><a href="ADAMIntermittent.html"><i class="fa fa-check"></i><b>13</b> Intermittent State Space Model</a>
<ul>
<li class="chapter" data-level="13.1" data-path="ADAMOccurrence.html"><a href="ADAMOccurrence.html"><i class="fa fa-check"></i><b>13.1</b> Occurrence part of the model</a>
<ul>
<li class="chapter" data-level="13.1.1" data-path="ADAMOccurrence.html"><a href="ADAMOccurrence.html#fixed-probability-model-oets_f"><i class="fa fa-check"></i><b>13.1.1</b> Fixed probability model, oETS<span class="math inline">\(_F\)</span></a></li>
<li class="chapter" data-level="13.1.2" data-path="ADAMOccurrence.html"><a href="ADAMOccurrence.html#oETSO"><i class="fa fa-check"></i><b>13.1.2</b> Odds ratio model, oETS<span class="math inline">\(_O\)</span></a></li>
<li class="chapter" data-level="13.1.3" data-path="ADAMOccurrence.html"><a href="ADAMOccurrence.html#oETSI"><i class="fa fa-check"></i><b>13.1.3</b> Inverse odds ratio model, oETS<span class="math inline">\(_I\)</span></a></li>
<li class="chapter" data-level="13.1.4" data-path="ADAMOccurrence.html"><a href="ADAMOccurrence.html#oETSG"><i class="fa fa-check"></i><b>13.1.4</b> General oETS model, oETS<span class="math inline">\(_G\)</span></a></li>
<li class="chapter" data-level="13.1.5" data-path="ADAMOccurrence.html"><a href="ADAMOccurrence.html#oETSD"><i class="fa fa-check"></i><b>13.1.5</b> Direct probability model, oETS<span class="math inline">\(_D\)</span></a></li>
<li class="chapter" data-level="13.1.6" data-path="ADAMOccurrence.html"><a href="ADAMOccurrence.html#oETSModelSelection"><i class="fa fa-check"></i><b>13.1.6</b> Model selection in oETS</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="ADAMDemandSizes.html"><a href="ADAMDemandSizes.html"><i class="fa fa-check"></i><b>13.2</b> Demand sizes part of the model</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="ADAMDemandSizes.html"><a href="ADAMDemandSizes.html#additive-vs-multiplicative-ets-for-demand-sizes"><i class="fa fa-check"></i><b>13.2.1</b> Additive vs multiplicative ETS for demand sizes</a></li>
<li class="chapter" data-level="13.2.2" data-path="ADAMDemandSizes.html"><a href="ADAMDemandSizes.html#using-arima-for-demand-sizes"><i class="fa fa-check"></i><b>13.2.2</b> Using ARIMA for demand sizes</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="ADAMIntermittentFull.html"><a href="ADAMIntermittentFull.html"><i class="fa fa-check"></i><b>13.3</b> The full ADAM model</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="ADAMIntermittentFull.html"><a href="ADAMIntermittentFull.html#iETSMLE"><i class="fa fa-check"></i><b>13.3.1</b> Maximum Likelihood Estimation</a></li>
<li class="chapter" data-level="13.3.2" data-path="ADAMIntermittentFull.html"><a href="ADAMIntermittentFull.html#conditional-expectation-and-variance"><i class="fa fa-check"></i><b>13.3.2</b> Conditional expectation and variance</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="IntermittentExample.html"><a href="IntermittentExample.html"><i class="fa fa-check"></i><b>13.4</b> Examples of application</a></li>
<li class="chapter" data-level="13.5" data-path="intermittent-demand-challenges.html"><a href="intermittent-demand-challenges.html"><i class="fa fa-check"></i><b>13.5</b> Intermittent demand challenges</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="diagnostics.html"><a href="diagnostics.html"><i class="fa fa-check"></i><b>14</b> Model diagnostics</a>
<ul>
<li class="chapter" data-level="14.1" data-path="diagnosticsOmitted.html"><a href="diagnosticsOmitted.html"><i class="fa fa-check"></i><b>14.1</b> Model specification: Omitted variables</a></li>
<li class="chapter" data-level="14.2" data-path="diagnosticsRedundant.html"><a href="diagnosticsRedundant.html"><i class="fa fa-check"></i><b>14.2</b> Model specification: Redundant variables</a></li>
<li class="chapter" data-level="14.3" data-path="diagnosticsTransformations.html"><a href="diagnosticsTransformations.html"><i class="fa fa-check"></i><b>14.3</b> Model specification: Transformations</a></li>
<li class="chapter" data-level="14.4" data-path="diagnosticsOutliers.html"><a href="diagnosticsOutliers.html"><i class="fa fa-check"></i><b>14.4</b> Model specification: Outliers</a>
<ul>
<li class="chapter" data-level="14.4.1" data-path="diagnosticsOutliers.html"><a href="diagnosticsOutliers.html#outliers-detection"><i class="fa fa-check"></i><b>14.4.1</b> Outliers detection</a></li>
<li class="chapter" data-level="14.4.2" data-path="diagnosticsOutliers.html"><a href="diagnosticsOutliers.html#dealing-with-outliers"><i class="fa fa-check"></i><b>14.4.2</b> Dealing with outliers</a></li>
<li class="chapter" data-level="14.4.3" data-path="diagnosticsOutliers.html"><a href="diagnosticsOutliers.html#an-automatic-mechanism"><i class="fa fa-check"></i><b>14.4.3</b> An automatic mechanism</a></li>
<li class="chapter" data-level="14.4.4" data-path="diagnosticsOutliers.html"><a href="diagnosticsOutliers.html#final-remarks"><i class="fa fa-check"></i><b>14.4.4</b> Final remarks</a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="diagnosticsResidualsIIDAuto.html"><a href="diagnosticsResidualsIIDAuto.html"><i class="fa fa-check"></i><b>14.5</b> Residuals are i.i.d.: autocorrelation</a></li>
<li class="chapter" data-level="14.6" data-path="diagnosticsResidualsIIDHetero.html"><a href="diagnosticsResidualsIIDHetero.html"><i class="fa fa-check"></i><b>14.6</b> Residuals are i.i.d.: heteroscedasticity</a>
<ul>
<li class="chapter" data-level="14.6.1" data-path="diagnosticsResidualsIIDHetero.html"><a href="diagnosticsResidualsIIDHetero.html#detecting-heteroscedasticity"><i class="fa fa-check"></i><b>14.6.1</b> Detecting heteroscedasticity</a></li>
</ul></li>
<li class="chapter" data-level="14.7" data-path="diagnosticsResidualsIIDExpectation.html"><a href="diagnosticsResidualsIIDExpectation.html"><i class="fa fa-check"></i><b>14.7</b> Residuals are i.i.d.: zero expectation</a>
<ul>
<li class="chapter" data-level="14.7.1" data-path="diagnosticsResidualsIIDExpectation.html"><a href="diagnosticsResidualsIIDExpectation.html#diagnosticsResidualsIIDExpectationMultiple"><i class="fa fa-check"></i><b>14.7.1</b> Multistep forecast errors have zero mean</a></li>
</ul></li>
<li class="chapter" data-level="14.8" data-path="diagnosticsResidualsIIDDistribution.html"><a href="diagnosticsResidualsIIDDistribution.html"><i class="fa fa-check"></i><b>14.8</b> Residuals are i.i.d.: distributional assumptions</a></li>
<li class="chapter" data-level="14.9" data-path="diagnosticsMulticollinearity.html"><a href="diagnosticsMulticollinearity.html"><i class="fa fa-check"></i><b>14.9</b> Multicollinearity</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="ADAMscaleModel.html"><a href="ADAMscaleModel.html"><i class="fa fa-check"></i><b>15</b> Scale model for ADAM</a>
<ul>
<li class="chapter" data-level="15.1" data-path="model-formulation-1.html"><a href="model-formulation-1.html"><i class="fa fa-check"></i><b>15.1</b> Model formulation</a>
<ul>
<li class="chapter" data-level="15.1.1" data-path="model-formulation-1.html"><a href="model-formulation-1.html#an-example-with-local-level-model-with-normal-distribution"><i class="fa fa-check"></i><b>15.1.1</b> An example with local level model with Normal distribution</a></li>
<li class="chapter" data-level="15.1.2" data-path="model-formulation-1.html"><a href="model-formulation-1.html#general-case-with-normal-distribution"><i class="fa fa-check"></i><b>15.1.2</b> General case with Normal distribution</a></li>
<li class="chapter" data-level="15.1.3" data-path="model-formulation-1.html"><a href="model-formulation-1.html#other-distributions"><i class="fa fa-check"></i><b>15.1.3</b> Other distributions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="ADAMSelection.html"><a href="ADAMSelection.html"><i class="fa fa-check"></i><b>16</b> Model selection and combinations in ADAM</a>
<ul>
<li class="chapter" data-level="16.1" data-path="ETSSelection.html"><a href="ETSSelection.html"><i class="fa fa-check"></i><b>16.1</b> ADAM ETS components selection</a></li>
<li class="chapter" data-level="16.2" data-path="ARIMASelection.html"><a href="ARIMASelection.html"><i class="fa fa-check"></i><b>16.2</b> ADAM ARIMA order selection</a>
<ul>
<li class="chapter" data-level="16.2.1" data-path="ARIMASelection.html"><a href="ARIMASelection.html#ets-arima-restrictions"><i class="fa fa-check"></i><b>16.2.1</b> ETS + ARIMA restrictions</a></li>
</ul></li>
<li class="chapter" data-level="16.3" data-path="ETSXSelection.html"><a href="ETSXSelection.html"><i class="fa fa-check"></i><b>16.3</b> Explanatory variables selection</a></li>
<li class="chapter" data-level="16.4" data-path="ADAMCombinations.html"><a href="ADAMCombinations.html"><i class="fa fa-check"></i><b>16.4</b> Forecasts combinations in ADAM</a>
<ul>
<li class="chapter" data-level="16.4.1" data-path="ADAMCombinations.html"><a href="ADAMCombinations.html#other-combination-approaches"><i class="fa fa-check"></i><b>16.4.1</b> Other combination approaches</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="ADAMUncertainty.html"><a href="ADAMUncertainty.html"><i class="fa fa-check"></i><b>17</b> Handling uncertainty in ADAM</a>
<ul>
<li class="chapter" data-level="17.1" data-path="ADAMUncertaintyVCOV.html"><a href="ADAMUncertaintyVCOV.html"><i class="fa fa-check"></i><b>17.1</b> Covariance matrix of parameters</a>
<ul>
<li class="chapter" data-level="17.1.1" data-path="ADAMUncertaintyVCOV.html"><a href="ADAMUncertaintyVCOV.html#bootstrapped-covariance-matrix"><i class="fa fa-check"></i><b>17.1.1</b> Bootstrapped covariance matrix</a></li>
</ul></li>
<li class="chapter" data-level="17.2" data-path="confidence-intervals-for-parameters.html"><a href="confidence-intervals-for-parameters.html"><i class="fa fa-check"></i><b>17.2</b> Confidence intervals for parameters</a></li>
<li class="chapter" data-level="17.3" data-path="conditionalVarianceUncertainty.html"><a href="conditionalVarianceUncertainty.html"><i class="fa fa-check"></i><b>17.3</b> Conditional variance with uncertain parameters</a>
<ul>
<li class="chapter" data-level="17.3.1" data-path="conditionalVarianceUncertainty.html"><a href="conditionalVarianceUncertainty.html#estimated-initial-state"><i class="fa fa-check"></i><b>17.3.1</b> Estimated initial state</a></li>
<li class="chapter" data-level="17.3.2" data-path="conditionalVarianceUncertainty.html"><a href="conditionalVarianceUncertainty.html#estimated-parameters-of-adam-model"><i class="fa fa-check"></i><b>17.3.2</b> Estimated parameters of ADAM model</a></li>
</ul></li>
<li class="chapter" data-level="17.4" data-path="adamRefitted.html"><a href="adamRefitted.html"><i class="fa fa-check"></i><b>17.4</b> Multi-scenarios for ADAM states</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="ADAMForecasting.html"><a href="ADAMForecasting.html"><i class="fa fa-check"></i><b>18</b> Forecasting with ADAM</a>
<ul>
<li class="chapter" data-level="18.1" data-path="ADAMForecastingExpectation.html"><a href="ADAMForecastingExpectation.html"><i class="fa fa-check"></i><b>18.1</b> Conditional expectation</a>
<ul>
<li class="chapter" data-level="18.1.1" data-path="ADAMForecastingExpectation.html"><a href="ADAMForecastingExpectation.html#ADAMForecastingExpectationSimulations"><i class="fa fa-check"></i><b>18.1.1</b> Simulating demand trajectories</a></li>
<li class="chapter" data-level="18.1.2" data-path="ADAMForecastingExpectation.html"><a href="ADAMForecastingExpectation.html#explanatory-variables"><i class="fa fa-check"></i><b>18.1.2</b> Explanatory variables</a></li>
<li class="chapter" data-level="18.1.3" data-path="ADAMForecastingExpectation.html"><a href="ADAMForecastingExpectation.html#demonstration-in-r"><i class="fa fa-check"></i><b>18.1.3</b> Demonstration in R</a></li>
</ul></li>
<li class="chapter" data-level="18.2" data-path="ADAMForecastingPI.html"><a href="ADAMForecastingPI.html"><i class="fa fa-check"></i><b>18.2</b> Prediction intervals</a>
<ul>
<li class="chapter" data-level="18.2.1" data-path="ADAMForecastingPI.html"><a href="ADAMForecastingPI.html#approximate-intervals"><i class="fa fa-check"></i><b>18.2.1</b> Approximate intervals</a></li>
<li class="chapter" data-level="18.2.2" data-path="ADAMForecastingPI.html"><a href="ADAMForecastingPI.html#ADAMForecastingPISimulations"><i class="fa fa-check"></i><b>18.2.2</b> Simulated intervals</a></li>
<li class="chapter" data-level="18.2.3" data-path="ADAMForecastingPI.html"><a href="ADAMForecastingPI.html#semiparametric-intervals"><i class="fa fa-check"></i><b>18.2.3</b> Semiparametric intervals</a></li>
<li class="chapter" data-level="18.2.4" data-path="ADAMForecastingPI.html"><a href="ADAMForecastingPI.html#nonparametric-intervals"><i class="fa fa-check"></i><b>18.2.4</b> Nonparametric intervals</a></li>
<li class="chapter" data-level="18.2.5" data-path="ADAMForecastingPI.html"><a href="ADAMForecastingPI.html#ADAMForecastingPIEmpirical"><i class="fa fa-check"></i><b>18.2.5</b> Empirical intervals</a></li>
<li class="chapter" data-level="18.2.6" data-path="ADAMForecastingPI.html"><a href="ADAMForecastingPI.html#complete-parametric-intervals"><i class="fa fa-check"></i><b>18.2.6</b> Complete parametric intervals</a></li>
<li class="chapter" data-level="18.2.7" data-path="ADAMForecastingPI.html"><a href="ADAMForecastingPI.html#explanatory-variables-1"><i class="fa fa-check"></i><b>18.2.7</b> Explanatory variables</a></li>
<li class="chapter" data-level="18.2.8" data-path="ADAMForecastingPI.html"><a href="ADAMForecastingPI.html#ADAMForecastingPIExample"><i class="fa fa-check"></i><b>18.2.8</b> Example in R</a></li>
</ul></li>
<li class="chapter" data-level="18.3" data-path="forecastingADAMOther.html"><a href="forecastingADAMOther.html"><i class="fa fa-check"></i><b>18.3</b> Other aspects of forecast uncertainty</a>
<ul>
<li class="chapter" data-level="18.3.1" data-path="forecastingADAMOther.html"><a href="forecastingADAMOther.html#constructing-intervals-for-intermittent-demand-model"><i class="fa fa-check"></i><b>18.3.1</b> Constructing intervals for intermittent demand model</a></li>
<li class="chapter" data-level="18.3.2" data-path="forecastingADAMOther.html"><a href="forecastingADAMOther.html#forecastingADAMOtherOneSided"><i class="fa fa-check"></i><b>18.3.2</b> One-sided prediction interval</a></li>
<li class="chapter" data-level="18.3.3" data-path="forecastingADAMOther.html"><a href="forecastingADAMOther.html#forecastingADAMOtherCumulative"><i class="fa fa-check"></i><b>18.3.3</b> Cumulative over the horizon forecast</a></li>
<li class="chapter" data-level="18.3.4" data-path="forecastingADAMOther.html"><a href="forecastingADAMOther.html#forecastingADAMOtherExample"><i class="fa fa-check"></i><b>18.3.4</b> Example in R</a></li>
<li class="chapter" data-level="18.3.5" data-path="forecastingADAMOther.html"><a href="forecastingADAMOther.html#confidence-interval"><i class="fa fa-check"></i><b>18.3.5</b> Confidence interval</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="19" data-path="conclusions.html"><a href="conclusions.html"><i class="fa fa-check"></i><b>19</b> What’s next?</a></li>
<li class="chapter" data-level="" data-path="about-the-author.html"><a href="about-the-author.html"><i class="fa fa-check"></i>About the author</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Forecasting and Analytics with ADAM</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="ADAMMultipleFrequenciesExamples" class="section level2" number="12.5">
<h2><span class="header-section-number">12.5</span> Examples of application</h2>
<div id="adam-ets" class="section level3" number="12.5.1">
<h3><span class="header-section-number">12.5.1</span> ADAM ETS</h3>
<p>We will use the <code>taylor</code> series from the <code>forecast</code> package to see how ADAM can be applied to high-frequency data. This is half-hourly electricity demand in England and Wales from Monday 5th June 2000 to Sunday 27th August 2000, used in <span class="citation"><a href="#ref-Taylor2003a" role="doc-biblioref">James W. Taylor</a> (<a href="#ref-Taylor2003a" role="doc-biblioref">2003b</a>)</span>.</p>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb176-1"><a href="ADAMMultipleFrequenciesExamples.html#cb176-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(zoo)</span>
<span id="cb176-2"><a href="ADAMMultipleFrequenciesExamples.html#cb176-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">zoo</span>(forecast<span class="sc">::</span>taylor,</span>
<span id="cb176-3"><a href="ADAMMultipleFrequenciesExamples.html#cb176-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">order.by=</span><span class="fu">as.POSIXct</span>(<span class="st">&quot;2000/06/05&quot;</span>)<span class="sc">+</span></span>
<span id="cb176-4"><a href="ADAMMultipleFrequenciesExamples.html#cb176-4" aria-hidden="true" tabindex="-1"></a>           (<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(forecast<span class="sc">::</span>taylor))<span class="sc">-</span><span class="dv">1</span>)<span class="sc">*</span><span class="dv">60</span><span class="sc">*</span><span class="dv">30</span>)</span></code></pre></div>
<pre><code>## Registered S3 method overwritten by &#39;quantmod&#39;:
##   method            from
##   as.zoo.data.frame zoo</code></pre>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="ADAMMultipleFrequenciesExamples.html#cb178-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(y)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:taylorSeries"></span>
<img src="Svetunkov--2022----ADAM_files/figure-html/taylorSeries-1.png" alt="Half-hourly electricity demand in England and Wales" width="672" />
<p class="caption">
Figure 12.1: Half-hourly electricity demand in England and Wales
</p>
</div>
<p>The series in Figure <a href="ADAMMultipleFrequenciesExamples.html#fig:taylorSeries">12.1</a> does not exhibit an apparent trend but has two seasonal cycles: a half-hour of day and day of the week. Seasonality seems to be multiplicative because, with the reduction of the level of series, the amplitude of seasonality also reduces. We will try several different models and see how they compare. In all the cases below, we will use backcasting to initialise the model. We will use the last 336 observations (<span class="math inline">\(48 \times 7\)</span>) as the holdout to see whether models perform adequately or not.</p>
<div class="remark">
<p><span id="unlabeled-div-19" class="remark"><em>Remark</em>. </span>When we have data with DST or Leap years (as discussed in Section <a href="MultipleFrequenciesDSTandLeap.html#MultipleFrequenciesDSTandLeap">12.4</a>), <code>adam()</code> will automatically correct the seasonal lags as long as your data contains specific dates (as <code>zoo</code> objects have, for example).</p>
</div>
<p>First, it is ADAM ETS(M,N,M) with <code>lags=c(48,7*48)</code>:</p>
<div class="sourceCode" id="cb179"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb179-1"><a href="ADAMMultipleFrequenciesExamples.html#cb179-1" aria-hidden="true" tabindex="-1"></a>adamModelETSMNM <span class="ot">&lt;-</span> <span class="fu">adam</span>(y, <span class="st">&quot;MNM&quot;</span>, <span class="at">lags=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">48</span>,<span class="dv">336</span>),</span>
<span id="cb179-2"><a href="ADAMMultipleFrequenciesExamples.html#cb179-2" aria-hidden="true" tabindex="-1"></a>                        <span class="at">h=</span><span class="dv">336</span>, <span class="at">holdout=</span><span class="cn">TRUE</span>,</span>
<span id="cb179-3"><a href="ADAMMultipleFrequenciesExamples.html#cb179-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">initial=</span><span class="st">&quot;back&quot;</span>)</span>
<span id="cb179-4"><a href="ADAMMultipleFrequenciesExamples.html#cb179-4" aria-hidden="true" tabindex="-1"></a>adamModelETSMNM</span></code></pre></div>
<pre><code>## Time elapsed: 0.45 seconds
## Model estimated using adam() function: ETS(MNM)[48, 336]
## Distribution assumed in the model: Gamma
## Loss function type: likelihood; Loss function value: 25682.88
## Persistence vector g:
##  alpha gamma1 gamma2 
## 0.1357 0.2813 0.2335 
## 
## Sample size: 3696
## Number of estimated parameters: 4
## Number of degrees of freedom: 3692
## Information criteria:
##      AIC     AICc      BIC     BICc 
## 51373.76 51373.77 51398.62 51398.66 
## 
## Forecast errors:
## ME: 625.221; MAE: 716.941; RMSE: 817.796
## sCE: 709.966%; Asymmetry: 90.4%; sMAE: 2.423%; sMSE: 0.076%
## MASE: 1.103; RMSSE: 0.867; rMAE: 0.107; rRMSE: 0.1</code></pre>
<p>Notice that the seasonal smoothing parameters are relatively high in this model. For example, the second <span class="math inline">\(\gamma\)</span> is equal to 0.2335, which means that the model adapts the seasonal profile to the data substantially (takes 23.35% of the error from the previous observation in it). Furthermore, the smoothing parameter <span class="math inline">\(\alpha\)</span> is equal to 0.1357, which is also potentially too high, given that we have well-behaved data and that we deal with a multiplicative model. This might indicate that the model overfits the data. To see if this is the case, we can produce the plot of components over time (Figure <a href="ADAMMultipleFrequenciesExamples.html#fig:adamModelETSMNM12">12.2</a>).</p>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb181-1"><a href="ADAMMultipleFrequenciesExamples.html#cb181-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(adamModelETSMNM,<span class="dv">12</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:adamModelETSMNM12"></span>
<img src="Svetunkov--2022----ADAM_files/figure-html/adamModelETSMNM12-1.png" alt="Half-hourly electricity demand data decomposition according to ETS(M,N,M)[48,336]" width="672" />
<p class="caption">
Figure 12.2: Half-hourly electricity demand data decomposition according to ETS(M,N,M)[48,336]
</p>
</div>
<p>As the plot in Figure <a href="ADAMMultipleFrequenciesExamples.html#fig:adamModelETSMNM12">12.2</a> shows, the level of series repeats the seasonal pattern in the original data, although in a diminished way. In addition, the second seasonal component repeats the intra-day seasonality in it, although it is also reduced.</p>
<p>Next, we can plot the fitted values and forecasts to see how the model performs overall (Figure <a href="ADAMMultipleFrequenciesExamples.html#fig:adamModelETSMNM">12.3</a>).</p>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb182-1"><a href="ADAMMultipleFrequenciesExamples.html#cb182-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(adamModelETSMNM,<span class="dv">7</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:adamModelETSMNM"></span>
<img src="Svetunkov--2022----ADAM_files/figure-html/adamModelETSMNM-1.png" alt="The fit and the forecast of the ETS(M,N,M)[48,336] model on half-hourly electricity demand data." width="672" />
<p class="caption">
Figure 12.3: The fit and the forecast of the ETS(M,N,M)[48,336] model on half-hourly electricity demand data.
</p>
</div>
<p>As we might notice from Figure <a href="ADAMMultipleFrequenciesExamples.html#fig:adamModelETSMNM">12.3</a> the model was constructed in 0.45 seconds, and while it might not be the most accurate model for the data, it fits it well and produces reasonable forecasts. So, it is a good starting point. If we want to improve upon it, we can try one of the multistep estimators, for example, GTMSE (Subsection <a href="multistepLosses.html#multistepLossesGTMSE">11.3.3</a>):</p>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb183-1"><a href="ADAMMultipleFrequenciesExamples.html#cb183-1" aria-hidden="true" tabindex="-1"></a>adamModelETSMNMGTMSE <span class="ot">&lt;-</span> <span class="fu">adam</span>(y, <span class="st">&quot;MNM&quot;</span>, <span class="at">lags=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">48</span>,<span class="dv">336</span>),</span>
<span id="cb183-2"><a href="ADAMMultipleFrequenciesExamples.html#cb183-2" aria-hidden="true" tabindex="-1"></a>                             <span class="at">h=</span><span class="dv">336</span>, <span class="at">holdout=</span><span class="cn">TRUE</span>,</span>
<span id="cb183-3"><a href="ADAMMultipleFrequenciesExamples.html#cb183-3" aria-hidden="true" tabindex="-1"></a>                             <span class="at">initial=</span><span class="st">&quot;back&quot;</span>, <span class="at">loss=</span><span class="st">&quot;GTMSE&quot;</span>)</span></code></pre></div>
<p>The function will take more time due to complexity in the loss function calculation, but hopefully, it will produce more accurate forecasts due to shrinkage of smoothing parameters:</p>
<div class="sourceCode" id="cb184"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb184-1"><a href="ADAMMultipleFrequenciesExamples.html#cb184-1" aria-hidden="true" tabindex="-1"></a>adamModelETSMNMGTMSE</span></code></pre></div>
<pre><code>## Time elapsed: 23.06 seconds
## Model estimated using adam() function: ETS(MNM)[48, 336]
## Distribution assumed in the model: Normal
## Loss function type: GTMSE; Loss function value: -2648.698
## Persistence vector g:
##  alpha gamma1 gamma2 
## 0.0314 0.2604 0.1414 
## 
## Sample size: 3696
## Number of estimated parameters: 3
## Number of degrees of freedom: 3693
## Information criteria are unavailable for the chosen loss &amp; distribution.
## 
## Forecast errors:
## ME: 216.71; MAE: 376.291; RMSE: 505.375
## sCE: 246.084%; Asymmetry: 63%; sMAE: 1.272%; sMSE: 0.029%
## MASE: 0.579; RMSSE: 0.535; rMAE: 0.056; rRMSE: 0.062</code></pre>
<p>The smoothing parameters of the second model are closer to zero than in the first one, which might mean that it does not overfit the data as much. We can analyse the components of the second model by plotting them over time, similarly to how we did it for the previous model (Figure <a href="ADAMMultipleFrequenciesExamples.html#fig:adamModelETSMNMGTMSE12">12.4</a>):</p>
<div class="sourceCode" id="cb186"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb186-1"><a href="ADAMMultipleFrequenciesExamples.html#cb186-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(adamModelETSMNMGTMSE,<span class="dv">12</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:adamModelETSMNMGTMSE12"></span>
<img src="Svetunkov--2022----ADAM_files/figure-html/adamModelETSMNMGTMSE12-1.png" alt="Half-hourly electricity demand data decomposition according to ETS(M,N,M)[48,336] estimated with GTMSE." width="672" />
<p class="caption">
Figure 12.4: Half-hourly electricity demand data decomposition according to ETS(M,N,M)[48,336] estimated with GTMSE.
</p>
</div>
<p>The components on the plot in Figure <a href="ADAMMultipleFrequenciesExamples.html#fig:adamModelETSMNMGTMSE12">12.4</a> are still not ideal, but at least the level does not seem to contain the seasonality in it anymore. The seasonal components could still be improved if, for example, the initial seasonal indices were smoother (this applies especially to the seasonal component 2).</p>
<p>Comparing the accuracy of the two models, for example, using RMSSE, we can conclude that the one with GTMSE was more accurate than the one estimated using the conventional likelihood.</p>
<p>Another potential way of improvement for the model is the inclusion of AR(1) term, as for example done by <span class="citation"><a href="#ref-Taylor2010" role="doc-biblioref">Taylor</a> (<a href="#ref-Taylor2010" role="doc-biblioref">2010</a>)</span>. This might take more time than the first model, but could also lead to some improvements in the accuracy:</p>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb187-1"><a href="ADAMMultipleFrequenciesExamples.html#cb187-1" aria-hidden="true" tabindex="-1"></a>adamModelETSMNMAR <span class="ot">&lt;-</span> <span class="fu">adam</span>(y, <span class="st">&quot;MNM&quot;</span>, <span class="at">lags=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">48</span>,<span class="dv">336</span>),</span>
<span id="cb187-2"><a href="ADAMMultipleFrequenciesExamples.html#cb187-2" aria-hidden="true" tabindex="-1"></a>                          <span class="at">initial=</span><span class="st">&quot;back&quot;</span>, <span class="at">orders=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>),</span>
<span id="cb187-3"><a href="ADAMMultipleFrequenciesExamples.html#cb187-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">h=</span><span class="dv">336</span>, <span class="at">holdout=</span><span class="cn">TRUE</span>, <span class="at">maxeval=</span><span class="dv">1000</span>)</span></code></pre></div>
<p>Estimating the ETS+ARIMA model is a complicated task because of the increase of dimensionality of the matrices in the transition equation. Still, by default, the number of iterations would be restricted by 160, which might not be enough to get to the minimum of the loss. This is why I increased the number of iterations in the example above to 1000. If you want to get more feedback on how the optimisation has been carried out, you can ask the function to print details via <code>print_level=41</code>.</p>
<div class="sourceCode" id="cb188"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb188-1"><a href="ADAMMultipleFrequenciesExamples.html#cb188-1" aria-hidden="true" tabindex="-1"></a>adamModelETSMNMAR</span></code></pre></div>
<pre><code>## Time elapsed: 2.07 seconds
## Model estimated using adam() function: ETS(MNM)[48, 336]+ARIMA(1,0,0)
## Distribution assumed in the model: Gamma
## Loss function type: likelihood; Loss function value: 24108.2
## Persistence vector g:
##  alpha gamma1 gamma2 
## 0.1129 0.2342 0.3180 
## 
## ARMA parameters of the model:
## AR:
## phi1[1] 
##  0.6923 
## 
## Sample size: 3696
## Number of estimated parameters: 5
## Number of degrees of freedom: 3691
## Information criteria:
##      AIC     AICc      BIC     BICc 
## 48226.39 48226.41 48257.47 48257.54 
## 
## Forecast errors:
## ME: 257.38; MAE: 435.476; RMSE: 561.237
## sCE: 292.266%; Asymmetry: 67.2%; sMAE: 1.472%; sMSE: 0.036%
## MASE: 0.67; RMSSE: 0.595; rMAE: 0.065; rRMSE: 0.069</code></pre>
<p>In this specific example, we see that the ADAM ETS(M,N,M)+AR(1) leads to a slight improvement in accuracy in comparison with the ADAM ETS(M,N,M) estimated using the conventional loss function.</p>
</div>
<div id="adam-etsx" class="section level3" number="12.5.2">
<h3><span class="header-section-number">12.5.2</span> ADAM ETSX</h3>
<p>Another option of dealing with multiple seasonalities, as discussed in Section <a href="ETSXMultipleSeasonality.html#ETSXMultipleSeasonality">12.3</a>, is the introduction of explanatory variables. We start with a static model that captures half-hours of the day via its seasonal component and days of week frequency via an explanatory variable. We will use the <code>temporaldummy()</code> function from the <code>greybox</code> package to create respective categorical variables. This function works much better when the data contains proper time stamps and, for example, is of class <code>zoo</code> or <code>xts</code>:</p>
<div class="sourceCode" id="cb190"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb190-1"><a href="ADAMMultipleFrequenciesExamples.html#cb190-1" aria-hidden="true" tabindex="-1"></a>x1 <span class="ot">&lt;-</span> <span class="fu">temporaldummy</span>(y,<span class="at">type=</span><span class="st">&quot;day&quot;</span>,<span class="at">of=</span><span class="st">&quot;week&quot;</span>,<span class="at">factors=</span><span class="cn">TRUE</span>)</span>
<span id="cb190-2"><a href="ADAMMultipleFrequenciesExamples.html#cb190-2" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">&lt;-</span> <span class="fu">temporaldummy</span>(y,<span class="at">type=</span><span class="st">&quot;hour&quot;</span>,<span class="at">of=</span><span class="st">&quot;day&quot;</span>,<span class="at">factors=</span><span class="cn">TRUE</span>)</span>
<span id="cb190-3"><a href="ADAMMultipleFrequenciesExamples.html#cb190-3" aria-hidden="true" tabindex="-1"></a>taylorData <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">y=</span>y,<span class="at">x1=</span>x1,<span class="at">x2=</span>x2)</span></code></pre></div>
<p>This function becomes especially useful when dealing with DST and Leap years (see Section <a href="MultipleFrequenciesDSTandLeap.html#MultipleFrequenciesDSTandLeap">12.4</a>) because it will encode the dummy variables based on dates, allowing to sidestep the issue with changing frequency in the data. We can now fit the ADAM ETSX model with dummy variables for days of the week:</p>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb191-1"><a href="ADAMMultipleFrequenciesExamples.html#cb191-1" aria-hidden="true" tabindex="-1"></a>adamModelETSXMNN <span class="ot">&lt;-</span> <span class="fu">adam</span>(taylorData, <span class="st">&quot;MNN&quot;</span>, <span class="at">h=</span><span class="dv">336</span>, <span class="at">holdout=</span><span class="cn">TRUE</span>,</span>
<span id="cb191-2"><a href="ADAMMultipleFrequenciesExamples.html#cb191-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">initial=</span><span class="st">&quot;back&quot;</span>)</span></code></pre></div>
<p>In the code above, we use the initialisation via backcasting (see discussion in Section <a href="ADAMInitialisation.html#ADAMInitialisationOptAndBack">11.4.1</a>), because otherwise the calculation will take much more time and might require additional manual tuning. Here is what we get as a result:</p>
<div class="sourceCode" id="cb192"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb192-1"><a href="ADAMMultipleFrequenciesExamples.html#cb192-1" aria-hidden="true" tabindex="-1"></a>adamModelETSXMNN</span></code></pre></div>
<pre><code>## Time elapsed: 0.61 seconds
## Model estimated using adam() function: ETSX(MNN)
## Distribution assumed in the model: Gamma
## Loss function type: likelihood; Loss function value: 30155.54
## Persistence vector g (excluding xreg):
##  alpha 
## 0.6182 
## 
## Sample size: 3696
## Number of estimated parameters: 2
## Number of degrees of freedom: 3694
## Information criteria:
##      AIC     AICc      BIC     BICc 
## 60315.08 60315.09 60327.51 60327.53 
## 
## Forecast errors:
## ME: -1664.294; MAE: 1781.472; RMSE: 2070.321
## sCE: -1889.878%; Asymmetry: -92.3%; sMAE: 6.021%; sMSE: 0.49%
## MASE: 2.74; RMSSE: 2.194; rMAE: 0.266; rRMSE: 0.253</code></pre>
<p>The resulting model produces biased forecasts (they are consistently higher than needed). This is mainly because the smoothing parameter <span class="math inline">\(\alpha\)</span> is too high, and the model frequently changes the level. We can see that in the plot of the state (Figure @ref(fig:adamModelETSXMNN12_1)):</p>
<div class="sourceCode" id="cb194"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb194-1"><a href="ADAMMultipleFrequenciesExamples.html#cb194-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(adamModelETSXMNN<span class="sc">$</span>states[,<span class="dv">1</span>], <span class="at">ylab=</span><span class="st">&quot;Level&quot;</span>)</span></code></pre></div>
<div class="figure">
<img src="Svetunkov--2022----ADAM_files/figure-html/adamModelETSXMNN12_1-1.png" alt="Plot of the level of the ETSX model." width="672" />
<p class="caption">
(#fig:adamModelETSXMNN12_1)Plot of the level of the ETSX model.
</p>
</div>
<p>As we see from Figure @ref(fig:adamModelETSXMNN12_1), the level component absorbs seasonality, which causes forecasting accuracy issues. However, the obtained value did not happen due to randomness – this is what the model does when seasonality is fixed and is not allowed to evolve. To reduce the model’s sensitivity, we can shrink the smoothing parameter using a multistep estimator (discussed in Section <a href="multistepLosses.html#multistepLosses">11.3</a>). But as discussed earlier, these estimators are typically slower than the conventional ones, so that they might take more computational time:</p>
<div class="sourceCode" id="cb195"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb195-1"><a href="ADAMMultipleFrequenciesExamples.html#cb195-1" aria-hidden="true" tabindex="-1"></a>adamModelETSXMNNGTMSE <span class="ot">&lt;-</span> <span class="fu">adam</span>(taylorData, <span class="st">&quot;MNN&quot;</span>,</span>
<span id="cb195-2"><a href="ADAMMultipleFrequenciesExamples.html#cb195-2" aria-hidden="true" tabindex="-1"></a>                              <span class="at">h=</span><span class="dv">336</span>, <span class="at">holdout=</span><span class="cn">TRUE</span>,</span>
<span id="cb195-3"><a href="ADAMMultipleFrequenciesExamples.html#cb195-3" aria-hidden="true" tabindex="-1"></a>                              <span class="at">initial=</span><span class="st">&quot;back&quot;</span>, <span class="at">loss=</span><span class="st">&quot;GTMSE&quot;</span>)</span>
<span id="cb195-4"><a href="ADAMMultipleFrequenciesExamples.html#cb195-4" aria-hidden="true" tabindex="-1"></a>adamModelETSXMNNGTMSE</span></code></pre></div>
<pre><code>## Time elapsed: 39.26 seconds
## Model estimated using adam() function: ETSX(MNN)
## Distribution assumed in the model: Normal
## Loss function type: GTMSE; Loss function value: -2044.705
## Persistence vector g (excluding xreg):
##  alpha 
## 0.0153 
## 
## Sample size: 3696
## Number of estimated parameters: 1
## Number of degrees of freedom: 3695
## Information criteria are unavailable for the chosen loss &amp; distribution.
## 
## Forecast errors:
## ME: 105.462; MAE: 921.897; RMSE: 1204.967
## sCE: 119.757%; Asymmetry: 18%; sMAE: 3.116%; sMSE: 0.166%
## MASE: 1.418; RMSSE: 1.277; rMAE: 0.138; rRMSE: 0.147</code></pre>
<p>While the model’s performance with GTMSE has improved due to the shrinkage of <span class="math inline">\(\alpha\)</span> to zero, the seasonal states are still deterministic and do not adapt to the changes in data. We could adapt them via <code>regressors="adapt"</code>, but then we would be constructing the ETS(M,N,M)[48,336] model but in a less efficient way. Alternatively, we could assume that one of the seasonal states is deterministic and, for example, construct the ETSX(M,N,M) model:</p>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb197-1"><a href="ADAMMultipleFrequenciesExamples.html#cb197-1" aria-hidden="true" tabindex="-1"></a>adamModelETSXMNMGTMSE <span class="ot">&lt;-</span> <span class="fu">adam</span>(taylorData, <span class="st">&quot;MNM&quot;</span>, <span class="at">lags=</span><span class="dv">48</span>,</span>
<span id="cb197-2"><a href="ADAMMultipleFrequenciesExamples.html#cb197-2" aria-hidden="true" tabindex="-1"></a>                              <span class="at">h=</span><span class="dv">336</span>, <span class="at">holdout=</span><span class="cn">TRUE</span>,</span>
<span id="cb197-3"><a href="ADAMMultipleFrequenciesExamples.html#cb197-3" aria-hidden="true" tabindex="-1"></a>                              <span class="at">initial=</span><span class="st">&quot;back&quot;</span>, <span class="at">loss=</span><span class="st">&quot;GTMSE&quot;</span>,</span>
<span id="cb197-4"><a href="ADAMMultipleFrequenciesExamples.html#cb197-4" aria-hidden="true" tabindex="-1"></a>                              <span class="at">formula=</span>y<span class="sc">~</span>x1)</span>
<span id="cb197-5"><a href="ADAMMultipleFrequenciesExamples.html#cb197-5" aria-hidden="true" tabindex="-1"></a>adamModelETSXMNMGTMSE</span></code></pre></div>
<pre><code>## Time elapsed: 33.56 seconds
## Model estimated using adam() function: ETSX(MNM)
## Distribution assumed in the model: Normal
## Loss function type: GTMSE; Loss function value: -2082.17
## Persistence vector g (excluding xreg):
##  alpha  gamma 
## 0.0135 0.0769 
## 
## Sample size: 3696
## Number of estimated parameters: 2
## Number of degrees of freedom: 3694
## Information criteria are unavailable for the chosen loss &amp; distribution.
## 
## Forecast errors:
## ME: 146.436; MAE: 830.332; RMSE: 1055.372
## sCE: 166.284%; Asymmetry: 27.1%; sMAE: 2.806%; sMSE: 0.127%
## MASE: 1.277; RMSSE: 1.118; rMAE: 0.124; rRMSE: 0.129</code></pre>
<p>We can see an improvement compared to the previous model, so the seasonal states do change over time, which means that the deterministic seasonality is not appropriate in our example. However, it might be more suitable in some other cases, producing more accurate forecasts than the models assuming stochastic seasonality.</p>
</div>
<div id="adam-arima" class="section level3" number="12.5.3">
<h3><span class="header-section-number">12.5.3</span> ADAM ARIMA</h3>
<p>Another model we can try on this data is ARIMA. We have not yet discussed the order selection mechanism for ARIMA, so I will construct a model based on my judgment. Keeping in mind that ETS(A,N,N) is equivalent to ARIMA(0,1,1) and that the changing seasonality in ARIMA context can be modelled with seasonal differences, I will construct SARIMA(0,1,1)(0,1,1)<span class="math inline">\(_{336}\)</span>, skipping the frequencies for a half-hour of the day. Hopefully, this will be enough to model: (a) changing level of data; (b) changing seasonal amplitude. Here is how we can construct this model using <code>adam()</code>:</p>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb199-1"><a href="ADAMMultipleFrequenciesExamples.html#cb199-1" aria-hidden="true" tabindex="-1"></a>adamModelARIMA <span class="ot">&lt;-</span> <span class="fu">adam</span>(y, <span class="st">&quot;NNN&quot;</span>, <span class="at">lags=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">336</span>), <span class="at">initial=</span><span class="st">&quot;back&quot;</span>,</span>
<span id="cb199-2"><a href="ADAMMultipleFrequenciesExamples.html#cb199-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">orders=</span><span class="fu">list</span>(<span class="at">i=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>),<span class="at">ma=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>)),</span>
<span id="cb199-3"><a href="ADAMMultipleFrequenciesExamples.html#cb199-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">h=</span><span class="dv">336</span>, <span class="at">holdout=</span><span class="cn">TRUE</span>)</span>
<span id="cb199-4"><a href="ADAMMultipleFrequenciesExamples.html#cb199-4" aria-hidden="true" tabindex="-1"></a>adamModelARIMA</span></code></pre></div>
<pre><code>## Time elapsed: 0.21 seconds
## Model estimated using adam() function: SARIMA(0,1,1)[1](0,1,1)[336]
## Distribution assumed in the model: Normal
## Loss function type: likelihood; Loss function value: 26098.76
## ARMA parameters of the model:
## MA:
##   theta1[1] theta1[336] 
##      0.5086     -0.1977 
## 
## Sample size: 3696
## Number of estimated parameters: 3
## Number of degrees of freedom: 3693
## Information criteria:
##      AIC     AICc      BIC     BICc 
## 52203.53 52203.53 52222.17 52222.20 
## 
## Forecast errors:
## ME: 49.339; MAE: 373.387; RMSE: 499.661
## sCE: 56.027%; Asymmetry: 18.6%; sMAE: 1.262%; sMSE: 0.029%
## MASE: 0.574; RMSSE: 0.529; rMAE: 0.056; rRMSE: 0.061</code></pre>
<p>Figure <a href="ADAMMultipleFrequenciesExamples.html#fig:adamModelARIMA">12.5</a> shows the fit and forecast from this model.</p>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb201-1"><a href="ADAMMultipleFrequenciesExamples.html#cb201-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(adamModelARIMA,<span class="dv">7</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:adamModelARIMA"></span>
<img src="Svetunkov--2022----ADAM_files/figure-html/adamModelARIMA-1.png" alt="The fit and the forecast of the ARIMA(0,1,1)(0,1,1)$_336$ model on half-hourly electricity demand data." width="672" />
<p class="caption">
Figure 12.5: The fit and the forecast of the ARIMA(0,1,1)(0,1,1)<span class="math inline">\(_336\)</span> model on half-hourly electricity demand data.
</p>
</div>
<p>This model is directly comparable with ADAM ETS via information criteria, and as we can see, it is worse than ADAM ETS(M,N,M)+AR(1) and multiple seasonal ETS(M,N,M) in terms of AICc. But it is better in terms of the holdout RMSSE, producing more accurate forecasts. We could analyse the residuals of this model and iteratively test whether the addition of AR terms and a half-hour of day seasonality improves the model’s accuracy. We could also try ARIMA models with different distributions, compare them and select the most appropriate one. The reader is encouraged to do this on their own.</p>

</div>
</div>
<!-- </div> -->
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-Taylor2010" class="csl-entry">
• Taylor, J.W., 2010. <span class="nocase">Triple seasonal methods for short-term electricity demand forecasting</span>. European Journal of Operational Research. 204, 139–152. <a href="https://doi.org/10.1016/j.ejor.2009.10.003">https://doi.org/10.1016/j.ejor.2009.10.003</a>
</div>
<div id="ref-Taylor2003a" class="csl-entry">
• Taylor, James W., 2003b. <span class="nocase">Short-term electricity demand forecasting using double seasonal exponential smoothing</span>. Journal of the Operational Research Society. 54, 799–805. <a href="https://doi.org/10.1057/palgrave.jors.2601589">https://doi.org/10.1057/palgrave.jors.2601589</a>
</div>
</div>

            </section>

          </div>
        </div>
      </div>
<a href="MultipleFrequenciesDSTandLeap.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="ADAMIntermittent.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/config-i1/adam/tree/master/Chapters//12-ADAM-ETS-Multiple-Frequencies.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Svetunkov (2022) - ADAM.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
