<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>11.1 Maximum Likelihood Estimation | Forecasting and Analytics with ADAM</title>
  <meta name="description" content="This textbook explains how to do time series analysis and forecasting using Augmented Dynamic Adaptive Model, implemented in smooth package for R." />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="11.1 Maximum Likelihood Estimation | Forecasting and Analytics with ADAM" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This textbook explains how to do time series analysis and forecasting using Augmented Dynamic Adaptive Model, implemented in smooth package for R." />
  <meta name="github-repo" content="config-i1/adam" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="11.1 Maximum Likelihood Estimation | Forecasting and Analytics with ADAM" />
  
  <meta name="twitter:description" content="This textbook explains how to do time series analysis and forecasting using Augmented Dynamic Adaptive Model, implemented in smooth package for R." />
  

<meta name="author" content="Ivan Svetunkov" />


<meta name="date" content="2021-07-08" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="ADAMETSEstimation.html"/>
<link rel="next" href="non-mle-based-loss-functions.html"/>
<script src="libs/header-attrs-2.9/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>
<script async defer src="https://hypothes.is/embed.js"></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-XH37Z8VYP8"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-XH37Z8VYP8');
</script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Forecasting and Analytics with ADAM</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#license"><i class="fa fa-check"></i>License</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#acknowledgments"><i class="fa fa-check"></i>Acknowledgments</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="forecastingProcess.html"><a href="forecastingProcess.html"><i class="fa fa-check"></i><b>2</b> Forecasts evaluation</a>
<ul>
<li class="chapter" data-level="2.1" data-path="errorMeasures.html"><a href="errorMeasures.html"><i class="fa fa-check"></i><b>2.1</b> Measuring accuracy of point forecasts</a></li>
<li class="chapter" data-level="2.2" data-path="uncertainty.html"><a href="uncertainty.html"><i class="fa fa-check"></i><b>2.2</b> Measuring uncertainty</a></li>
<li class="chapter" data-level="2.3" data-path="rollingOrigin.html"><a href="rollingOrigin.html"><i class="fa fa-check"></i><b>2.3</b> Rolling origin</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="rollingOrigin.html"><a href="rollingOrigin.html#principles-of-rolling-origin"><i class="fa fa-check"></i><b>2.3.1</b> Principles of Rolling origin</a></li>
<li class="chapter" data-level="2.3.2" data-path="rollingOrigin.html"><a href="rollingOrigin.html#rolling-origin-in-r"><i class="fa fa-check"></i><b>2.3.2</b> Rolling origin in R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="tsDecomposition.html"><a href="tsDecomposition.html"><i class="fa fa-check"></i><b>3</b> From time series components to ETS</a>
<ul>
<li class="chapter" data-level="3.1" data-path="tsComponents.html"><a href="tsComponents.html"><i class="fa fa-check"></i><b>3.1</b> Time series components</a></li>
<li class="chapter" data-level="3.2" data-path="ClassicalDecomposition.html"><a href="ClassicalDecomposition.html"><i class="fa fa-check"></i><b>3.2</b> Classical Seasonal Decomposition</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="ClassicalDecomposition.html"><a href="ClassicalDecomposition.html#how-to-do"><i class="fa fa-check"></i><b>3.2.1</b> How to do?</a></li>
<li class="chapter" data-level="3.2.2" data-path="ClassicalDecomposition.html"><a href="ClassicalDecomposition.html#a-couple-of-examples"><i class="fa fa-check"></i><b>3.2.2</b> A couple of examples</a></li>
<li class="chapter" data-level="3.2.3" data-path="ClassicalDecomposition.html"><a href="ClassicalDecomposition.html#other-techniques"><i class="fa fa-check"></i><b>3.2.3</b> Other techniques</a></li>
<li class="chapter" data-level="3.2.4" data-path="ClassicalDecomposition.html"><a href="ClassicalDecomposition.html#why-bother"><i class="fa fa-check"></i><b>3.2.4</b> “Why bother?”</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="ETSTaxonomy.html"><a href="ETSTaxonomy.html"><i class="fa fa-check"></i><b>3.3</b> ETS taxonomy</a></li>
<li class="chapter" data-level="3.4" data-path="ETSTaxonomyMaths.html"><a href="ETSTaxonomyMaths.html"><i class="fa fa-check"></i><b>3.4</b> Mathematical models in the ETS taxonomy</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="conventional-exponential-smoothing.html"><a href="conventional-exponential-smoothing.html"><i class="fa fa-check"></i><b>4</b> Conventional Exponential Smoothing</a>
<ul>
<li class="chapter" data-level="4.1" data-path="SES.html"><a href="SES.html"><i class="fa fa-check"></i><b>4.1</b> Simple Exponential Smoothing</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="SES.html"><a href="SES.html#examples-of-application"><i class="fa fa-check"></i><b>4.1.1</b> Examples of application</a></li>
<li class="chapter" data-level="4.1.2" data-path="SES.html"><a href="SES.html#whyExponential"><i class="fa fa-check"></i><b>4.1.2</b> Why “exponential?”</a></li>
<li class="chapter" data-level="4.1.3" data-path="SES.html"><a href="SES.html#error-correction-form-of-ses"><i class="fa fa-check"></i><b>4.1.3</b> Error correction form of SES</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="SESandETS.html"><a href="SESandETS.html"><i class="fa fa-check"></i><b>4.2</b> SES and ETS</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="SESandETS.html"><a href="SESandETS.html#etsann"><i class="fa fa-check"></i><b>4.2.1</b> ETS(A,N,N)</a></li>
<li class="chapter" data-level="4.2.2" data-path="SESandETS.html"><a href="SESandETS.html#etsmnn"><i class="fa fa-check"></i><b>4.2.2</b> ETS(M,N,N)</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="ETSExamples.html"><a href="ETSExamples.html"><i class="fa fa-check"></i><b>4.3</b> Several examples of exponential smoothing methods and ETS</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="ETSExamples.html"><a href="ETSExamples.html#ETSAAN"><i class="fa fa-check"></i><b>4.3.1</b> ETS(A,A,N)</a></li>
<li class="chapter" data-level="4.3.2" data-path="ETSExamples.html"><a href="ETSExamples.html#ETSAAdN"><i class="fa fa-check"></i><b>4.3.2</b> ETS(A,Ad,N)</a></li>
<li class="chapter" data-level="4.3.3" data-path="ETSExamples.html"><a href="ETSExamples.html#etsaam"><i class="fa fa-check"></i><b>4.3.3</b> ETS(A,A,M)</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="ets-assumptions-estimation-and-selection.html"><a href="ets-assumptions-estimation-and-selection.html"><i class="fa fa-check"></i><b>4.4</b> ETS assumptions, estimation and selection</a></li>
<li class="chapter" data-level="4.5" data-path="state-space-form-of-ets.html"><a href="state-space-form-of-ets.html"><i class="fa fa-check"></i><b>4.5</b> State space form of ETS</a></li>
<li class="chapter" data-level="4.6" data-path="ETSParametersBounds.html"><a href="ETSParametersBounds.html"><i class="fa fa-check"></i><b>4.6</b> Parameters bounds</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="ADAMETSIntroduction.html"><a href="ADAMETSIntroduction.html"><i class="fa fa-check"></i><b>5</b> Pure additive ADAM ETS</a>
<ul>
<li class="chapter" data-level="5.1" data-path="ADAMETSPureAdditive.html"><a href="ADAMETSPureAdditive.html"><i class="fa fa-check"></i><b>5.1</b> Model formulation</a></li>
<li class="chapter" data-level="5.2" data-path="adamETSPureAdditiveRecursive.html"><a href="adamETSPureAdditiveRecursive.html"><i class="fa fa-check"></i><b>5.2</b> Recursive relation</a></li>
<li class="chapter" data-level="5.3" data-path="pureAdditiveExpectationAndVariance.html"><a href="pureAdditiveExpectationAndVariance.html"><i class="fa fa-check"></i><b>5.3</b> Conditional expectation and variance</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="pureAdditiveExpectationAndVariance.html"><a href="pureAdditiveExpectationAndVariance.html#example-with-etsann"><i class="fa fa-check"></i><b>5.3.1</b> Example with ETS(A,N,N)</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="stabilityConditionAdditiveError.html"><a href="stabilityConditionAdditiveError.html"><i class="fa fa-check"></i><b>5.4</b> Stability and forecastability conditions</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="stabilityConditionAdditiveError.html"><a href="stabilityConditionAdditiveError.html#example-with-etsann-1"><i class="fa fa-check"></i><b>5.4.1</b> Example with ETS(A,N,N)</a></li>
<li class="chapter" data-level="5.4.2" data-path="stabilityConditionAdditiveError.html"><a href="stabilityConditionAdditiveError.html#comming-back-to-the-general-case"><i class="fa fa-check"></i><b>5.4.2</b> Comming back to the general case</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="ADAMETSAdditiveDistributions.html"><a href="ADAMETSAdditiveDistributions.html"><i class="fa fa-check"></i><b>5.5</b> Distributional assumptions in pure additive ETS</a></li>
<li class="chapter" data-level="5.6" data-path="ADAMETSPureAdditiveExamples.html"><a href="ADAMETSPureAdditiveExamples.html"><i class="fa fa-check"></i><b>5.6</b> Examples of application</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="ADAMETSPureAdditiveExamples.html"><a href="ADAMETSPureAdditiveExamples.html#non-seasonal-data"><i class="fa fa-check"></i><b>5.6.1</b> Non-seasonal data</a></li>
<li class="chapter" data-level="5.6.2" data-path="ADAMETSPureAdditiveExamples.html"><a href="ADAMETSPureAdditiveExamples.html#ADAMETSPureAdditiveExamplesETSAAA"><i class="fa fa-check"></i><b>5.6.2</b> Seasonal data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="ADAMETSPureMultiplicative.html"><a href="ADAMETSPureMultiplicative.html"><i class="fa fa-check"></i><b>6</b> Pure multiplicative ADAM ETS</a>
<ul>
<li class="chapter" data-level="6.1" data-path="adamETSPuremultiplicativeRecursive.html"><a href="adamETSPuremultiplicativeRecursive.html"><i class="fa fa-check"></i><b>6.1</b> Recursive relation</a></li>
<li class="chapter" data-level="6.2" data-path="pureMultiplicativeExpectationAndVariance.html"><a href="pureMultiplicativeExpectationAndVariance.html"><i class="fa fa-check"></i><b>6.2</b> The problem with moments in pure multiplicative ETS</a></li>
<li class="chapter" data-level="6.3" data-path="stabilityConditionMultiplicativeError.html"><a href="stabilityConditionMultiplicativeError.html"><i class="fa fa-check"></i><b>6.3</b> Smoothing parameters bounds</a></li>
<li class="chapter" data-level="6.4" data-path="ADAMETSMultiplicativeDistributions.html"><a href="ADAMETSMultiplicativeDistributions.html"><i class="fa fa-check"></i><b>6.4</b> Distributional assumptions in pure multiplicative ETS</a></li>
<li class="chapter" data-level="6.5" data-path="ADAMETSMultiplicativeExamples.html"><a href="ADAMETSMultiplicativeExamples.html"><i class="fa fa-check"></i><b>6.5</b> Examples of application</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="ADAMETSMultiplicativeExamples.html"><a href="ADAMETSMultiplicativeExamples.html#non-seasonal-data-1"><i class="fa fa-check"></i><b>6.5.1</b> Non-seasonal data</a></li>
<li class="chapter" data-level="6.5.2" data-path="ADAMETSMultiplicativeExamples.html"><a href="ADAMETSMultiplicativeExamples.html#seasonal-data"><i class="fa fa-check"></i><b>6.5.2</b> Seasonal data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="ADAMETSMixedModels.html"><a href="ADAMETSMixedModels.html"><i class="fa fa-check"></i><b>7</b> Further ADAM ETS topics</a>
<ul>
<li class="chapter" data-level="7.1" data-path="ADAMETSMixedModelsGroup3.html"><a href="ADAMETSMixedModelsGroup3.html"><i class="fa fa-check"></i><b>7.1</b> Mixed models with non-multiplicative trend</a></li>
<li class="chapter" data-level="7.2" data-path="ADAMETSMixedModelsGroup4.html"><a href="ADAMETSMixedModelsGroup4.html"><i class="fa fa-check"></i><b>7.2</b> Mixed models with multiplicative trend</a></li>
<li class="chapter" data-level="7.3" data-path="ADAMETSSeasonalNormalisation.html"><a href="ADAMETSSeasonalNormalisation.html"><i class="fa fa-check"></i><b>7.3</b> Normalisation of seasonal indices in ETS models</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="ARIMA.html"><a href="ARIMA.html"><i class="fa fa-check"></i><b>8</b> Conventional ARIMA</a>
<ul>
<li class="chapter" data-level="8.1" data-path="ARIMAIntro.html"><a href="ARIMAIntro.html"><i class="fa fa-check"></i><b>8.1</b> Introduction to ARIMA</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="ARIMAIntro.html"><a href="ARIMAIntro.html#AR"><i class="fa fa-check"></i><b>8.1.1</b> AR(p)</a></li>
<li class="chapter" data-level="8.1.2" data-path="ARIMAIntro.html"><a href="ARIMAIntro.html#MA"><i class="fa fa-check"></i><b>8.1.2</b> MA(q)</a></li>
<li class="chapter" data-level="8.1.3" data-path="ARIMAIntro.html"><a href="ARIMAIntro.html#ARMA"><i class="fa fa-check"></i><b>8.1.3</b> ARMA(p,q)</a></li>
<li class="chapter" data-level="8.1.4" data-path="ARIMAIntro.html"><a href="ARIMAIntro.html#ARMAConstant"><i class="fa fa-check"></i><b>8.1.4</b> ARMA with constant</a></li>
<li class="chapter" data-level="8.1.5" data-path="ARIMAIntro.html"><a href="ARIMAIntro.html#Differences"><i class="fa fa-check"></i><b>8.1.5</b> I(d)</a></li>
<li class="chapter" data-level="8.1.6" data-path="ARIMAIntro.html"><a href="ARIMAIntro.html#arimapdq"><i class="fa fa-check"></i><b>8.1.6</b> ARIMA(p,d,q)</a></li>
<li class="chapter" data-level="8.1.7" data-path="ARIMAIntro.html"><a href="ARIMAIntro.html#ARIMABounds"><i class="fa fa-check"></i><b>8.1.7</b> Parameters bounds</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="seasonal-arima.html"><a href="seasonal-arima.html"><i class="fa fa-check"></i><b>8.2</b> Seasonal ARIMA</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="seasonal-arima.html"><a href="seasonal-arima.html#single-seasonal-arima"><i class="fa fa-check"></i><b>8.2.1</b> Single seasonal ARIMA</a></li>
<li class="chapter" data-level="8.2.2" data-path="seasonal-arima.html"><a href="seasonal-arima.html#sarima-with-constant"><i class="fa fa-check"></i><b>8.2.2</b> SARIMA with constant</a></li>
<li class="chapter" data-level="8.2.3" data-path="seasonal-arima.html"><a href="seasonal-arima.html#MSARIMA"><i class="fa fa-check"></i><b>8.2.3</b> Multiple seasonal ARIMA</a></li>
<li class="chapter" data-level="8.2.4" data-path="seasonal-arima.html"><a href="seasonal-arima.html#MSARIMABounds"><i class="fa fa-check"></i><b>8.2.4</b> Parameters bounds for MSARIMA</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="BJApproach.html"><a href="BJApproach.html"><i class="fa fa-check"></i><b>8.3</b> Box-Jenkins approach</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="BJApproach.html"><a href="BJApproach.html#identifying-stationarity"><i class="fa fa-check"></i><b>8.3.1</b> Identifying stationarity</a></li>
<li class="chapter" data-level="8.3.2" data-path="BJApproach.html"><a href="BJApproach.html#ACF"><i class="fa fa-check"></i><b>8.3.2</b> Autocorrelation function (ACF)</a></li>
<li class="chapter" data-level="8.3.3" data-path="BJApproach.html"><a href="BJApproach.html#PACF"><i class="fa fa-check"></i><b>8.3.3</b> Partial autocorrelation function (PACF)</a></li>
<li class="chapter" data-level="8.3.4" data-path="BJApproach.html"><a href="BJApproach.html#BJApproachSummary"><i class="fa fa-check"></i><b>8.3.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="ARIMAandETS.html"><a href="ARIMAandETS.html"><i class="fa fa-check"></i><b>8.4</b> ARIMA and ETS</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="ARIMAandETS.html"><a href="ARIMAandETS.html#ARIMAETS011"><i class="fa fa-check"></i><b>8.4.1</b> ARIMA(0,1,1) and ETS(A,N,N)</a></li>
<li class="chapter" data-level="8.4.2" data-path="ARIMAandETS.html"><a href="ARIMAandETS.html#ARIMAETS022"><i class="fa fa-check"></i><b>8.4.2</b> ARIMA(0,2,2) and ETS(A,A,N)</a></li>
<li class="chapter" data-level="8.4.3" data-path="ARIMAandETS.html"><a href="ARIMAandETS.html#ARIMAETS112"><i class="fa fa-check"></i><b>8.4.3</b> ARIMA(1,1,2) and ETS(A,Ad,N)</a></li>
<li class="chapter" data-level="8.4.4" data-path="ARIMAandETS.html"><a href="ARIMAandETS.html#arima-and-other-ets-models"><i class="fa fa-check"></i><b>8.4.4</b> ARIMA and other ETS models</a></li>
<li class="chapter" data-level="8.4.5" data-path="ARIMAandETS.html"><a href="ARIMAandETS.html#ets-arima"><i class="fa fa-check"></i><b>8.4.5</b> ETS + ARIMA</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="ARIMAExampleInR.html"><a href="ARIMAExampleInR.html"><i class="fa fa-check"></i><b>8.5</b> Examples of application</a>
<ul>
<li class="chapter" data-level="8.5.1" data-path="ARIMAExampleInR.html"><a href="ARIMAExampleInR.html#non-seasonal-data-2"><i class="fa fa-check"></i><b>8.5.1</b> Non-seasonal data</a></li>
<li class="chapter" data-level="8.5.2" data-path="ARIMAExampleInR.html"><a href="ARIMAExampleInR.html#ARIMAExampleInRSeasonal"><i class="fa fa-check"></i><b>8.5.2</b> Seasonal data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="ADAMARIMA.html"><a href="ADAMARIMA.html"><i class="fa fa-check"></i><b>9</b> ADAM ARIMA</a>
<ul>
<li class="chapter" data-level="9.1" data-path="StateSpaceARIMA.html"><a href="StateSpaceARIMA.html"><i class="fa fa-check"></i><b>9.1</b> State space ARIMA</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="StateSpaceARIMA.html"><a href="StateSpaceARIMA.html#StateSpaceARIMAAdditive"><i class="fa fa-check"></i><b>9.1.1</b> Additive ARIMA</a></li>
<li class="chapter" data-level="9.1.2" data-path="StateSpaceARIMA.html"><a href="StateSpaceARIMA.html#an-example"><i class="fa fa-check"></i><b>9.1.2</b> An example</a></li>
<li class="chapter" data-level="9.1.3" data-path="StateSpaceARIMA.html"><a href="StateSpaceARIMA.html#state-space-arima-with-constant"><i class="fa fa-check"></i><b>9.1.3</b> State space ARIMA with constant</a></li>
<li class="chapter" data-level="9.1.4" data-path="StateSpaceARIMA.html"><a href="StateSpaceARIMA.html#ADAMARIMAPureMultiplicative"><i class="fa fa-check"></i><b>9.1.4</b> Multiplicative ARIMA</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="ADAMARIMARecursive.html"><a href="ADAMARIMARecursive.html"><i class="fa fa-check"></i><b>9.2</b> Recursive relation</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="ADAMARIMARecursive.html"><a href="ADAMARIMARecursive.html#moments-of-adam-arima"><i class="fa fa-check"></i><b>9.2.1</b> Moments of ADAM ARIMA</a></li>
<li class="chapter" data-level="9.2.2" data-path="ADAMARIMARecursive.html"><a href="ADAMARIMARecursive.html#parameters-bounds"><i class="fa fa-check"></i><b>9.2.2</b> Parameters bounds</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="ADAMARIMADistributions.html"><a href="ADAMARIMADistributions.html"><i class="fa fa-check"></i><b>9.3</b> Distributional assumptions of ADAM ARIMA</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="ADAMARIMADistributions.html"><a href="ADAMARIMADistributions.html#conditional-distributions"><i class="fa fa-check"></i><b>9.3.1</b> Conditional distributions</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="ets-arima-1.html"><a href="ets-arima-1.html"><i class="fa fa-check"></i><b>9.4</b> ETS + ARIMA</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="ets-arima-1.html"><a href="ets-arima-1.html#pure-additive-models"><i class="fa fa-check"></i><b>9.4.1</b> Pure additive models</a></li>
<li class="chapter" data-level="9.4.2" data-path="ets-arima-1.html"><a href="ets-arima-1.html#pure-multiplicative-models"><i class="fa fa-check"></i><b>9.4.2</b> Pure multiplicative models</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="ADAMARIMAExamples.html"><a href="ADAMARIMAExamples.html"><i class="fa fa-check"></i><b>9.5</b> Examples of application</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="ADAMX.html"><a href="ADAMX.html"><i class="fa fa-check"></i><b>10</b> Explanatory variables in ADAM</a>
<ul>
<li class="chapter" data-level="10.1" data-path="adamx-model-formulation.html"><a href="adamx-model-formulation.html"><i class="fa fa-check"></i><b>10.1</b> ADAMX: Model formulation</a></li>
<li class="chapter" data-level="10.2" data-path="ADAMXConventionalConditionalMoments.html"><a href="ADAMXConventionalConditionalMoments.html"><i class="fa fa-check"></i><b>10.2</b> Conditional expectation and variance of ADAMX</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="ADAMXConventionalConditionalMoments.html"><a href="ADAMXConventionalConditionalMoments.html#the-adamx-with-known-explanatory-variables"><i class="fa fa-check"></i><b>10.2.1</b> The ADAMX with known explanatory variables</a></li>
<li class="chapter" data-level="10.2.2" data-path="ADAMXConventionalConditionalMoments.html"><a href="ADAMXConventionalConditionalMoments.html#adamx-with-random-explanatory-variables"><i class="fa fa-check"></i><b>10.2.2</b> ADAMX with random explanatory variables</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="ADAMXDynamic.html"><a href="ADAMXDynamic.html"><i class="fa fa-check"></i><b>10.3</b> Dynamic X in ADAMX</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="ADAMXDynamic.html"><a href="ADAMXDynamic.html#conditional-moments-of-dynamic-adamx"><i class="fa fa-check"></i><b>10.3.1</b> Conditional moments of dynamic ADAMX</a></li>
<li class="chapter" data-level="10.3.2" data-path="ADAMXDynamic.html"><a href="ADAMXDynamic.html#known-explanatory-variables"><i class="fa fa-check"></i><b>10.3.2</b> Known explanatory variables</a></li>
<li class="chapter" data-level="10.3.3" data-path="ADAMXDynamic.html"><a href="ADAMXDynamic.html#random-explanatory-variables"><i class="fa fa-check"></i><b>10.3.3</b> Random explanatory variables</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="stability-and-forecastability-conditions-of-adamx.html"><a href="stability-and-forecastability-conditions-of-adamx.html"><i class="fa fa-check"></i><b>10.4</b> Stability and forecastability conditions of ADAMX</a></li>
<li class="chapter" data-level="10.5" data-path="ETSXDynamicCategories.html"><a href="ETSXDynamicCategories.html"><i class="fa fa-check"></i><b>10.5</b> Dealing with categorical variables in ADAMX</a></li>
<li class="chapter" data-level="10.6" data-path="ETSXRExample.html"><a href="ETSXRExample.html"><i class="fa fa-check"></i><b>10.6</b> Examples of application</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="ADAMETSEstimation.html"><a href="ADAMETSEstimation.html"><i class="fa fa-check"></i><b>11</b> Estimation of ADAM models</a>
<ul>
<li class="chapter" data-level="11.1" data-path="ADAMETSEstimationLikelihood.html"><a href="ADAMETSEstimationLikelihood.html"><i class="fa fa-check"></i><b>11.1</b> Maximum Likelihood Estimation</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="ADAMETSEstimationLikelihood.html"><a href="ADAMETSEstimationLikelihood.html#an-example-in-r"><i class="fa fa-check"></i><b>11.1.1</b> An example in R</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="non-mle-based-loss-functions.html"><a href="non-mle-based-loss-functions.html"><i class="fa fa-check"></i><b>11.2</b> Non MLE-based loss functions</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="non-mle-based-loss-functions.html"><a href="non-mle-based-loss-functions.html#MSEandMAEEstimators"><i class="fa fa-check"></i><b>11.2.1</b> MSE and MAE</a></li>
<li class="chapter" data-level="11.2.2" data-path="non-mle-based-loss-functions.html"><a href="non-mle-based-loss-functions.html#ham"><i class="fa fa-check"></i><b>11.2.2</b> HAM</a></li>
<li class="chapter" data-level="11.2.3" data-path="non-mle-based-loss-functions.html"><a href="non-mle-based-loss-functions.html#lasso-and-ridge"><i class="fa fa-check"></i><b>11.2.3</b> LASSO and RIDGE</a></li>
<li class="chapter" data-level="11.2.4" data-path="non-mle-based-loss-functions.html"><a href="non-mle-based-loss-functions.html#custom-losses"><i class="fa fa-check"></i><b>11.2.4</b> Custom losses</a></li>
<li class="chapter" data-level="11.2.5" data-path="non-mle-based-loss-functions.html"><a href="non-mle-based-loss-functions.html#examples-in-r"><i class="fa fa-check"></i><b>11.2.5</b> Examples in R</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="multistepLosses.html"><a href="multistepLosses.html"><i class="fa fa-check"></i><b>11.3</b> Multistep losses</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="multistepLosses.html"><a href="multistepLosses.html#mathrmmse_h---mse-for-h-steps-ahead"><i class="fa fa-check"></i><b>11.3.1</b> <span class="math inline">\(\mathrm{MSE}_h\)</span> - MSE for h steps ahead</a></li>
<li class="chapter" data-level="11.3.2" data-path="multistepLosses.html"><a href="multistepLosses.html#multistepLossesTMSE"><i class="fa fa-check"></i><b>11.3.2</b> TMSE - Trace MSE</a></li>
<li class="chapter" data-level="11.3.3" data-path="multistepLosses.html"><a href="multistepLosses.html#multistepLossesGTMSE"><i class="fa fa-check"></i><b>11.3.3</b> GTMSE - Geometric Trace MSE</a></li>
<li class="chapter" data-level="11.3.4" data-path="multistepLosses.html"><a href="multistepLosses.html#msce---mean-squared-cumulative-error"><i class="fa fa-check"></i><b>11.3.4</b> MSCE - Mean Squared Cumulative Error</a></li>
<li class="chapter" data-level="11.3.5" data-path="multistepLosses.html"><a href="multistepLosses.html#gpl---general-predictive-likelihood"><i class="fa fa-check"></i><b>11.3.5</b> GPL - General Predictive Likelihood</a></li>
<li class="chapter" data-level="11.3.6" data-path="multistepLosses.html"><a href="multistepLosses.html#other-multistep-estimators"><i class="fa fa-check"></i><b>11.3.6</b> Other multistep estimators</a></li>
<li class="chapter" data-level="11.3.7" data-path="multistepLosses.html"><a href="multistepLosses.html#an-example-in-r-1"><i class="fa fa-check"></i><b>11.3.7</b> An example in R</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="ADAMInitialisation.html"><a href="ADAMInitialisation.html"><i class="fa fa-check"></i><b>11.4</b> Initialisation of ADAM</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="ADAMInitialisation.html"><a href="ADAMInitialisation.html#ADAMInitialisationOptAndBack"><i class="fa fa-check"></i><b>11.4.1</b> Optimisation vs backcasting</a></li>
<li class="chapter" data-level="11.4.2" data-path="ADAMInitialisation.html"><a href="ADAMInitialisation.html#pre-initialisation-of-adam-parameters"><i class="fa fa-check"></i><b>11.4.2</b> Pre-initialisation of ADAM parameters</a></li>
<li class="chapter" data-level="11.4.3" data-path="ADAMInitialisation.html"><a href="ADAMInitialisation.html#pre-initialisation-of-adam-states-ets"><i class="fa fa-check"></i><b>11.4.3</b> Pre-initialisation of ADAM states, ETS</a></li>
<li class="chapter" data-level="11.4.4" data-path="ADAMInitialisation.html"><a href="ADAMInitialisation.html#pre-initialisation-of-adam-states-arima"><i class="fa fa-check"></i><b>11.4.4</b> Pre-initialisation of ADAM states, ARIMA</a></li>
<li class="chapter" data-level="11.4.5" data-path="ADAMInitialisation.html"><a href="ADAMInitialisation.html#pre-initialisation-of-adam-states-regressors-and-constant"><i class="fa fa-check"></i><b>11.4.5</b> Pre-initialisation of ADAM states, Regressors and constant</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="multiple-frequencies-in-adam-ets.html"><a href="multiple-frequencies-in-adam-ets.html"><i class="fa fa-check"></i><b>12</b> Multiple frequencies in ADAM ETS</a>
<ul>
<li class="chapter" data-level="12.1" data-path="estimation-of-multiple-seasonal-model.html"><a href="estimation-of-multiple-seasonal-model.html"><i class="fa fa-check"></i><b>12.1</b> Estimation of multiple seasonal model</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="estimation-of-multiple-seasonal-model.html"><a href="estimation-of-multiple-seasonal-model.html#adam-ets-issues"><i class="fa fa-check"></i><b>12.1.1</b> ADAM ETS issues</a></li>
<li class="chapter" data-level="12.1.2" data-path="estimation-of-multiple-seasonal-model.html"><a href="estimation-of-multiple-seasonal-model.html#adam-arima-issues"><i class="fa fa-check"></i><b>12.1.2</b> ADAM ARIMA issues</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="ETSXMultipleSeasonality.html"><a href="ETSXMultipleSeasonality.html"><i class="fa fa-check"></i><b>12.2</b> Using explanatory variables for multiple seasonalities</a></li>
<li class="chapter" data-level="12.3" data-path="MultipleFrequenciesDSTandLeap.html"><a href="MultipleFrequenciesDSTandLeap.html"><i class="fa fa-check"></i><b>12.3</b> Dealing with daylight saving and leap years</a></li>
<li class="chapter" data-level="12.4" data-path="ADAMMultipleFrequenciesExamples.html"><a href="ADAMMultipleFrequenciesExamples.html"><i class="fa fa-check"></i><b>12.4</b> Examples of application</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="ADAMMultipleFrequenciesExamples.html"><a href="ADAMMultipleFrequenciesExamples.html#adam-ets"><i class="fa fa-check"></i><b>12.4.1</b> ADAM ETS</a></li>
<li class="chapter" data-level="12.4.2" data-path="ADAMMultipleFrequenciesExamples.html"><a href="ADAMMultipleFrequenciesExamples.html#adam-etsx"><i class="fa fa-check"></i><b>12.4.2</b> ADAM ETSX</a></li>
<li class="chapter" data-level="12.4.3" data-path="ADAMMultipleFrequenciesExamples.html"><a href="ADAMMultipleFrequenciesExamples.html#adam-arima"><i class="fa fa-check"></i><b>12.4.3</b> ADAM ARIMA</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="ADAMIntermittent.html"><a href="ADAMIntermittent.html"><i class="fa fa-check"></i><b>13</b> ADAM for Intermittent Demand</a>
<ul>
<li class="chapter" data-level="13.1" data-path="ADAMOccurrence.html"><a href="ADAMOccurrence.html"><i class="fa fa-check"></i><b>13.1</b> Occurrence part of the model</a>
<ul>
<li class="chapter" data-level="13.1.1" data-path="ADAMOccurrence.html"><a href="ADAMOccurrence.html#fixed-probability-model-oets_f"><i class="fa fa-check"></i><b>13.1.1</b> Fixed probability model, oETS<span class="math inline">\(_F\)</span></a></li>
<li class="chapter" data-level="13.1.2" data-path="ADAMOccurrence.html"><a href="ADAMOccurrence.html#oETSO"><i class="fa fa-check"></i><b>13.1.2</b> Odds ratio model, oETS<span class="math inline">\(_O\)</span></a></li>
<li class="chapter" data-level="13.1.3" data-path="ADAMOccurrence.html"><a href="ADAMOccurrence.html#inverse-odds-ratio-model-oets_i"><i class="fa fa-check"></i><b>13.1.3</b> Inverse odds ratio model, oETS<span class="math inline">\(_I\)</span></a></li>
<li class="chapter" data-level="13.1.4" data-path="ADAMOccurrence.html"><a href="ADAMOccurrence.html#oETSG"><i class="fa fa-check"></i><b>13.1.4</b> General oETS model, oETS<span class="math inline">\(_G\)</span></a></li>
<li class="chapter" data-level="13.1.5" data-path="ADAMOccurrence.html"><a href="ADAMOccurrence.html#direct-probability-model-oets_d"><i class="fa fa-check"></i><b>13.1.5</b> Direct probability model, oETS<span class="math inline">\(_D\)</span></a></li>
<li class="chapter" data-level="13.1.6" data-path="ADAMOccurrence.html"><a href="ADAMOccurrence.html#oETSModelSelection"><i class="fa fa-check"></i><b>13.1.6</b> Model selection in oETS</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="ADAMDemandSizes.html"><a href="ADAMDemandSizes.html"><i class="fa fa-check"></i><b>13.2</b> Demand sizes part of the model</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="ADAMDemandSizes.html"><a href="ADAMDemandSizes.html#additive-vs-multiplicative-ets-for-demand-sizes"><i class="fa fa-check"></i><b>13.2.1</b> Additive vs multiplicative ETS for demand sizes</a></li>
<li class="chapter" data-level="13.2.2" data-path="ADAMDemandSizes.html"><a href="ADAMDemandSizes.html#using-arima-for-demand-sizes"><i class="fa fa-check"></i><b>13.2.2</b> Using ARIMA for demand sizes</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="ADAMIntermittentFull.html"><a href="ADAMIntermittentFull.html"><i class="fa fa-check"></i><b>13.3</b> The full ADAM model</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="ADAMIntermittentFull.html"><a href="ADAMIntermittentFull.html#iETSMLE"><i class="fa fa-check"></i><b>13.3.1</b> Maximum Likelihood Estimation</a></li>
<li class="chapter" data-level="13.3.2" data-path="ADAMIntermittentFull.html"><a href="ADAMIntermittentFull.html#conditional-expectation-and-variance"><i class="fa fa-check"></i><b>13.3.2</b> Conditional expectation and variance</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="examples-of-application-1.html"><a href="examples-of-application-1.html"><i class="fa fa-check"></i><b>13.4</b> Examples of application</a></li>
<li class="chapter" data-level="13.5" data-path="intermittent-demand-challenges.html"><a href="intermittent-demand-challenges.html"><i class="fa fa-check"></i><b>13.5</b> Intermittent demand challenges</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="diagnostics.html"><a href="diagnostics.html"><i class="fa fa-check"></i><b>14</b> Model diagnostics</a>
<ul>
<li class="chapter" data-level="14.1" data-path="diagnosticsOmitted.html"><a href="diagnosticsOmitted.html"><i class="fa fa-check"></i><b>14.1</b> Model specification: Omitted variables</a></li>
<li class="chapter" data-level="14.2" data-path="model-specification-redundant-variables.html"><a href="model-specification-redundant-variables.html"><i class="fa fa-check"></i><b>14.2</b> Model specification: Redundant variables</a></li>
<li class="chapter" data-level="14.3" data-path="diagnosticsTransformations.html"><a href="diagnosticsTransformations.html"><i class="fa fa-check"></i><b>14.3</b> Model specification: Transformations</a></li>
<li class="chapter" data-level="14.4" data-path="diagnosticsOutliers.html"><a href="diagnosticsOutliers.html"><i class="fa fa-check"></i><b>14.4</b> Model specification: Outliers</a>
<ul>
<li class="chapter" data-level="14.4.1" data-path="diagnosticsOutliers.html"><a href="diagnosticsOutliers.html#outliers-detection"><i class="fa fa-check"></i><b>14.4.1</b> Outliers detection</a></li>
<li class="chapter" data-level="14.4.2" data-path="diagnosticsOutliers.html"><a href="diagnosticsOutliers.html#dealing-with-outliers"><i class="fa fa-check"></i><b>14.4.2</b> Dealing with outliers</a></li>
<li class="chapter" data-level="14.4.3" data-path="diagnosticsOutliers.html"><a href="diagnosticsOutliers.html#an-automatic-mechanism"><i class="fa fa-check"></i><b>14.4.3</b> An automatic mechanism</a></li>
<li class="chapter" data-level="14.4.4" data-path="diagnosticsOutliers.html"><a href="diagnosticsOutliers.html#final-remarks"><i class="fa fa-check"></i><b>14.4.4</b> Final remarks</a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="diagnosticsResidualsIIDAuto.html"><a href="diagnosticsResidualsIIDAuto.html"><i class="fa fa-check"></i><b>14.5</b> Residuals are i.i.d.: autocorrelation</a></li>
<li class="chapter" data-level="14.6" data-path="diagnosticsResidualsIIDHetero.html"><a href="diagnosticsResidualsIIDHetero.html"><i class="fa fa-check"></i><b>14.6</b> Residuals are i.i.d.: heteroscedasticity</a>
<ul>
<li class="chapter" data-level="14.6.1" data-path="diagnosticsResidualsIIDHetero.html"><a href="diagnosticsResidualsIIDHetero.html#detecting-heteroscedasticity"><i class="fa fa-check"></i><b>14.6.1</b> Detecting heteroscedasticity</a></li>
</ul></li>
<li class="chapter" data-level="14.7" data-path="residuals-are-i-i-d-zero-expectation.html"><a href="residuals-are-i-i-d-zero-expectation.html"><i class="fa fa-check"></i><b>14.7</b> Residuals are i.i.d.: zero expectation</a></li>
<li class="chapter" data-level="14.8" data-path="residuals-are-i-i-d-distributional-assumptions.html"><a href="residuals-are-i-i-d-distributional-assumptions.html"><i class="fa fa-check"></i><b>14.8</b> Residuals are i.i.d.: distributional assumptions</a></li>
<li class="chapter" data-level="14.9" data-path="multicollinearity.html"><a href="multicollinearity.html"><i class="fa fa-check"></i><b>14.9</b> Multicollinearity</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="ADAMSelection.html"><a href="ADAMSelection.html"><i class="fa fa-check"></i><b>15</b> Model selection and combinations in ADAM</a>
<ul>
<li class="chapter" data-level="15.1" data-path="ETSSelection.html"><a href="ETSSelection.html"><i class="fa fa-check"></i><b>15.1</b> ADAM ETS components selection</a></li>
<li class="chapter" data-level="15.2" data-path="ARIMASelection.html"><a href="ARIMASelection.html"><i class="fa fa-check"></i><b>15.2</b> ADAM ARIMA order selection</a></li>
<li class="chapter" data-level="15.3" data-path="ETSXSelection.html"><a href="ETSXSelection.html"><i class="fa fa-check"></i><b>15.3</b> Explanatory variables selection</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Forecasting and Analytics with ADAM</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div class = rmdreview>
This book is in <b><a href="open.html#open">Open Review</a></b>. I want your feedback to make the book better for you and other readers. To add your annotation, <span style="background-color: #3297FD; color: white">select some text</span> and then click the <i class="h-icon-annotate"></i> on the pop-up menu. To see the annotations of others, click the button in the upper right hand corner of the page <i class="fa fa-arrow-circle-right  fa-rotate-315" aria-hidden="true"></i>
</div>
<div id="ADAMETSEstimationLikelihood" class="section level2" number="11.1">
<h2><span class="header-section-number">11.1</span> Maximum Likelihood Estimation</h2>
<p>The <a href="#likelihoodApproach">maximum likelihood estimation</a> (MLE) of ADAM model relies on the distributional assumptions of each specific model and might differ from one to another. There are several options for the <code>distribution</code> supported by <code>adam()</code> function in smooth package, here we briefly discuss how the estimation is done for each one of them. We start with the additive error models, for which the assumptions, log-likelihoods and MLE of scales are provided in Table <a href="ADAMETSEstimationLikelihood.html#tab:additiveErrorLikelihoods">11.1</a>. The likelihoods are derived based on the probability density functions, discussed in <a href="#distributions">the chapter 2</a>, by taking logarithms of the product of pdfs for all in sample observations. For example, this is what we get for the normal distribution (we already <a href="#likelihoodApproachMaths">had a simple example</a> with this earlier in the book):
<span class="math display" id="eq:ETSADAMNormalDistributionExample01">\[\begin{equation}
  \begin{aligned}
    \mathcal{L}(\boldsymbol{\theta}, {\sigma}^2 | \mathbf{y}) = &amp; \prod_{t=1}^T \left(\frac{1}{\sqrt{2 \pi \sigma^2}} \exp \left( -\frac{\left(y_t - \mu_t \right)^2}{2 \sigma^2} \right)\right) \\
    \mathcal{L}(\boldsymbol{\theta}, {\sigma}^2 | \mathbf{y}) = &amp; \frac{1}{\left(\sqrt{2 \pi \sigma^2}\right)^T} \exp \left( \sum_{t=1}^T -\frac{\epsilon_t^2}{2 \sigma^2} \right) \\
    \ell(\boldsymbol{\theta}, {\sigma}^2 | \mathbf{y}) = &amp; \log \mathcal{L}(\boldsymbol{\theta}, {\sigma}^2 | \mathbf{y}) \\
    \ell(\boldsymbol{\theta}, {\sigma}^2 | \mathbf{y}) = &amp; -\frac{T}{2} \log(2 \pi \sigma^2) -\frac{1}{2} \sum_{t=1}^T \frac{\epsilon_t^2}{\sigma^2}
  \end{aligned},
  \tag{11.3}
\end{equation}\]</span>
where <span class="math inline">\(\mathbf{y}\)</span> is the vector of all in-sample actual values. As for the scale, it is obtained by solving the equation after taking derivative of the log-likelihood <a href="ADAMETSEstimationLikelihood.html#eq:ETSADAMNormalDistributionExample01">(11.3)</a> with respect to <span class="math inline">\(\sigma^2\)</span> and setting it equal to zero. We don’t discuss the concentrated log-likelihoods (obtained after inserting the estimated scale in the respective log-likelihood function), because they are not useful in understanding how the model is estimated, but knowing how to calculate scale helps, because it simplifies the model estimation process.</p>
<table class="table" style="font-size: 12px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:additiveErrorLikelihoods">Table 11.1: </span>Likelihood approach for additive error models
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
Assumption
</th>
<th style="text-align:left;">
log-likelihood
</th>
<th style="text-align:left;">
MLE of scale
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
<strong>Normal</strong>
</td>
<td style="text-align:left;">
<span class="math inline">\(\epsilon_t \sim \mathcal{N}(0, \sigma^2)\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(-\frac{T}{2} \log(2 \pi \sigma^2) -\frac{1}{2} \sum_{t=1}^T \frac{\epsilon_t^2}{\sigma^2}\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\hat{\sigma}^2 = \frac{1}{T} \sum_{t=1}^T e_t^2\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
<strong>Laplace</strong>
</td>
<td style="text-align:left;">
<span class="math inline">\(\epsilon_t \sim \mathcal{Laplace}(0, s)\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(-T \log(2 s) -\sum_{t=1}^T \frac{|\epsilon_t|}{s}\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\hat{s} = \frac{1}{T} \sum_{t=1}^T |e_t|\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
<strong>S</strong>
</td>
<td style="text-align:left;">
<span class="math inline">\(\epsilon_t \sim \mathcal{S}(0, s)\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(-T \log(4 s^2) -\sum_{t=1}^T \frac{\sqrt{|\epsilon_t|}}{s}\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\hat{s} = \frac{1}{2T} \sum_{t=1}^T \sqrt{|e_t|}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
<strong>Generalised Normal</strong>
</td>
<td style="text-align:left;">
<span class="math inline">\(\epsilon_t \sim \mathcal{GN}(0, s, \beta)\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\begin{split} &amp;T\log\beta -T \log(2 s \Gamma\left(\beta^{-1}\right)) -\\  &amp;\sum_{t=1}^T \frac{\left|\epsilon_t\right|^\beta}{s}\end{split}\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\hat{s} = \sqrt[^{\beta}]{\frac{\beta}{T} \sum_{t=1}^T\left| e_t \right|^{\beta}}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
<strong>Asymmetric Laplace</strong>
</td>
<td style="text-align:left;">
<span class="math inline">\(\epsilon_t \sim \mathcal{ALaplace}(0, s, \alpha)\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\begin{split} &amp;T\log\left(\alpha(1-\alpha)\right) -T \log(s) -\\  &amp;\sum_{t=1}^T \frac{\epsilon_t (\alpha - I(\epsilon_t \leq 0))}{s} \end{split}\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\hat{s} = \frac{1}{T} \sum_{t=1}^T e_t(\alpha -I(e_t \leq 0))\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
<strong>Inverse Gaussian</strong>
</td>
<td style="text-align:left;">
<span class="math inline">\(1+\frac{\epsilon_t}{\mu_{y,t}} \sim \mathcal{IG}(1, s)\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\begin{split} &amp;-\frac{T}{2} \log \left(2 \pi s \left(\frac{y_t}{\mu_{y,t}}\right)^3 \right) -\\  &amp;\frac{3}{2}\sum_{t=1}^T \log y_t -\frac{1}{2s} \sum_{t=1}^{T} \frac{\epsilon_t^2}{\mu_{y,t}y_t}\end{split}\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\hat{s} = \frac{1}{T} \sum_{t=1}^{T} \frac{e_t^2}{\hat{\mu}_{y,t} y_t}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
<strong>Gamma</strong>
</td>
<td style="text-align:left;">
<span class="math inline">\(1+\frac{\epsilon_t}{\mu_{y,t}} \sim \mathcal{\Gamma}(s^{-1}, s)\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\begin{split} &amp;-T \log \Gamma \left(s^{-1}\right) - \frac{T}{s} \log s + \\  &amp;\frac{1}{s} \sum_{t=1}^T \log \left(\frac{y_t/\mu_{y,t}}{ \exp(y_t/\mu_{y,t})}\right) - \sum_{t=1}^T \log y_t\end{split}\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\hat{s} = \frac{1}{T} \sum_{t=1}^T \left(\frac{e_t}{\mu_{y,t}}\right)^2\)</span> *
</td>
</tr>
<tr>
<td style="text-align:left;">
<strong>Log Normal</strong>
</td>
<td style="text-align:left;">
<span class="math inline">\(1+\frac{\epsilon_t}{\mu_{y,t}} \sim \mathrm{log}\mathcal{N}\left(-\frac{\sigma^2}{2}, \sigma^2\right)\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\begin{split} &amp;-\frac{T}{2} \log \left(2 \pi \sigma^2\right) -\\  &amp;\frac{1}{2\sigma^2} \sum_{t=1}^{T} \left(\log \left(\frac{y_t}{\mu_{y,t}}\right)+\frac{\sigma^2}{2}\right)^2 -\\  &amp;\sum_{t=1}^T \log y_t \end{split}\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\hat{\sigma}^2 = 2\left(1-\sqrt{ 1-\frac{1}{T} \sum_{t=1}^{T} \log^2\left(\frac{y_t}{\hat{\mu}_{y,t}}\right)}\right)\)</span>
</td>
</tr>
</tbody>
</table>
<p>(*) Note that the MLE of scale parameter for Gamma distribution (formulated in ADAM) does not exist. While there are no proofs for it, it seems that the maximum of the likelihood of Gamma distribution is achieved, when <span class="math inline">\(\hat{s} = \frac{1}{T} \sum_{t=1}^T \left(\frac{e_t}{\mu_{y,t}}\right)^2\)</span>, which corresponds to the estimate based on method of moments.</p>
<p>Other distributions can be used in ADAM ETS as well (for example, Logistic distribution or Student’s t), but we do not discuss them here. Note that for the additive error models <span class="math inline">\(y_t = \mu_{y,t}+\epsilon_t\)</span>, thus some formulae in Table <a href="ADAMETSEstimationLikelihood.html#tab:additiveErrorLikelihoods">11.1</a> are simplified. In all of the cases in <a href="ADAMETSEstimationLikelihood.html#tab:additiveErrorLikelihoods">11.1</a> the assumptions imply that the actual value follows the same distribution, but with a different location and / or scale. For example, for the Normal distribution we have:
<span class="math display" id="eq:ETSADAMNormalDistributionExample02">\[\begin{equation}
  \begin{aligned}
    &amp; \epsilon_t \sim \mathcal{N}(0, \sigma^2) \\
    &amp; \mathrm{or} \\
    &amp; y_t = \mu_{y,t}+\epsilon_t \sim \mathcal{N}(\mu_{y,t}, \sigma^2)
  \end{aligned}.
  \tag{11.4}
\end{equation}\]</span></p>
<p>When it comes to the multiplicative error models, the likelihoods become slightly different. For example, when we assume that <span class="math inline">\(\epsilon_t \sim \mathcal{N}(0, \sigma^2)\)</span> in the multiplicative error model, this implies that:
<span class="math display" id="eq:ETSADAMNormalDistributionExample03">\[\begin{equation}
    y_t = \mu_{y,t}(1+\epsilon_t) \sim \mathcal{N}(\mu_{y,t}, \mu_{y,t}^2 \sigma^2) .
  \tag{11.5}
\end{equation}\]</span>
As a result the log-likelihoods would have the <span class="math inline">\(\mu_{y,t}\)</span> part in the formulae. Similar logic is applicable to <span class="math inline">\(\mathcal{Laplace}\)</span>, <span class="math inline">\(\mathcal{S}\)</span>, <span class="math inline">\(\mathcal{GN}\)</span> and <span class="math inline">\(\mathcal{ALaplace}\)</span> distributions. From the practical point of view, these assumptions imply that the scale (and variance) of the distribution of <span class="math inline">\(y_t\)</span> changes together with the level of the series. When it comes to the <span class="math inline">\(\mathcal{IG}\)</span> and log<span class="math inline">\(\mathcal{N}\)</span>, the assumptions are imposed on the <span class="math inline">\(1+\epsilon_t\)</span> part of the model, the respective likelihoods do not involve the expectation <span class="math inline">\(\mu_{y,t}\)</span>, but the formulation still implies that the variance of the data increases together with the increase of the level of data.</p>
<p>All the likelihoods for the multiplicative error models are summarised in Table <a href="ADAMETSEstimationLikelihood.html#tab:multiplicativeErrorLikelihoods">11.2</a>.</p>
<table class="table" style="font-size: 12px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:multiplicativeErrorLikelihoods">Table 11.2: </span>Likelihood approach for multiplicative error models
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
Assumption
</th>
<th style="text-align:left;">
log-likelihood
</th>
<th style="text-align:left;">
MLE of scale
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
<strong>Normal</strong>
</td>
<td style="text-align:left;">
<span class="math inline">\(\epsilon_t \sim \mathcal{N}(0, \sigma^2)\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\begin{split} &amp;-\frac{T}{2} \log(2 \pi \sigma^2) -\frac{1}{2} \sum_{t=1}^T \frac{\epsilon_t^2}{\sigma^2} -\\  &amp;\sum_{t=1}^T \log |\mu_{y,t}|\end{split}\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\hat{\sigma}^2 = \frac{1}{T} \sum_{t=1}^T e_t^2\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
<strong>Laplace</strong>
</td>
<td style="text-align:left;">
<span class="math inline">\(\epsilon_t \sim \mathcal{Laplace}(0, s)\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\begin{split} &amp;-T \log(2 s) -\sum_{t=1}^T \frac{|\epsilon_t|}{s} -\\  &amp;\sum_{t=1}^T \log \mu_{y,t}\end{split}\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\hat{s} = \frac{1}{T} \sum_{t=1}^T |e_t|\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
<strong>S</strong>
</td>
<td style="text-align:left;">
<span class="math inline">\(\epsilon_t \sim \mathcal{S}(0, s)\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\begin{split} &amp;-T \log(4 s^2) -\sum_{t=1}^T \frac{\sqrt{|\epsilon_t|}}{s} -\\  &amp;\sum_{t=1}^T \log \mu_{y,t}\end{split}\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\hat{s} = \frac{1}{2T} \sum_{t=1}^T \sqrt{|e_t|}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
<strong>Generalised Normal</strong>
</td>
<td style="text-align:left;">
<span class="math inline">\(\epsilon_t \sim \mathcal{GN}(0, s, \beta)\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\begin{split} &amp;T\log\beta -T \log(2 s \Gamma\left(\beta^{-1}\right)) -\\  &amp;\sum_{t=1}^T \frac{\left|\epsilon_t\right|^\beta}{s} -\sum_{t=1}^T \log \mu_{y,t}\end{split}\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\hat{s} = \sqrt[^{\beta}]{\frac{\beta}{T} \sum_{t=1}^T\left| e_t \right|^{\beta}}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
<strong>Asymmetric Laplace</strong>
</td>
<td style="text-align:left;">
<span class="math inline">\(\epsilon_t \sim \mathcal{ALaplace}(0, s, \alpha)\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\begin{split} &amp;T\log\left(\alpha(1-\alpha)\right) -T \log(s) -\\  &amp;\sum_{t=1}^T \frac{\epsilon_t (\alpha - I(\epsilon_t \leq 0))}{s} -\sum_{t=1}^T \log \mu_{y,t}\end{split}\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\hat{s} = \frac{1}{T} \sum_{t=1}^T e_t(\alpha -I(e_t \leq 0))\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
<strong>Inverse Gaussian</strong>
</td>
<td style="text-align:left;">
<span class="math inline">\(1+\epsilon_t \sim \mathcal{IG}(1, s)\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\begin{split} &amp;-\frac{T}{2} \log \left(2 \pi s \left(1+\epsilon_{t}\right)^3 \right) -\\  &amp;\frac{3}{2}\sum_{t=1}^T \log y_t -\frac{1}{2s} \sum_{t=1}^{T} \frac{\epsilon_t^2}{1+\epsilon_t}\end{split}\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\hat{s} = \frac{1}{T} \sum_{t=1}^{T} \frac{e_t^2}{1+e_t}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
<strong>Gamma</strong>
</td>
<td style="text-align:left;">
<span class="math inline">\(1+\epsilon_t \sim \mathcal{\Gamma}(s^{-1}, s)\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\begin{split} &amp;-T \log \Gamma \left(s^{-1}\right) - \frac{T}{s} \log s + \\  &amp;\frac{1}{s} \sum_{t=1}^T \log \left(\frac{1+\epsilon_t}{\exp(1+\epsilon_t)}\right) - \sum_{t=1}^T \log y_t\end{split}\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\hat{s} = \frac{1}{T} \sum_{t=1}^T e_t^2\)</span> *
</td>
</tr>
<tr>
<td style="text-align:left;">
<strong>Log Normal</strong>
</td>
<td style="text-align:left;">
<span class="math inline">\(1+\epsilon_t \sim \mathrm{log}\mathcal{N}\left(-\frac{\sigma^2}{2}, \sigma^2\right)\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\begin{split} &amp;-\frac{T}{2} \log \left(2 \pi \sigma^2\right) -\\  &amp;\frac{1}{2\sigma^2} \sum_{t=1}^{T} \left(\log \left(1+\epsilon_t\right)+\frac{\sigma^2}{2}\right)^2 -\\  &amp;\sum_{t=1}^T \log y_t \end{split}\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\hat{\sigma}^2 = 2\left(1-\sqrt{ 1-\frac{1}{T} \sum_{t=1}^{T} \log^2\left(1+e_t\right)}\right)\)</span>
</td>
</tr>
</tbody>
</table>
<p>When it comes to practicalities, in <code>adam()</code> function, in the optimiser, on each iteration, after fitting the model the scales from Tables <a href="ADAMETSEstimationLikelihood.html#tab:additiveErrorLikelihoods">11.1</a> and <a href="ADAMETSEstimationLikelihood.html#tab:multiplicativeErrorLikelihoods">11.2</a> are calculated and then used in the log-likelihoods based on the respective distribution functions, for additive error models:</p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(\mathcal{N}\)</span> - <code>dnorm(x=actuals, mean=fitted, sd=scale,  log=TRUE)</code> from <code>stats</code> package;</li>
<li><span class="math inline">\(\mathcal{Laplace}\)</span> - <code>dlaplace(q=actuals, mu=fitted, scale=scale, log=TRUE)</code> from <code>greybox</code> package;</li>
<li><span class="math inline">\(\mathcal{S}\)</span> - <code>ds(q=actuals, mu=fitted, scale=scale, log=TRUE)</code> from <code>greybox</code> package;</li>
<li><span class="math inline">\(\mathcal{GN}\)</span> - <code>dgnorm(x=actuals, mu=fitted, alpha=scale, beta=beta, log=TRUE)</code> implemented in <code>greybox</code> package based on <code>gnorm</code> package (the version on CRAN is outdated);</li>
<li><span class="math inline">\(\mathcal{ALaplace}\)</span> - <code>dalaplace(q=actuals, mu=fitted, scale=scale,  alpha=alpha, log=TRUE)</code> from <code>greybox</code> package;</li>
<li><span class="math inline">\(\mathcal{IG}\)</span> - <code>dinvgauss(x=actuals, mean=fitted, dispersion=scale/fitted, log=TRUE)</code> from <code>statmod</code> package;</li>
<li>log<span class="math inline">\(\mathcal{N}\)</span> - <code>dlnorm(x=actuals, meanlog=fitted-scale^2/2, sdlog=scale, log=TRUE)</code> from <code>stats</code> package;</li>
<li><span class="math inline">\(\mathcal{\Gamma}\)</span> - <code>dgamma(x=actuals, shape=1/scale, scale=scale*fitted, log=TRUE)</code> from <code>stats</code> package.</li>
</ol>
<p>and for multiplicative error models:</p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(\mathcal{N}\)</span> - <code>dnorm(x=actuals, mean=fitted, sd=scale*fitted,  log=TRUE)</code>;</li>
<li><span class="math inline">\(\mathcal{Laplace}\)</span> - <code>dlaplace(q=actuals, mu=fitted, scale=scale*fitted, log=TRUE)</code>;</li>
<li><span class="math inline">\(\mathcal{S}\)</span> - <code>ds(q=actuals, mu=fitted, scale=scale*sqrt(fitted), log=TRUE)</code>;</li>
<li><span class="math inline">\(\mathcal{GN}\)</span> - <code>dgnorm(x=actuals, mu=fitted, alpha=scale*fitted^beta, beta=beta, log=TRUE)</code>;</li>
<li><span class="math inline">\(\mathcal{ALaplace}\)</span> - <code>dalaplace(q=actuals, mu=fitted, scale=scale*fitted,  alpha=alpha, log=TRUE)</code>;</li>
<li><span class="math inline">\(\mathcal{IG}\)</span> - <code>dinvgauss(x=actuals, mean=fitted, dispersion=scale/fitted, log=TRUE)</code>;</li>
<li>log<span class="math inline">\(\mathcal{N}\)</span> - <code>dlnorm(x=actuals, meanlog=fitted-scale^2/2, sdlog=scale, log=TRUE)</code>;</li>
<li><span class="math inline">\(\mathcal{\Gamma}\)</span> - <code>dgamma(x=actuals, shape=1/scale, scale=scale*fitted, log=TRUE)</code>.</li>
</ol>
<p>Note that in cases of <span class="math inline">\(\mathcal{GN}\)</span> and <span class="math inline">\(\mathcal{ALaplace}\)</span>, additional parameters (namely <span class="math inline">\(\beta\)</span> and <span class="math inline">\(\alpha\)</span>) are needed. If the user does not provide them, then they are estimated together with the other parameters via the maximisation of respective likelihoods.</p>
<p>The MLE of parameters of ADAM ETS models makes them comparable with each other irrespective of the types of components and distributional assumptions. As a result, model selection based on information criteria can be done using <code>auto.adam()</code> function from <code>smooth</code>, which will select the most appropriate ETS model with the most suitable distribution.</p>
<div id="an-example-in-r" class="section level3" number="11.1.1">
<h3><span class="header-section-number">11.1.1</span> An example in R</h3>
<p><code>adam()</code> function in smooth package has the parameter <code>distribution</code>, which allows selecting between several options discussed in this chapter, based on the respective density functions (see the list above with <code>dnorm()</code> etc). Here is a brief example in R with ADAM ETS(M,A,M) applied to the <code>AirPassengers</code> data with several distributions:</p>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="ADAMETSEstimationLikelihood.html#cb127-1" aria-hidden="true" tabindex="-1"></a>adamModel <span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="st">&quot;list&quot;</span>,<span class="dv">5</span>)</span>
<span id="cb127-2"><a href="ADAMETSEstimationLikelihood.html#cb127-2" aria-hidden="true" tabindex="-1"></a>adamModel[[<span class="dv">1</span>]] <span class="ot">&lt;-</span> <span class="fu">adam</span>(AirPassengers, <span class="st">&quot;MAM&quot;</span>, <span class="at">distribution=</span><span class="st">&quot;dnorm&quot;</span>, <span class="at">h=</span><span class="dv">12</span>, <span class="at">holdout=</span><span class="cn">TRUE</span>)</span>
<span id="cb127-3"><a href="ADAMETSEstimationLikelihood.html#cb127-3" aria-hidden="true" tabindex="-1"></a>adamModel[[<span class="dv">2</span>]] <span class="ot">&lt;-</span> <span class="fu">adam</span>(AirPassengers, <span class="st">&quot;MAM&quot;</span>, <span class="at">distribution=</span><span class="st">&quot;dlaplace&quot;</span>, <span class="at">h=</span><span class="dv">12</span>, <span class="at">holdout=</span><span class="cn">TRUE</span>)</span>
<span id="cb127-4"><a href="ADAMETSEstimationLikelihood.html#cb127-4" aria-hidden="true" tabindex="-1"></a>adamModel[[<span class="dv">3</span>]] <span class="ot">&lt;-</span> <span class="fu">adam</span>(AirPassengers, <span class="st">&quot;MAM&quot;</span>, <span class="at">distribution=</span><span class="st">&quot;dgnorm&quot;</span>, <span class="at">h=</span><span class="dv">12</span>, <span class="at">holdout=</span><span class="cn">TRUE</span>)</span>
<span id="cb127-5"><a href="ADAMETSEstimationLikelihood.html#cb127-5" aria-hidden="true" tabindex="-1"></a>adamModel[[<span class="dv">4</span>]] <span class="ot">&lt;-</span> <span class="fu">adam</span>(AirPassengers, <span class="st">&quot;MAM&quot;</span>, <span class="at">distribution=</span><span class="st">&quot;dinvgauss&quot;</span>, <span class="at">h=</span><span class="dv">12</span>, <span class="at">holdout=</span><span class="cn">TRUE</span>)</span>
<span id="cb127-6"><a href="ADAMETSEstimationLikelihood.html#cb127-6" aria-hidden="true" tabindex="-1"></a>adamModel[[<span class="dv">5</span>]] <span class="ot">&lt;-</span> <span class="fu">adam</span>(AirPassengers, <span class="st">&quot;MAM&quot;</span>, <span class="at">distribution=</span><span class="st">&quot;dgamma&quot;</span>, <span class="at">h=</span><span class="dv">12</span>, <span class="at">holdout=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<p>In this case, the function will select the most appropriate ETS model for each distribution. We can see what was selected in each case and compare the models using information criteria:</p>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="ADAMETSEstimationLikelihood.html#cb128-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setNames</span>(<span class="fu">sapply</span>(adamModel, AICc), <span class="fu">c</span>(<span class="st">&quot;dnorm&quot;</span>,<span class="st">&quot;dlaplace&quot;</span>,<span class="st">&quot;dgnorm&quot;</span>,<span class="st">&quot;dinvgauss&quot;</span>,<span class="st">&quot;dgamma&quot;</span>))</span></code></pre></div>
<pre><code>##     dnorm  dlaplace    dgnorm dinvgauss    dgamma 
##  972.5669  975.2124  977.9902  973.7769  973.1933</code></pre>
<p>We could compare the performance of models in detail, but, for the purposes of this demonstration, it should suffice to say that among the four models considered above, based on the AICc value, the model with the Normal distribution should be preferred. This process of fit and selection can be automated using <code>auto.adam()</code> model, which accepts the vector of distributions to test and by default would consider <code>distribution=c("dnorm", "dlaplace", "ds", "dgnorm", "dlnorm", "dinvgauss", "dgamma")</code>:</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="ADAMETSEstimationLikelihood.html#cb130-1" aria-hidden="true" tabindex="-1"></a>adamModel <span class="ot">&lt;-</span> <span class="fu">auto.adam</span>(AirPassengers, <span class="st">&quot;MAM&quot;</span>, <span class="at">h=</span><span class="dv">12</span>, <span class="at">holdout=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<p>This command should return the ADAM ETS(M,A,M) model with the most appropriate distribution, selected based on the AICc.</p>
</div>
</div>

            </section>

          </div>
        </div>
      </div>
<a href="ADAMETSEstimation.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="non-mle-based-loss-functions.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/config-i1/adam/tree/master/Chapters//11-ADAM-Estimation.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["adam.pdf", "adam.epub"],
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
