<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>3.4 Regression with categorical variables | Forecasting and Analytics with ADAM</title>
  <meta name="description" content="This textbook explains how to do time series analysis and forecasting using Augmented Dynamic Adaptive Model, implemented in smooth package for R." />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="3.4 Regression with categorical variables | Forecasting and Analytics with ADAM" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This textbook explains how to do time series analysis and forecasting using Augmented Dynamic Adaptive Model, implemented in smooth package for R." />
  <meta name="github-repo" content="config-i1/adam" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="3.4 Regression with categorical variables | Forecasting and Analytics with ADAM" />
  
  <meta name="twitter:description" content="This textbook explains how to do time series analysis and forecasting using Augmented Dynamic Adaptive Model, implemented in smooth package for R." />
  

<meta name="author" content="Ivan Svetunkov" />


<meta name="date" content="2021-07-05" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="regression-uncertainty.html"/>
<link rel="next" href="variables-transformations.html"/>
<script src="libs/header-attrs-2.9/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>
<script async defer src="https://hypothes.is/embed.js"></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-XH37Z8VYP8"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-XH37Z8VYP8');
</script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Forecasting and Analytics with ADAM</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#license"><i class="fa fa-check"></i>License</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#what-is-adam"><i class="fa fa-check"></i>What is ADAM?</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#acknowledgments"><i class="fa fa-check"></i>Acknowledgments</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="modelsMethods.html"><a href="modelsMethods.html"><i class="fa fa-check"></i><b>1.1</b> Models, methods et al. </a></li>
<li class="chapter" data-level="1.2" data-path="scales.html"><a href="scales.html"><i class="fa fa-check"></i><b>1.2</b> Scales of information</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="scales.html"><a href="scales.html#nominal-scale"><i class="fa fa-check"></i><b>1.2.1</b> Nominal scale</a></li>
<li class="chapter" data-level="1.2.2" data-path="scales.html"><a href="scales.html#ordinal-scale"><i class="fa fa-check"></i><b>1.2.2</b> Ordinal scale</a></li>
<li class="chapter" data-level="1.2.3" data-path="scales.html"><a href="scales.html#interval-scale"><i class="fa fa-check"></i><b>1.2.3</b> Interval scale</a></li>
<li class="chapter" data-level="1.2.4" data-path="scales.html"><a href="scales.html#ratio-scale"><i class="fa fa-check"></i><b>1.2.4</b> Ratio scale</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="statistics.html"><a href="statistics.html"><i class="fa fa-check"></i><b>2</b> Introduction to statistics</a>
<ul>
<li class="chapter" data-level="2.1" data-path="dataAnalysis.html"><a href="dataAnalysis.html"><i class="fa fa-check"></i><b>2.1</b> Preliminary data analysis</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="dataAnalysis.html"><a href="dataAnalysis.html#numerical-analysis"><i class="fa fa-check"></i><b>2.1.1</b> Numerical analysis</a></li>
<li class="chapter" data-level="2.1.2" data-path="dataAnalysis.html"><a href="dataAnalysis.html#dataAnalysisGraphical"><i class="fa fa-check"></i><b>2.1.2</b> Graphical analysis</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="LLNandCLT.html"><a href="LLNandCLT.html"><i class="fa fa-check"></i><b>2.2</b> Law of Large Numbers and Central Limit Theorem</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="LLNandCLT.html"><a href="LLNandCLT.html#LLN"><i class="fa fa-check"></i><b>2.2.1</b> Law of Large Numbers</a></li>
<li class="chapter" data-level="2.2.2" data-path="LLNandCLT.html"><a href="LLNandCLT.html#CLT"><i class="fa fa-check"></i><b>2.2.2</b> Central Limit Theorem</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="estimatesProperties.html"><a href="estimatesProperties.html"><i class="fa fa-check"></i><b>2.3</b> Properties of estimators</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="estimatesProperties.html"><a href="estimatesProperties.html#estimatesPropertiesBias"><i class="fa fa-check"></i><b>2.3.1</b> Bias</a></li>
<li class="chapter" data-level="2.3.2" data-path="estimatesProperties.html"><a href="estimatesProperties.html#estimatesPropertiesEfficiency"><i class="fa fa-check"></i><b>2.3.2</b> Efficiency</a></li>
<li class="chapter" data-level="2.3.3" data-path="estimatesProperties.html"><a href="estimatesProperties.html#estimatesPropertiesConsistency"><i class="fa fa-check"></i><b>2.3.3</b> Consistency</a></li>
<li class="chapter" data-level="2.3.4" data-path="estimatesProperties.html"><a href="estimatesProperties.html#asymptoticNormality"><i class="fa fa-check"></i><b>2.3.4</b> Asymptotic normality</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="confidenceIntervals.html"><a href="confidenceIntervals.html"><i class="fa fa-check"></i><b>2.4</b> Confidence and prediction intervals</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="confidenceIntervals.html"><a href="confidenceIntervals.html#confidence-interval"><i class="fa fa-check"></i><b>2.4.1</b> Confidence interval</a></li>
<li class="chapter" data-level="2.4.2" data-path="confidenceIntervals.html"><a href="confidenceIntervals.html#prediction-interval"><i class="fa fa-check"></i><b>2.4.2</b> Prediction interval</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="hypothesisTesting.html"><a href="hypothesisTesting.html"><i class="fa fa-check"></i><b>2.5</b> Hypothesis testing</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="hypothesisTesting.html"><a href="hypothesisTesting.html#hypothesisTestingMistakes"><i class="fa fa-check"></i><b>2.5.1</b> Common mistakes related to hypothesis testing</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="correlations.html"><a href="correlations.html"><i class="fa fa-check"></i><b>2.6</b> Correlation and measures of association</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="correlations.html"><a href="correlations.html#nominal-scale-1"><i class="fa fa-check"></i><b>2.6.1</b> Nominal scale</a></li>
<li class="chapter" data-level="2.6.2" data-path="correlations.html"><a href="correlations.html#ordinal-scale-1"><i class="fa fa-check"></i><b>2.6.2</b> Ordinal scale</a></li>
<li class="chapter" data-level="2.6.3" data-path="correlations.html"><a href="correlations.html#correlationCoefficient"><i class="fa fa-check"></i><b>2.6.3</b> Numerical scale</a></li>
<li class="chapter" data-level="2.6.4" data-path="correlations.html"><a href="correlations.html#correlationsMixed"><i class="fa fa-check"></i><b>2.6.4</b> Mixed scales</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="distributions.html"><a href="distributions.html"><i class="fa fa-check"></i><b>2.7</b> Theory of distributions</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="distributions.html"><a href="distributions.html#distributionsNormal"><i class="fa fa-check"></i><b>2.7.1</b> Normal distribution</a></li>
<li class="chapter" data-level="2.7.2" data-path="distributions.html"><a href="distributions.html#distributionsLaplace"><i class="fa fa-check"></i><b>2.7.2</b> Laplace distribution</a></li>
<li class="chapter" data-level="2.7.3" data-path="distributions.html"><a href="distributions.html#s-distribution"><i class="fa fa-check"></i><b>2.7.3</b> S distribution</a></li>
<li class="chapter" data-level="2.7.4" data-path="distributions.html"><a href="distributions.html#distributionsGeneralisedNormal"><i class="fa fa-check"></i><b>2.7.4</b> Generalised Normal distribution</a></li>
<li class="chapter" data-level="2.7.5" data-path="distributions.html"><a href="distributions.html#distributionsALaplace"><i class="fa fa-check"></i><b>2.7.5</b> Asymmetric Laplace distribution</a></li>
<li class="chapter" data-level="2.7.6" data-path="distributions.html"><a href="distributions.html#log-normal-log-laplace-log-s-and-log-gn-distributions"><i class="fa fa-check"></i><b>2.7.6</b> Log Normal, Log Laplace, Log S and Log GN distributions</a></li>
<li class="chapter" data-level="2.7.7" data-path="distributions.html"><a href="distributions.html#IGDistribution"><i class="fa fa-check"></i><b>2.7.7</b> Inverse Gaussian distribution</a></li>
<li class="chapter" data-level="2.7.8" data-path="distributions.html"><a href="distributions.html#GammaDistribution"><i class="fa fa-check"></i><b>2.7.8</b> Gamma distribution</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>3</b> Regression analysis</a>
<ul>
<li class="chapter" data-level="3.1" data-path="simpleLinearRegression.html"><a href="simpleLinearRegression.html"><i class="fa fa-check"></i><b>3.1</b> Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="simpleLinearRegression.html"><a href="simpleLinearRegression.html#OLS"><i class="fa fa-check"></i><b>3.1.1</b> Ordinary Least Squares (OLS)</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="linearRegression.html"><a href="linearRegression.html"><i class="fa fa-check"></i><b>3.2</b> Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="linearRegression.html"><a href="linearRegression.html#ols-estimation"><i class="fa fa-check"></i><b>3.2.1</b> OLS estimation</a></li>
<li class="chapter" data-level="3.2.2" data-path="linearRegression.html"><a href="linearRegression.html#linearRegressionQualityOfFit"><i class="fa fa-check"></i><b>3.2.2</b> Quality of a fit</a></li>
<li class="chapter" data-level="3.2.3" data-path="linearRegression.html"><a href="linearRegression.html#interpretation-of-parameters"><i class="fa fa-check"></i><b>3.2.3</b> Interpretation of parameters</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="regression-uncertainty.html"><a href="regression-uncertainty.html"><i class="fa fa-check"></i><b>3.3</b> Regression uncertainty</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="regression-uncertainty.html"><a href="regression-uncertainty.html#confidence-intervals"><i class="fa fa-check"></i><b>3.3.1</b> Confidence intervals</a></li>
<li class="chapter" data-level="3.3.2" data-path="regression-uncertainty.html"><a href="regression-uncertainty.html#hypothesis-testing"><i class="fa fa-check"></i><b>3.3.2</b> Hypothesis testing</a></li>
<li class="chapter" data-level="3.3.3" data-path="regression-uncertainty.html"><a href="regression-uncertainty.html#regression-model-uncertainty"><i class="fa fa-check"></i><b>3.3.3</b> Regression model uncertainty</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="dummyVariables.html"><a href="dummyVariables.html"><i class="fa fa-check"></i><b>3.4</b> Regression with categorical variables</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="dummyVariables.html"><a href="dummyVariables.html#categorical-variables-for-the-slope"><i class="fa fa-check"></i><b>3.4.1</b> Categorical variables for the slope</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="variables-transformations.html"><a href="variables-transformations.html"><i class="fa fa-check"></i><b>3.5</b> Variables transformations</a></li>
<li class="chapter" data-level="3.6" data-path="assumptions.html"><a href="assumptions.html"><i class="fa fa-check"></i><b>3.6</b> Typical assumptions of statistical models</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="assumptions.html"><a href="assumptions.html#assumptionsCorrectModel"><i class="fa fa-check"></i><b>3.6.1</b> Model is correctly specified</a></li>
<li class="chapter" data-level="3.6.2" data-path="assumptions.html"><a href="assumptions.html#assumptionsResidualsAreIID"><i class="fa fa-check"></i><b>3.6.2</b> Residuals are i.i.d.</a></li>
<li class="chapter" data-level="3.6.3" data-path="assumptions.html"><a href="assumptions.html#assumptionsXreg"><i class="fa fa-check"></i><b>3.6.3</b> The explanatory variables are not correlated with anything but the response variable</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="likelihoodApproach.html"><a href="likelihoodApproach.html"><i class="fa fa-check"></i><b>3.7</b> Likelihood Approach</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="likelihoodApproach.html"><a href="likelihoodApproach.html#an-example-in-r"><i class="fa fa-check"></i><b>3.7.1</b> An example in R</a></li>
<li class="chapter" data-level="3.7.2" data-path="likelihoodApproach.html"><a href="likelihoodApproach.html#likelihoodApproachMaths"><i class="fa fa-check"></i><b>3.7.2</b> Mathematical explanation</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="statisticsNumberOfParameters.html"><a href="statisticsNumberOfParameters.html"><i class="fa fa-check"></i><b>3.8</b> Calculating number of parameters in models</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="regressionModelBuilding.html"><a href="regressionModelBuilding.html"><i class="fa fa-check"></i><b>4</b> Regression model building</a>
<ul>
<li class="chapter" data-level="4.1" data-path="modelSelection.html"><a href="modelSelection.html"><i class="fa fa-check"></i><b>4.1</b> Model selection mechanism</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="modelSelection.html"><a href="modelSelection.html#informationCriteria"><i class="fa fa-check"></i><b>4.1.1</b> Information criteria idea</a></li>
<li class="chapter" data-level="4.1.2" data-path="modelSelection.html"><a href="modelSelection.html#informationCriteriaMistakes"><i class="fa fa-check"></i><b>4.1.2</b> Common confusions related to information criteria</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="forecastingProcess.html"><a href="forecastingProcess.html"><i class="fa fa-check"></i><b>5</b> Forecasts evaluation</a>
<ul>
<li class="chapter" data-level="5.1" data-path="errorMeasures.html"><a href="errorMeasures.html"><i class="fa fa-check"></i><b>5.1</b> Measuring accuracy of point forecasts</a></li>
<li class="chapter" data-level="5.2" data-path="uncertainty.html"><a href="uncertainty.html"><i class="fa fa-check"></i><b>5.2</b> Measuring uncertainty</a></li>
<li class="chapter" data-level="5.3" data-path="rollingOrigin.html"><a href="rollingOrigin.html"><i class="fa fa-check"></i><b>5.3</b> Rolling origin</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="rollingOrigin.html"><a href="rollingOrigin.html#principles-of-rolling-origin"><i class="fa fa-check"></i><b>5.3.1</b> Principles of Rolling origin</a></li>
<li class="chapter" data-level="5.3.2" data-path="rollingOrigin.html"><a href="rollingOrigin.html#rolling-origin-in-r"><i class="fa fa-check"></i><b>5.3.2</b> Rolling origin in R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="tsDecomposition.html"><a href="tsDecomposition.html"><i class="fa fa-check"></i><b>6</b> From time series components to ETS</a>
<ul>
<li class="chapter" data-level="6.1" data-path="tsComponents.html"><a href="tsComponents.html"><i class="fa fa-check"></i><b>6.1</b> Time series components</a></li>
<li class="chapter" data-level="6.2" data-path="ClassicalDecomposition.html"><a href="ClassicalDecomposition.html"><i class="fa fa-check"></i><b>6.2</b> Classical Seasonal Decomposition</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="ClassicalDecomposition.html"><a href="ClassicalDecomposition.html#how-to-do"><i class="fa fa-check"></i><b>6.2.1</b> How to do?</a></li>
<li class="chapter" data-level="6.2.2" data-path="ClassicalDecomposition.html"><a href="ClassicalDecomposition.html#a-couple-of-examples"><i class="fa fa-check"></i><b>6.2.2</b> A couple of examples</a></li>
<li class="chapter" data-level="6.2.3" data-path="ClassicalDecomposition.html"><a href="ClassicalDecomposition.html#other-techniques"><i class="fa fa-check"></i><b>6.2.3</b> Other techniques</a></li>
<li class="chapter" data-level="6.2.4" data-path="ClassicalDecomposition.html"><a href="ClassicalDecomposition.html#why-bother"><i class="fa fa-check"></i><b>6.2.4</b> “Why bother?”</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="ETSTaxonomy.html"><a href="ETSTaxonomy.html"><i class="fa fa-check"></i><b>6.3</b> ETS taxonomy</a></li>
<li class="chapter" data-level="6.4" data-path="ETSTaxonomyMaths.html"><a href="ETSTaxonomyMaths.html"><i class="fa fa-check"></i><b>6.4</b> Mathematical models in the ETS taxonomy</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="conventional-exponential-smoothing.html"><a href="conventional-exponential-smoothing.html"><i class="fa fa-check"></i><b>7</b> Conventional Exponential Smoothing</a>
<ul>
<li class="chapter" data-level="7.1" data-path="SES.html"><a href="SES.html"><i class="fa fa-check"></i><b>7.1</b> Simple Exponential Smoothing</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="SES.html"><a href="SES.html#examples-of-application"><i class="fa fa-check"></i><b>7.1.1</b> Examples of application</a></li>
<li class="chapter" data-level="7.1.2" data-path="SES.html"><a href="SES.html#whyExponential"><i class="fa fa-check"></i><b>7.1.2</b> Why “exponential?”</a></li>
<li class="chapter" data-level="7.1.3" data-path="SES.html"><a href="SES.html#error-correction-form-of-ses"><i class="fa fa-check"></i><b>7.1.3</b> Error correction form of SES</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="SESandETS.html"><a href="SESandETS.html"><i class="fa fa-check"></i><b>7.2</b> SES and ETS</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="SESandETS.html"><a href="SESandETS.html#etsann"><i class="fa fa-check"></i><b>7.2.1</b> ETS(A,N,N)</a></li>
<li class="chapter" data-level="7.2.2" data-path="SESandETS.html"><a href="SESandETS.html#etsmnn"><i class="fa fa-check"></i><b>7.2.2</b> ETS(M,N,N)</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="ETSExamples.html"><a href="ETSExamples.html"><i class="fa fa-check"></i><b>7.3</b> Several examples of exponential smoothing methods and ETS</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="ETSExamples.html"><a href="ETSExamples.html#ETSAAN"><i class="fa fa-check"></i><b>7.3.1</b> ETS(A,A,N)</a></li>
<li class="chapter" data-level="7.3.2" data-path="ETSExamples.html"><a href="ETSExamples.html#ETSAAdN"><i class="fa fa-check"></i><b>7.3.2</b> ETS(A,Ad,N)</a></li>
<li class="chapter" data-level="7.3.3" data-path="ETSExamples.html"><a href="ETSExamples.html#etsaam"><i class="fa fa-check"></i><b>7.3.3</b> ETS(A,A,M)</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="ets-assumptions-estimation-and-selection.html"><a href="ets-assumptions-estimation-and-selection.html"><i class="fa fa-check"></i><b>7.4</b> ETS assumptions, estimation and selection</a></li>
<li class="chapter" data-level="7.5" data-path="state-space-form-of-ets.html"><a href="state-space-form-of-ets.html"><i class="fa fa-check"></i><b>7.5</b> State space form of ETS</a></li>
<li class="chapter" data-level="7.6" data-path="ETSParametersBounds.html"><a href="ETSParametersBounds.html"><i class="fa fa-check"></i><b>7.6</b> Parameters bounds</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="ADAMETSIntroduction.html"><a href="ADAMETSIntroduction.html"><i class="fa fa-check"></i><b>8</b> Pure additive ADAM ETS</a>
<ul>
<li class="chapter" data-level="8.1" data-path="ADAMETSPureAdditive.html"><a href="ADAMETSPureAdditive.html"><i class="fa fa-check"></i><b>8.1</b> Model formulation</a></li>
<li class="chapter" data-level="8.2" data-path="adamETSPureAdditiveRecursive.html"><a href="adamETSPureAdditiveRecursive.html"><i class="fa fa-check"></i><b>8.2</b> Recursive relation</a></li>
<li class="chapter" data-level="8.3" data-path="pureAdditiveExpectationAndVariance.html"><a href="pureAdditiveExpectationAndVariance.html"><i class="fa fa-check"></i><b>8.3</b> Conditional expectation and variance</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="pureAdditiveExpectationAndVariance.html"><a href="pureAdditiveExpectationAndVariance.html#example-with-etsann"><i class="fa fa-check"></i><b>8.3.1</b> Example with ETS(A,N,N)</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="stabilityConditionAdditiveError.html"><a href="stabilityConditionAdditiveError.html"><i class="fa fa-check"></i><b>8.4</b> Stability and forecastability conditions</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="stabilityConditionAdditiveError.html"><a href="stabilityConditionAdditiveError.html#example-with-etsann-1"><i class="fa fa-check"></i><b>8.4.1</b> Example with ETS(A,N,N)</a></li>
<li class="chapter" data-level="8.4.2" data-path="stabilityConditionAdditiveError.html"><a href="stabilityConditionAdditiveError.html#comming-back-to-the-general-case"><i class="fa fa-check"></i><b>8.4.2</b> Comming back to the general case</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="ADAMETSAdditiveDistributions.html"><a href="ADAMETSAdditiveDistributions.html"><i class="fa fa-check"></i><b>8.5</b> Distributional assumptions in pure additive ETS</a></li>
<li class="chapter" data-level="8.6" data-path="ADAMETSPureAdditiveExamples.html"><a href="ADAMETSPureAdditiveExamples.html"><i class="fa fa-check"></i><b>8.6</b> Examples of application</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="ADAMETSPureAdditiveExamples.html"><a href="ADAMETSPureAdditiveExamples.html#non-seasonal-data"><i class="fa fa-check"></i><b>8.6.1</b> Non-seasonal data</a></li>
<li class="chapter" data-level="8.6.2" data-path="ADAMETSPureAdditiveExamples.html"><a href="ADAMETSPureAdditiveExamples.html#ADAMETSPureAdditiveExamplesETSAAA"><i class="fa fa-check"></i><b>8.6.2</b> Seasonal data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="ADAMETSPureMultiplicative.html"><a href="ADAMETSPureMultiplicative.html"><i class="fa fa-check"></i><b>9</b> Pure multiplicative ADAM ETS</a>
<ul>
<li class="chapter" data-level="9.1" data-path="adamETSPuremultiplicativeRecursive.html"><a href="adamETSPuremultiplicativeRecursive.html"><i class="fa fa-check"></i><b>9.1</b> Recursive relation</a></li>
<li class="chapter" data-level="9.2" data-path="pureMultiplicativeExpectationAndVariance.html"><a href="pureMultiplicativeExpectationAndVariance.html"><i class="fa fa-check"></i><b>9.2</b> The problem with moments in pure multiplicative ETS</a></li>
<li class="chapter" data-level="9.3" data-path="stabilityConditionMultiplicativeError.html"><a href="stabilityConditionMultiplicativeError.html"><i class="fa fa-check"></i><b>9.3</b> Smoothing parameters bounds</a></li>
<li class="chapter" data-level="9.4" data-path="ADAMETSMultiplicativeDistributions.html"><a href="ADAMETSMultiplicativeDistributions.html"><i class="fa fa-check"></i><b>9.4</b> Distributional assumptions in pure multiplicative ETS</a></li>
<li class="chapter" data-level="9.5" data-path="ADAMETSMultiplicativeExamples.html"><a href="ADAMETSMultiplicativeExamples.html"><i class="fa fa-check"></i><b>9.5</b> Examples of application</a>
<ul>
<li class="chapter" data-level="9.5.1" data-path="ADAMETSMultiplicativeExamples.html"><a href="ADAMETSMultiplicativeExamples.html#non-seasonal-data-1"><i class="fa fa-check"></i><b>9.5.1</b> Non-seasonal data</a></li>
<li class="chapter" data-level="9.5.2" data-path="ADAMETSMultiplicativeExamples.html"><a href="ADAMETSMultiplicativeExamples.html#seasonal-data"><i class="fa fa-check"></i><b>9.5.2</b> Seasonal data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="ADAMETSMixedModels.html"><a href="ADAMETSMixedModels.html"><i class="fa fa-check"></i><b>10</b> Further ADAM ETS topics</a>
<ul>
<li class="chapter" data-level="10.1" data-path="ADAMETSMixedModelsGroup3.html"><a href="ADAMETSMixedModelsGroup3.html"><i class="fa fa-check"></i><b>10.1</b> Mixed models with non-multiplicative trend</a></li>
<li class="chapter" data-level="10.2" data-path="ADAMETSMixedModelsGroup4.html"><a href="ADAMETSMixedModelsGroup4.html"><i class="fa fa-check"></i><b>10.2</b> Mixed models with multiplicative trend</a></li>
<li class="chapter" data-level="10.3" data-path="ADAMETSSeasonalNormalisation.html"><a href="ADAMETSSeasonalNormalisation.html"><i class="fa fa-check"></i><b>10.3</b> Normalisation of seasonal indices in ETS models</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="ARIMA.html"><a href="ARIMA.html"><i class="fa fa-check"></i><b>11</b> Conventional ARIMA</a>
<ul>
<li class="chapter" data-level="11.1" data-path="ARIMAIntro.html"><a href="ARIMAIntro.html"><i class="fa fa-check"></i><b>11.1</b> Introduction to ARIMA</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="ARIMAIntro.html"><a href="ARIMAIntro.html#AR"><i class="fa fa-check"></i><b>11.1.1</b> AR(p)</a></li>
<li class="chapter" data-level="11.1.2" data-path="ARIMAIntro.html"><a href="ARIMAIntro.html#MA"><i class="fa fa-check"></i><b>11.1.2</b> MA(q)</a></li>
<li class="chapter" data-level="11.1.3" data-path="ARIMAIntro.html"><a href="ARIMAIntro.html#ARMA"><i class="fa fa-check"></i><b>11.1.3</b> ARMA(p,q)</a></li>
<li class="chapter" data-level="11.1.4" data-path="ARIMAIntro.html"><a href="ARIMAIntro.html#ARMAConstant"><i class="fa fa-check"></i><b>11.1.4</b> ARMA with constant</a></li>
<li class="chapter" data-level="11.1.5" data-path="ARIMAIntro.html"><a href="ARIMAIntro.html#Differences"><i class="fa fa-check"></i><b>11.1.5</b> I(d)</a></li>
<li class="chapter" data-level="11.1.6" data-path="ARIMAIntro.html"><a href="ARIMAIntro.html#arimapdq"><i class="fa fa-check"></i><b>11.1.6</b> ARIMA(p,d,q)</a></li>
<li class="chapter" data-level="11.1.7" data-path="ARIMAIntro.html"><a href="ARIMAIntro.html#ARIMABounds"><i class="fa fa-check"></i><b>11.1.7</b> Parameters bounds</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="seasonal-arima.html"><a href="seasonal-arima.html"><i class="fa fa-check"></i><b>11.2</b> Seasonal ARIMA</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="seasonal-arima.html"><a href="seasonal-arima.html#single-seasonal-arima"><i class="fa fa-check"></i><b>11.2.1</b> Single seasonal ARIMA</a></li>
<li class="chapter" data-level="11.2.2" data-path="seasonal-arima.html"><a href="seasonal-arima.html#sarima-with-constant"><i class="fa fa-check"></i><b>11.2.2</b> SARIMA with constant</a></li>
<li class="chapter" data-level="11.2.3" data-path="seasonal-arima.html"><a href="seasonal-arima.html#MSARIMA"><i class="fa fa-check"></i><b>11.2.3</b> Multiple seasonal ARIMA</a></li>
<li class="chapter" data-level="11.2.4" data-path="seasonal-arima.html"><a href="seasonal-arima.html#MSARIMABounds"><i class="fa fa-check"></i><b>11.2.4</b> Parameters bounds for MSARIMA</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="BJApproach.html"><a href="BJApproach.html"><i class="fa fa-check"></i><b>11.3</b> Box-Jenkins approach</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="BJApproach.html"><a href="BJApproach.html#identifying-stationarity"><i class="fa fa-check"></i><b>11.3.1</b> Identifying stationarity</a></li>
<li class="chapter" data-level="11.3.2" data-path="BJApproach.html"><a href="BJApproach.html#ACF"><i class="fa fa-check"></i><b>11.3.2</b> Autocorrelation function (ACF)</a></li>
<li class="chapter" data-level="11.3.3" data-path="BJApproach.html"><a href="BJApproach.html#PACF"><i class="fa fa-check"></i><b>11.3.3</b> Partial autocorrelation function (PACF)</a></li>
<li class="chapter" data-level="11.3.4" data-path="BJApproach.html"><a href="BJApproach.html#BJApproachSummary"><i class="fa fa-check"></i><b>11.3.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="ARIMAandETS.html"><a href="ARIMAandETS.html"><i class="fa fa-check"></i><b>11.4</b> ARIMA and ETS</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="ARIMAandETS.html"><a href="ARIMAandETS.html#ARIMAETS011"><i class="fa fa-check"></i><b>11.4.1</b> ARIMA(0,1,1) and ETS(A,N,N)</a></li>
<li class="chapter" data-level="11.4.2" data-path="ARIMAandETS.html"><a href="ARIMAandETS.html#ARIMAETS022"><i class="fa fa-check"></i><b>11.4.2</b> ARIMA(0,2,2) and ETS(A,A,N)</a></li>
<li class="chapter" data-level="11.4.3" data-path="ARIMAandETS.html"><a href="ARIMAandETS.html#ARIMAETS112"><i class="fa fa-check"></i><b>11.4.3</b> ARIMA(1,1,2) and ETS(A,Ad,N)</a></li>
<li class="chapter" data-level="11.4.4" data-path="ARIMAandETS.html"><a href="ARIMAandETS.html#arima-and-other-ets-models"><i class="fa fa-check"></i><b>11.4.4</b> ARIMA and other ETS models</a></li>
<li class="chapter" data-level="11.4.5" data-path="ARIMAandETS.html"><a href="ARIMAandETS.html#ets-arima"><i class="fa fa-check"></i><b>11.4.5</b> ETS + ARIMA</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="ARIMAExampleInR.html"><a href="ARIMAExampleInR.html"><i class="fa fa-check"></i><b>11.5</b> Examples of application</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="ARIMAExampleInR.html"><a href="ARIMAExampleInR.html#non-seasonal-data-2"><i class="fa fa-check"></i><b>11.5.1</b> Non-seasonal data</a></li>
<li class="chapter" data-level="11.5.2" data-path="ARIMAExampleInR.html"><a href="ARIMAExampleInR.html#ARIMAExampleInRSeasonal"><i class="fa fa-check"></i><b>11.5.2</b> Seasonal data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="ADAMARIMA.html"><a href="ADAMARIMA.html"><i class="fa fa-check"></i><b>12</b> ADAM ARIMA</a>
<ul>
<li class="chapter" data-level="12.1" data-path="StateSpaceARIMA.html"><a href="StateSpaceARIMA.html"><i class="fa fa-check"></i><b>12.1</b> State space ARIMA</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="StateSpaceARIMA.html"><a href="StateSpaceARIMA.html#StateSpaceARIMAAdditive"><i class="fa fa-check"></i><b>12.1.1</b> Additive ARIMA</a></li>
<li class="chapter" data-level="12.1.2" data-path="StateSpaceARIMA.html"><a href="StateSpaceARIMA.html#an-example"><i class="fa fa-check"></i><b>12.1.2</b> An example</a></li>
<li class="chapter" data-level="12.1.3" data-path="StateSpaceARIMA.html"><a href="StateSpaceARIMA.html#state-space-arima-with-constant"><i class="fa fa-check"></i><b>12.1.3</b> State space ARIMA with constant</a></li>
<li class="chapter" data-level="12.1.4" data-path="StateSpaceARIMA.html"><a href="StateSpaceARIMA.html#ADAMARIMAPureMultiplicative"><i class="fa fa-check"></i><b>12.1.4</b> Multiplicative ARIMA</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="ADAMARIMARecursive.html"><a href="ADAMARIMARecursive.html"><i class="fa fa-check"></i><b>12.2</b> Recursive relation</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="ADAMARIMARecursive.html"><a href="ADAMARIMARecursive.html#moments-of-adam-arima"><i class="fa fa-check"></i><b>12.2.1</b> Moments of ADAM ARIMA</a></li>
<li class="chapter" data-level="12.2.2" data-path="ADAMARIMARecursive.html"><a href="ADAMARIMARecursive.html#parameters-bounds"><i class="fa fa-check"></i><b>12.2.2</b> Parameters bounds</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="ADAMARIMADistributions.html"><a href="ADAMARIMADistributions.html"><i class="fa fa-check"></i><b>12.3</b> Distributional assumptions of ADAM ARIMA</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="ADAMARIMADistributions.html"><a href="ADAMARIMADistributions.html#conditional-distributions"><i class="fa fa-check"></i><b>12.3.1</b> Conditional distributions</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="ets-arima-1.html"><a href="ets-arima-1.html"><i class="fa fa-check"></i><b>12.4</b> ETS + ARIMA</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="ets-arima-1.html"><a href="ets-arima-1.html#pure-additive-models"><i class="fa fa-check"></i><b>12.4.1</b> Pure additive models</a></li>
<li class="chapter" data-level="12.4.2" data-path="ets-arima-1.html"><a href="ets-arima-1.html#pure-multiplicative-models"><i class="fa fa-check"></i><b>12.4.2</b> Pure multiplicative models</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="ADAMARIMAExamples.html"><a href="ADAMARIMAExamples.html"><i class="fa fa-check"></i><b>12.5</b> Examples of application</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="ADAMX.html"><a href="ADAMX.html"><i class="fa fa-check"></i><b>13</b> Explanatory variables in ADAM</a>
<ul>
<li class="chapter" data-level="13.1" data-path="adamx-model-formulation.html"><a href="adamx-model-formulation.html"><i class="fa fa-check"></i><b>13.1</b> ADAMX: Model formulation</a></li>
<li class="chapter" data-level="13.2" data-path="ADAMXConventionalConditionalMoments.html"><a href="ADAMXConventionalConditionalMoments.html"><i class="fa fa-check"></i><b>13.2</b> Conditional expectation and variance of ADAMX</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="ADAMXConventionalConditionalMoments.html"><a href="ADAMXConventionalConditionalMoments.html#the-adamx-with-known-explanatory-variables"><i class="fa fa-check"></i><b>13.2.1</b> The ADAMX with known explanatory variables</a></li>
<li class="chapter" data-level="13.2.2" data-path="ADAMXConventionalConditionalMoments.html"><a href="ADAMXConventionalConditionalMoments.html#adamx-with-random-explanatory-variables"><i class="fa fa-check"></i><b>13.2.2</b> ADAMX with random explanatory variables</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="ADAMXDynamic.html"><a href="ADAMXDynamic.html"><i class="fa fa-check"></i><b>13.3</b> Dynamic X in ADAMX</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="ADAMXDynamic.html"><a href="ADAMXDynamic.html#conditional-moments-of-dynamic-adamx"><i class="fa fa-check"></i><b>13.3.1</b> Conditional moments of dynamic ADAMX</a></li>
<li class="chapter" data-level="13.3.2" data-path="ADAMXDynamic.html"><a href="ADAMXDynamic.html#known-explanatory-variables"><i class="fa fa-check"></i><b>13.3.2</b> Known explanatory variables</a></li>
<li class="chapter" data-level="13.3.3" data-path="ADAMXDynamic.html"><a href="ADAMXDynamic.html#random-explanatory-variables"><i class="fa fa-check"></i><b>13.3.3</b> Random explanatory variables</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="stability-and-forecastability-conditions-of-adamx.html"><a href="stability-and-forecastability-conditions-of-adamx.html"><i class="fa fa-check"></i><b>13.4</b> Stability and forecastability conditions of ADAMX</a></li>
<li class="chapter" data-level="13.5" data-path="ETSXDynamicCategories.html"><a href="ETSXDynamicCategories.html"><i class="fa fa-check"></i><b>13.5</b> Dealing with categorical variables in ADAMX</a></li>
<li class="chapter" data-level="13.6" data-path="ETSXRExample.html"><a href="ETSXRExample.html"><i class="fa fa-check"></i><b>13.6</b> Examples of application</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="ADAMETSEstimation.html"><a href="ADAMETSEstimation.html"><i class="fa fa-check"></i><b>14</b> Estimation of ADAM models</a>
<ul>
<li class="chapter" data-level="14.1" data-path="ADAMETSEstimationLikelihood.html"><a href="ADAMETSEstimationLikelihood.html"><i class="fa fa-check"></i><b>14.1</b> Maximum Likelihood Estimation</a>
<ul>
<li class="chapter" data-level="14.1.1" data-path="ADAMETSEstimationLikelihood.html"><a href="ADAMETSEstimationLikelihood.html#an-example-in-r-1"><i class="fa fa-check"></i><b>14.1.1</b> An example in R</a></li>
</ul></li>
<li class="chapter" data-level="14.2" data-path="non-mle-based-loss-functions.html"><a href="non-mle-based-loss-functions.html"><i class="fa fa-check"></i><b>14.2</b> Non MLE-based loss functions</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="non-mle-based-loss-functions.html"><a href="non-mle-based-loss-functions.html#MSEandMAEEstimators"><i class="fa fa-check"></i><b>14.2.1</b> MSE and MAE</a></li>
<li class="chapter" data-level="14.2.2" data-path="non-mle-based-loss-functions.html"><a href="non-mle-based-loss-functions.html#ham"><i class="fa fa-check"></i><b>14.2.2</b> HAM</a></li>
<li class="chapter" data-level="14.2.3" data-path="non-mle-based-loss-functions.html"><a href="non-mle-based-loss-functions.html#lasso-and-ridge"><i class="fa fa-check"></i><b>14.2.3</b> LASSO and RIDGE</a></li>
<li class="chapter" data-level="14.2.4" data-path="non-mle-based-loss-functions.html"><a href="non-mle-based-loss-functions.html#custom-losses"><i class="fa fa-check"></i><b>14.2.4</b> Custom losses</a></li>
<li class="chapter" data-level="14.2.5" data-path="non-mle-based-loss-functions.html"><a href="non-mle-based-loss-functions.html#examples-in-r"><i class="fa fa-check"></i><b>14.2.5</b> Examples in R</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="multistepLosses.html"><a href="multistepLosses.html"><i class="fa fa-check"></i><b>14.3</b> Multistep losses</a>
<ul>
<li class="chapter" data-level="14.3.1" data-path="multistepLosses.html"><a href="multistepLosses.html#mathrmmse_h---mse-for-h-steps-ahead"><i class="fa fa-check"></i><b>14.3.1</b> <span class="math inline">\(\mathrm{MSE}_h\)</span> - MSE for h steps ahead</a></li>
<li class="chapter" data-level="14.3.2" data-path="multistepLosses.html"><a href="multistepLosses.html#multistepLossesTMSE"><i class="fa fa-check"></i><b>14.3.2</b> TMSE - Trace MSE</a></li>
<li class="chapter" data-level="14.3.3" data-path="multistepLosses.html"><a href="multistepLosses.html#multistepLossesGTMSE"><i class="fa fa-check"></i><b>14.3.3</b> GTMSE - Geometric Trace MSE</a></li>
<li class="chapter" data-level="14.3.4" data-path="multistepLosses.html"><a href="multistepLosses.html#msce---mean-squared-cumulative-error"><i class="fa fa-check"></i><b>14.3.4</b> MSCE - Mean Squared Cumulative Error</a></li>
<li class="chapter" data-level="14.3.5" data-path="multistepLosses.html"><a href="multistepLosses.html#gpl---general-predictive-likelihood"><i class="fa fa-check"></i><b>14.3.5</b> GPL - General Predictive Likelihood</a></li>
<li class="chapter" data-level="14.3.6" data-path="multistepLosses.html"><a href="multistepLosses.html#other-multistep-estimators"><i class="fa fa-check"></i><b>14.3.6</b> Other multistep estimators</a></li>
<li class="chapter" data-level="14.3.7" data-path="multistepLosses.html"><a href="multistepLosses.html#an-example-in-r-2"><i class="fa fa-check"></i><b>14.3.7</b> An example in R</a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="ADAMInitialisation.html"><a href="ADAMInitialisation.html"><i class="fa fa-check"></i><b>14.4</b> Initialisation of ADAM</a>
<ul>
<li class="chapter" data-level="14.4.1" data-path="ADAMInitialisation.html"><a href="ADAMInitialisation.html#ADAMInitialisationOptAndBack"><i class="fa fa-check"></i><b>14.4.1</b> Optimisation vs backcasting</a></li>
<li class="chapter" data-level="14.4.2" data-path="ADAMInitialisation.html"><a href="ADAMInitialisation.html#pre-initialisation-of-adam-parameters"><i class="fa fa-check"></i><b>14.4.2</b> Pre-initialisation of ADAM parameters</a></li>
<li class="chapter" data-level="14.4.3" data-path="ADAMInitialisation.html"><a href="ADAMInitialisation.html#pre-initialisation-of-adam-states-ets"><i class="fa fa-check"></i><b>14.4.3</b> Pre-initialisation of ADAM states, ETS</a></li>
<li class="chapter" data-level="14.4.4" data-path="ADAMInitialisation.html"><a href="ADAMInitialisation.html#pre-initialisation-of-adam-states-arima"><i class="fa fa-check"></i><b>14.4.4</b> Pre-initialisation of ADAM states, ARIMA</a></li>
<li class="chapter" data-level="14.4.5" data-path="ADAMInitialisation.html"><a href="ADAMInitialisation.html#pre-initialisation-of-adam-states-regressors-and-constant"><i class="fa fa-check"></i><b>14.4.5</b> Pre-initialisation of ADAM states, Regressors and constant</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="multiple-frequencies-in-adam-ets.html"><a href="multiple-frequencies-in-adam-ets.html"><i class="fa fa-check"></i><b>15</b> Multiple frequencies in ADAM ETS</a>
<ul>
<li class="chapter" data-level="15.1" data-path="estimation-of-multiple-seasonal-model.html"><a href="estimation-of-multiple-seasonal-model.html"><i class="fa fa-check"></i><b>15.1</b> Estimation of multiple seasonal model</a>
<ul>
<li class="chapter" data-level="15.1.1" data-path="estimation-of-multiple-seasonal-model.html"><a href="estimation-of-multiple-seasonal-model.html#adam-ets-issues"><i class="fa fa-check"></i><b>15.1.1</b> ADAM ETS issues</a></li>
<li class="chapter" data-level="15.1.2" data-path="estimation-of-multiple-seasonal-model.html"><a href="estimation-of-multiple-seasonal-model.html#adam-arima-issues"><i class="fa fa-check"></i><b>15.1.2</b> ADAM ARIMA issues</a></li>
</ul></li>
<li class="chapter" data-level="15.2" data-path="ETSXMultipleSeasonality.html"><a href="ETSXMultipleSeasonality.html"><i class="fa fa-check"></i><b>15.2</b> Using explanatory variables for multiple seasonalities</a></li>
<li class="chapter" data-level="15.3" data-path="MultipleFrequenciesDSTandLeap.html"><a href="MultipleFrequenciesDSTandLeap.html"><i class="fa fa-check"></i><b>15.3</b> Dealing with daylight saving and leap years</a></li>
<li class="chapter" data-level="15.4" data-path="ADAMMultipleFrequenciesExamples.html"><a href="ADAMMultipleFrequenciesExamples.html"><i class="fa fa-check"></i><b>15.4</b> Examples of application</a>
<ul>
<li class="chapter" data-level="15.4.1" data-path="ADAMMultipleFrequenciesExamples.html"><a href="ADAMMultipleFrequenciesExamples.html#adam-ets"><i class="fa fa-check"></i><b>15.4.1</b> ADAM ETS</a></li>
<li class="chapter" data-level="15.4.2" data-path="ADAMMultipleFrequenciesExamples.html"><a href="ADAMMultipleFrequenciesExamples.html#adam-etsx"><i class="fa fa-check"></i><b>15.4.2</b> ADAM ETSX</a></li>
<li class="chapter" data-level="15.4.3" data-path="ADAMMultipleFrequenciesExamples.html"><a href="ADAMMultipleFrequenciesExamples.html#adam-arima"><i class="fa fa-check"></i><b>15.4.3</b> ADAM ARIMA</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="ADAMIntermittent.html"><a href="ADAMIntermittent.html"><i class="fa fa-check"></i><b>16</b> ADAM for Intermittent Demand</a>
<ul>
<li class="chapter" data-level="16.1" data-path="ADAMOccurrence.html"><a href="ADAMOccurrence.html"><i class="fa fa-check"></i><b>16.1</b> Occurrence part of the model</a>
<ul>
<li class="chapter" data-level="16.1.1" data-path="ADAMOccurrence.html"><a href="ADAMOccurrence.html#fixed-probability-model-oets_f"><i class="fa fa-check"></i><b>16.1.1</b> Fixed probability model, oETS<span class="math inline">\(_F\)</span></a></li>
<li class="chapter" data-level="16.1.2" data-path="ADAMOccurrence.html"><a href="ADAMOccurrence.html#oETSO"><i class="fa fa-check"></i><b>16.1.2</b> Odds ratio model, oETS<span class="math inline">\(_O\)</span></a></li>
<li class="chapter" data-level="16.1.3" data-path="ADAMOccurrence.html"><a href="ADAMOccurrence.html#inverse-odds-ratio-model-oets_i"><i class="fa fa-check"></i><b>16.1.3</b> Inverse odds ratio model, oETS<span class="math inline">\(_I\)</span></a></li>
<li class="chapter" data-level="16.1.4" data-path="ADAMOccurrence.html"><a href="ADAMOccurrence.html#oETSG"><i class="fa fa-check"></i><b>16.1.4</b> General oETS model, oETS<span class="math inline">\(_G\)</span></a></li>
<li class="chapter" data-level="16.1.5" data-path="ADAMOccurrence.html"><a href="ADAMOccurrence.html#direct-probability-model-oets_d"><i class="fa fa-check"></i><b>16.1.5</b> Direct probability model, oETS<span class="math inline">\(_D\)</span></a></li>
<li class="chapter" data-level="16.1.6" data-path="ADAMOccurrence.html"><a href="ADAMOccurrence.html#oETSModelSelection"><i class="fa fa-check"></i><b>16.1.6</b> Model selection in oETS</a></li>
</ul></li>
<li class="chapter" data-level="16.2" data-path="ADAMDemandSizes.html"><a href="ADAMDemandSizes.html"><i class="fa fa-check"></i><b>16.2</b> Demand sizes part of the model</a>
<ul>
<li class="chapter" data-level="16.2.1" data-path="ADAMDemandSizes.html"><a href="ADAMDemandSizes.html#additive-vs-multiplicative-ets-for-demand-sizes"><i class="fa fa-check"></i><b>16.2.1</b> Additive vs multiplicative ETS for demand sizes</a></li>
<li class="chapter" data-level="16.2.2" data-path="ADAMDemandSizes.html"><a href="ADAMDemandSizes.html#using-arima-for-demand-sizes"><i class="fa fa-check"></i><b>16.2.2</b> Using ARIMA for demand sizes</a></li>
</ul></li>
<li class="chapter" data-level="16.3" data-path="ADAMIntermittentFull.html"><a href="ADAMIntermittentFull.html"><i class="fa fa-check"></i><b>16.3</b> The full ADAM model</a>
<ul>
<li class="chapter" data-level="16.3.1" data-path="ADAMIntermittentFull.html"><a href="ADAMIntermittentFull.html#iETSMLE"><i class="fa fa-check"></i><b>16.3.1</b> Maximum Likelihood Estimation</a></li>
<li class="chapter" data-level="16.3.2" data-path="ADAMIntermittentFull.html"><a href="ADAMIntermittentFull.html#conditional-expectation-and-variance"><i class="fa fa-check"></i><b>16.3.2</b> Conditional expectation and variance</a></li>
</ul></li>
<li class="chapter" data-level="16.4" data-path="examples-of-application-1.html"><a href="examples-of-application-1.html"><i class="fa fa-check"></i><b>16.4</b> Examples of application</a></li>
<li class="chapter" data-level="16.5" data-path="intermittent-demand-challenges.html"><a href="intermittent-demand-challenges.html"><i class="fa fa-check"></i><b>16.5</b> Intermittent demand challenges</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="diagnostics.html"><a href="diagnostics.html"><i class="fa fa-check"></i><b>17</b> Model diagnostics</a>
<ul>
<li class="chapter" data-level="17.1" data-path="diagnosticsOmitted.html"><a href="diagnosticsOmitted.html"><i class="fa fa-check"></i><b>17.1</b> Model specification: Omitted variables</a></li>
<li class="chapter" data-level="17.2" data-path="model-specification-redundant-variables.html"><a href="model-specification-redundant-variables.html"><i class="fa fa-check"></i><b>17.2</b> Model specification: Redundant variables</a></li>
<li class="chapter" data-level="17.3" data-path="diagnosticsTransformations.html"><a href="diagnosticsTransformations.html"><i class="fa fa-check"></i><b>17.3</b> Model specification: Transformations</a></li>
<li class="chapter" data-level="17.4" data-path="diagnosticsOutliers.html"><a href="diagnosticsOutliers.html"><i class="fa fa-check"></i><b>17.4</b> Model specification: Outliers</a>
<ul>
<li class="chapter" data-level="17.4.1" data-path="diagnosticsOutliers.html"><a href="diagnosticsOutliers.html#outliers-detection"><i class="fa fa-check"></i><b>17.4.1</b> Outliers detection</a></li>
<li class="chapter" data-level="17.4.2" data-path="diagnosticsOutliers.html"><a href="diagnosticsOutliers.html#dealing-with-outliers"><i class="fa fa-check"></i><b>17.4.2</b> Dealing with outliers</a></li>
<li class="chapter" data-level="17.4.3" data-path="diagnosticsOutliers.html"><a href="diagnosticsOutliers.html#an-automatic-mechanism"><i class="fa fa-check"></i><b>17.4.3</b> An automatic mechanism</a></li>
<li class="chapter" data-level="17.4.4" data-path="diagnosticsOutliers.html"><a href="diagnosticsOutliers.html#final-remarks"><i class="fa fa-check"></i><b>17.4.4</b> Final remarks</a></li>
</ul></li>
<li class="chapter" data-level="17.5" data-path="diagnosticsResidualsIIDAuto.html"><a href="diagnosticsResidualsIIDAuto.html"><i class="fa fa-check"></i><b>17.5</b> Residuals are i.i.d.: autocorrelation</a></li>
<li class="chapter" data-level="17.6" data-path="diagnosticsResidualsIIDHetero.html"><a href="diagnosticsResidualsIIDHetero.html"><i class="fa fa-check"></i><b>17.6</b> Residuals are i.i.d.: heteroscedasticity</a>
<ul>
<li class="chapter" data-level="17.6.1" data-path="diagnosticsResidualsIIDHetero.html"><a href="diagnosticsResidualsIIDHetero.html#detecting-heteroscedasticity"><i class="fa fa-check"></i><b>17.6.1</b> Detecting heteroscedasticity</a></li>
</ul></li>
<li class="chapter" data-level="17.7" data-path="residuals-are-i-i-d-zero-expectation.html"><a href="residuals-are-i-i-d-zero-expectation.html"><i class="fa fa-check"></i><b>17.7</b> Residuals are i.i.d.: zero expectation</a></li>
<li class="chapter" data-level="17.8" data-path="residuals-are-i-i-d-distributional-assumptions.html"><a href="residuals-are-i-i-d-distributional-assumptions.html"><i class="fa fa-check"></i><b>17.8</b> Residuals are i.i.d.: distributional assumptions</a></li>
<li class="chapter" data-level="17.9" data-path="multicollinearity.html"><a href="multicollinearity.html"><i class="fa fa-check"></i><b>17.9</b> Multicollinearity</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="ADAMSelection.html"><a href="ADAMSelection.html"><i class="fa fa-check"></i><b>18</b> Model selection and combinations in ADAM</a>
<ul>
<li class="chapter" data-level="18.1" data-path="ETSSelection.html"><a href="ETSSelection.html"><i class="fa fa-check"></i><b>18.1</b> ADAM ETS components selection</a></li>
<li class="chapter" data-level="18.2" data-path="ARIMASelection.html"><a href="ARIMASelection.html"><i class="fa fa-check"></i><b>18.2</b> ADAM ARIMA order selection</a></li>
<li class="chapter" data-level="18.3" data-path="ETSXSelection.html"><a href="ETSXSelection.html"><i class="fa fa-check"></i><b>18.3</b> Explanatory variables selection</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Forecasting and Analytics with ADAM</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div class = rmdreview>
This book is in <b><a href="open.html#open">Open Review</a></b>. I want your feedback to make the book better for you and other readers. To add your annotation, <span style="background-color: #3297FD; color: white">select some text</span> and then click the <i class="h-icon-annotate"></i> on the pop-up menu. To see the annotations of others, click the button in the upper right hand corner of the page <i class="fa fa-arrow-circle-right  fa-rotate-315" aria-hidden="true"></i>
</div>
<div id="dummyVariables" class="section level2" number="3.4">
<h2><span class="header-section-number">3.4</span> Regression with categorical variables</h2>
<p>So far we assumed that the explanatory variables in the model are numerical. But is it possible to include somehow in regression model variables in categorical scales, for example, colour and size of t-shirts? Yes, it is. This is done using so called “dummy variables.”</p>
<p>As we remember from Section <a href="scales.html#scales">1.2</a>, the variables in categorical scale do not have distance or natural zero. This means that if we encode the values in numbers (e.g. “red” - “1,” “green” - “2,” “blue” - “3”), then these numbers will not have any proper mathematical meaning - they will only represent specific values (and order in case of ordinal scale), but we would be limited in operations with these values. In order to overcome this limitation, we could create a set of dummy variables, each of which would be equal to one if the value of the original variable is equal to a specific value and zero otherwise. Consider the example with colours, where we have three types of t-shirts to sell:</p>
<ol style="list-style-type: decimal">
<li>Red,</li>
<li>Green,</li>
<li>Blue.</li>
</ol>
<p>Every t-shirt in our dataset would have one of these colours, and based on this we could create three dummy variables:</p>
<ol style="list-style-type: decimal">
<li>colourRed, which would be equal to one if the t-shirt is Red and zero otherwise,</li>
<li>colourGreen: 1 if the t-shirt is Green and 0 otherwise,</li>
<li>colourBlue: 1 if the t-shirt is Blue and 0 otherwise.</li>
</ol>
<p>These dummy variables can then be added to a model instead of the original variable colour, resulting, for example, in the model:
<span class="math display" id="eq:regressionDummies01">\[\begin{equation}
    sales_t = a_0 + a_1 price_t + a_2 colourRed_t + a_3 colourGreen_t + \epsilon_t .
    \tag{3.32}
\end{equation}\]</span>
Notice that I have only included two dummy variables out of the three. This is because we do not need to have all of them to be able to say what colour of t-shirt we have: if it is not Red and not Green, then it must be Blue. Furthermore, while some models and estimation methods could handle all the dummy variables in the model, the linear regression cannot be estimated via the conventional methods if they are all in. This is exactly because of this situation with “not Red, not Green.” If we introduce all three, the model will have so called “dummy variables trap,” implying perfect multicollinearity (see Subsection <a href="assumptions.html#assumptionsXreg">3.6.3</a>), because of the functional relation between variables:
<span class="math display" id="eq:regressionDummies02">\[\begin{equation}
    colourBlue_t = 1 - colourRed_t - colourGreen_t \text{ for all } t .
    \tag{3.33}
\end{equation}\]</span>
This is a general rule: if you have created a set of dummy variables from a categorical one, then one of them needs to be dropped, in order not to have the dummy variables trap.</p>
<p>So, what does the inclusion of dummy variables in the regression model means? We can see that on the following example of artificial data:</p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="dummyVariables.html#cb125-1" aria-hidden="true" tabindex="-1"></a>tShirts <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="fu">rnorm</span>(<span class="dv">150</span>,<span class="dv">20</span>,<span class="dv">2</span>),<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>)</span>
<span id="cb125-2"><a href="dummyVariables.html#cb125-2" aria-hidden="true" tabindex="-1"></a>tShirts[<span class="dv">1</span><span class="sc">:</span><span class="dv">50</span>,<span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb125-3"><a href="dummyVariables.html#cb125-3" aria-hidden="true" tabindex="-1"></a>tShirts[<span class="dv">1</span><span class="sc">:</span><span class="dv">50</span><span class="sc">+</span><span class="dv">50</span>,<span class="dv">3</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb125-4"><a href="dummyVariables.html#cb125-4" aria-hidden="true" tabindex="-1"></a>tShirts[<span class="dv">1</span><span class="sc">:</span><span class="dv">50</span><span class="sc">+</span><span class="dv">50</span><span class="sc">*</span><span class="dv">2</span>,<span class="dv">4</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb125-5"><a href="dummyVariables.html#cb125-5" aria-hidden="true" tabindex="-1"></a>tShirts <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="dv">1000</span> <span class="sc">+</span> tShirts <span class="sc">%*%</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">2.5</span>, <span class="dv">30</span>, <span class="sc">-</span><span class="dv">20</span>, <span class="dv">50</span>) <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">150</span>,<span class="dv">0</span>,<span class="dv">5</span>), tShirts)</span>
<span id="cb125-6"><a href="dummyVariables.html#cb125-6" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(tShirts) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;sales&quot;</span>,<span class="st">&quot;price&quot;</span>,<span class="st">&quot;colourRed&quot;</span>,<span class="st">&quot;colourGreen&quot;</span>,<span class="st">&quot;colourBlue&quot;</span>)</span></code></pre></div>
<p>We can produce spread plot to see how the data looks like:</p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="dummyVariables.html#cb126-1" aria-hidden="true" tabindex="-1"></a><span class="fu">spread</span>(tShirts)</span></code></pre></div>
<div class="figure"><span id="fig:tShirtsSpread"></span>
<img src="adam_files/figure-html/tShirtsSpread-1.png" alt="Spread plot of t-shirts data." width="672" />
<p class="caption">
Figure 3.14: Spread plot of t-shirts data.
</p>
</div>
<p>Figure @red(fig:tShirtsSpread) demonstrates that the sales differ depending on the type of colour (the boxplots). The scatterplot between sales and price is not very clear, but there are actually three theoretical lines on that plot. We can enlarge the plot and draw them:</p>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="dummyVariables.html#cb127-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(tShirts[,<span class="dv">2</span><span class="sc">:</span><span class="dv">1</span>])</span>
<span id="cb127-2"><a href="dummyVariables.html#cb127-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">a=</span><span class="dv">1000</span><span class="sc">+</span><span class="dv">30</span>, <span class="at">b=</span><span class="sc">-</span><span class="fl">2.5</span>, <span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span>
<span id="cb127-3"><a href="dummyVariables.html#cb127-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">a=</span><span class="dv">1000-20</span>, <span class="at">b=</span><span class="sc">-</span><span class="fl">2.5</span>, <span class="at">col=</span><span class="st">&quot;green&quot;</span>)</span>
<span id="cb127-4"><a href="dummyVariables.html#cb127-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">a=</span><span class="dv">1000</span><span class="sc">+</span><span class="dv">50</span>, <span class="at">b=</span><span class="sc">-</span><span class="fl">2.5</span>, <span class="at">col=</span><span class="st">&quot;blue&quot;</span>)</span></code></pre></div>
<div class="figure"><span id="fig:tShirtsScatterPlot"></span>
<img src="adam_files/figure-html/tShirtsScatterPlot-1.png" alt="Scatterplot of Sales vs Price of t-shirts of different colour." width="672" />
<p class="caption">
Figure 3.15: Scatterplot of Sales vs Price of t-shirts of different colour.
</p>
</div>
<p>Now, if we want to construct the regression that would take these differences into account, we need to estimate the model <a href="dummyVariables.html#eq:regressionDummies01">(3.32)</a>:</p>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="dummyVariables.html#cb128-1" aria-hidden="true" tabindex="-1"></a>tShirtsALM <span class="ot">&lt;-</span> <span class="fu">alm</span>(sales<span class="sc">~</span>price<span class="sc">+</span>colourRed<span class="sc">+</span>colourGreen, tShirts, <span class="at">loss=</span><span class="st">&quot;MSE&quot;</span>)</span>
<span id="cb128-2"><a href="dummyVariables.html#cb128-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(tShirtsALM)</span></code></pre></div>
<pre><code>## Response variable: sales
## Distribution used in the estimation: Normal
## Loss function used in estimation: MSE
## Coefficients:
##              Estimate Std. Error Lower 2.5% Upper 97.5%  
## (Intercept) 1047.4500     4.3014  1038.9489   1055.9511 *
## price         -2.3520     0.2136    -2.7742     -1.9299 *
## colourRed    -19.8512     1.0090   -21.8453    -17.8570 *
## colourGreen  -71.3793     1.0085   -73.3724    -69.3861 *
## 
## Error standard deviation: 5.0424
## Sample size: 150
## Number of estimated parameters: 4
## Number of degrees of freedom: 146
## Information criteria:
##      AIC     AICc      BIC     BICc 
## 914.9932 915.2690 927.0357 927.7268</code></pre>
<p>Notice that the intercept in this model is not 1000, as we used in the generation of the data, but is 1047. This is because it now also contains the effect of blue colour on sales in it. So, the sales of blue coloured t-shirt is now the baseline category, and each dummy variable now represents the shifts of sales, when we switch from one colour to another. For example, we can say that <em>the sales of red colour t-shirt are on average lower than the sales of the blue one by approximately 20 units</em>. What dummy variables do in the model is just shift the line from one level to another. This becomes clear if we consider special cases of models for the three t-shirts:</p>
<ol style="list-style-type: decimal">
<li>For the blue t-shirt, our model is: sales=1047.45-2.35price+et. This is because both <code>colourRed</code> and <code>colourGreen</code> are zero in this case;</li>
<li>For the red t-shirt the model is: sales=1047.45+-19.85-2.35price+et or sales=1027.6-2.35price+et;</li>
<li>Finally, for the green one, the model is: sales=1047.45+-71.38-2.35price+et or sales=976.07-2.35price+et.</li>
</ol>
<p>In a way, we could have constructed three different regression models for the sub-samples of data, and in the ideal situation (all the data in the world) we would get the same set of estimates of parameters. However, this would be a costly procedure from the statistical perspective, because three separate models will have lower number of degrees of freedom, then the model with dummy variables. Thus, the estimates of parameters will be more uncertain in those three models than in one model <code>tShirtsALM</code>.</p>
<p>One thing that we can remark is that the estimated parameters differ from the ones we used in the data generation. This is because the intercepts of the three models above intersect the y-axis in the points 1047.45, 1027.6 and 976.07 respectively. Furthermore, in general it is not possible to extract the specific effect of blue colour on sales based on the estimates of parameters, unless we impose some restrictions on parameters. The closest we can get to the true parameters is if we normalise them (assuming that there is some baseline and that the colours build upon it and add up to zero):</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="dummyVariables.html#cb130-1" aria-hidden="true" tabindex="-1"></a>colourParameters <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">coef</span>(tShirtsALM)[<span class="dv">3</span><span class="sc">:</span><span class="dv">4</span>]<span class="sc">+</span><span class="fu">coef</span>(tShirtsALM)[<span class="dv">1</span>],<span class="fu">coef</span>(tShirtsALM)[<span class="dv">1</span>])</span>
<span id="cb130-2"><a href="dummyVariables.html#cb130-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(colourParameters)[<span class="dv">3</span>] <span class="ot">&lt;-</span> <span class="st">&quot;colourBlue&quot;</span>;</span>
<span id="cb130-3"><a href="dummyVariables.html#cb130-3" aria-hidden="true" tabindex="-1"></a>colourParameters <span class="sc">-</span> <span class="fu">mean</span>(colourParameters)</span></code></pre></div>
<pre><code>##   colourRed colourGreen  colourBlue 
##    10.55897   -40.96912    30.41015</code></pre>
<p>The meaning of these effects is that on average they change the baseline sales of colourless t-shirts according to these values. For example, the specific increase of sales due to the red colour of t-shirt is 11 units. In general, it is not worth bothering with these specific effects, and we can just stick with parameters of model, keeping in mind that we only have effects comparative to the selected baseline category.</p>
<p>In R, we can also work with factor variables, without a need to expand variables in a set of dummies - the program will do the expansion automatically and drop the first level of the variable. In order to see how it works, we create a data frame with the factor variable <code>colour</code>:</p>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="dummyVariables.html#cb132-1" aria-hidden="true" tabindex="-1"></a>tShirtsDataFrame <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(tShirts[,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>])</span>
<span id="cb132-2"><a href="dummyVariables.html#cb132-2" aria-hidden="true" tabindex="-1"></a>tShirtsDataFrame<span class="sc">$</span>colour <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">c</span>(<span class="st">&quot;Red&quot;</span>,<span class="st">&quot;Green&quot;</span>,<span class="st">&quot;Blue&quot;</span>)[tShirts[,<span class="dv">3</span><span class="sc">:</span><span class="dv">5</span>] <span class="sc">%*%</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>)])</span>
<span id="cb132-3"><a href="dummyVariables.html#cb132-3" aria-hidden="true" tabindex="-1"></a><span class="fu">spread</span>(tShirtsDataFrame)</span></code></pre></div>
<p><img src="adam_files/figure-html/unnamed-chunk-56-1.png" width="672" /></p>
<p>Notice that the “Blue” was automatically set as the first level, because <code>factor()</code> function would sort labels alphabetically unless the levels are provided explicitly. The estimated model in this case will be exactly the same as the <code>tShirts</code> model above:</p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="dummyVariables.html#cb133-1" aria-hidden="true" tabindex="-1"></a>tShirtsDataFrameALM <span class="ot">&lt;-</span> <span class="fu">alm</span>(sales<span class="sc">~</span>price<span class="sc">+</span>colour, tShirtsDataFrame, <span class="at">loss=</span><span class="st">&quot;MSE&quot;</span>)</span>
<span id="cb133-2"><a href="dummyVariables.html#cb133-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(tShirtsDataFrameALM)</span></code></pre></div>
<pre><code>## Response variable: sales
## Distribution used in the estimation: Normal
## Loss function used in estimation: MSE
## Coefficients:
##              Estimate Std. Error Lower 2.5% Upper 97.5%  
## (Intercept) 1047.4500     4.3014  1038.9489   1055.9511 *
## price         -2.3520     0.2136    -2.7742     -1.9299 *
## colourGreen  -71.3793     1.0085   -73.3724    -69.3861 *
## colourRed    -19.8512     1.0090   -21.8453    -17.8570 *
## 
## Error standard deviation: 5.0424
## Sample size: 150
## Number of estimated parameters: 4
## Number of degrees of freedom: 146
## Information criteria:
##      AIC     AICc      BIC     BICc 
## 914.9932 915.2690 927.0357 927.7268</code></pre>
<p>Finally, it is recommended in general not to drop dummy variables one by one, if for some reason you decide that some of them are not helping. If, for example, we decide not to include <code>colourRed</code> and only have the model with <code>colourGreen</code>, then the meaning of the dummy variables will change - we will not be able to distinguish the Blue from Red. Furthermore, while some dummy variables might not seem important (or significant) in regression, their combination might be improving the model, and dropping some of them might be damaging for the model in terms of its predictive power. So, it is more common either to include all levels (but one) of categorical variable or not to include any of them.</p>
<div id="categorical-variables-for-the-slope" class="section level3" number="3.4.1">
<h3><span class="header-section-number">3.4.1</span> Categorical variables for the slope</h3>
<p>In reality, we can have more complicated situations, when the change of price would lead to different changes in sales for different types of t-shirts. In this case, we are talking about an <strong>interaction effect</strong> between price and colour. The following artificial example demonstrates the situation:</p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="dummyVariables.html#cb135-1" aria-hidden="true" tabindex="-1"></a>tShirtsInteraction <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="fu">rnorm</span>(<span class="dv">150</span>,<span class="dv">20</span>,<span class="dv">2</span>),<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>)</span>
<span id="cb135-2"><a href="dummyVariables.html#cb135-2" aria-hidden="true" tabindex="-1"></a>tShirtsInteraction[<span class="dv">1</span><span class="sc">:</span><span class="dv">50</span>,<span class="dv">2</span>] <span class="ot">&lt;-</span> tShirtsInteraction[<span class="dv">1</span><span class="sc">:</span><span class="dv">50</span>,<span class="dv">1</span>]</span>
<span id="cb135-3"><a href="dummyVariables.html#cb135-3" aria-hidden="true" tabindex="-1"></a>tShirtsInteraction[<span class="dv">1</span><span class="sc">:</span><span class="dv">50</span><span class="sc">+</span><span class="dv">50</span>,<span class="dv">3</span>] <span class="ot">&lt;-</span> tShirtsInteraction[<span class="dv">1</span><span class="sc">:</span><span class="dv">50</span><span class="sc">+</span><span class="dv">50</span>,<span class="dv">1</span>]</span>
<span id="cb135-4"><a href="dummyVariables.html#cb135-4" aria-hidden="true" tabindex="-1"></a>tShirtsInteraction[<span class="dv">1</span><span class="sc">:</span><span class="dv">50</span><span class="sc">+</span><span class="dv">50</span><span class="sc">*</span><span class="dv">2</span>,<span class="dv">4</span>] <span class="ot">&lt;-</span> tShirtsInteraction[<span class="dv">1</span><span class="sc">:</span><span class="dv">50</span><span class="sc">+</span><span class="dv">50</span><span class="sc">*</span><span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb135-5"><a href="dummyVariables.html#cb135-5" aria-hidden="true" tabindex="-1"></a>tShirtsInteraction <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="dv">1000</span> <span class="sc">+</span> tShirtsInteraction <span class="sc">%*%</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">2.5</span>, <span class="sc">-</span><span class="fl">1.5</span>, <span class="sc">-</span><span class="fl">0.5</span>, <span class="sc">-</span><span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb135-6"><a href="dummyVariables.html#cb135-6" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">rnorm</span>(<span class="dv">150</span>,<span class="dv">0</span>,<span class="dv">5</span>), tShirtsInteraction)</span>
<span id="cb135-7"><a href="dummyVariables.html#cb135-7" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(tShirtsInteraction) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;sales&quot;</span>,<span class="st">&quot;price&quot;</span>,<span class="st">&quot;price:colourRed&quot;</span>,</span>
<span id="cb135-8"><a href="dummyVariables.html#cb135-8" aria-hidden="true" tabindex="-1"></a>                                  <span class="st">&quot;price:colourGreen&quot;</span>,<span class="st">&quot;price:colourBlue&quot;</span>)</span></code></pre></div>
<p>This artificial data can be plotted in the following way to show the effect:</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="dummyVariables.html#cb136-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(tShirtsInteraction[,<span class="dv">2</span><span class="sc">:</span><span class="dv">1</span>])</span>
<span id="cb136-2"><a href="dummyVariables.html#cb136-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">a=</span><span class="dv">1000</span>, <span class="at">b=</span><span class="sc">-</span><span class="fl">2.5-1.5</span>, <span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span>
<span id="cb136-3"><a href="dummyVariables.html#cb136-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">a=</span><span class="dv">1000</span>, <span class="at">b=</span><span class="sc">-</span><span class="fl">2.5-0.5</span>, <span class="at">col=</span><span class="st">&quot;green&quot;</span>)</span>
<span id="cb136-4"><a href="dummyVariables.html#cb136-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">a=</span><span class="dv">1000</span>, <span class="at">b=</span><span class="sc">-</span><span class="fl">2.5</span><span class="dv">-4</span>, <span class="at">col=</span><span class="st">&quot;blue&quot;</span>)</span></code></pre></div>
<div class="figure"><span id="fig:tShirtsInteractionScatterPlot"></span>
<img src="adam_files/figure-html/tShirtsInteractionScatterPlot-1.png" alt="Scatterplot of Sales vs Price of t-shirts of different colour, interaction effect." width="672" />
<p class="caption">
Figure 3.16: Scatterplot of Sales vs Price of t-shirts of different colour, interaction effect.
</p>
</div>
<p>The plot on Figure <a href="dummyVariables.html#fig:tShirtsInteractionScatterPlot">3.16</a> shows that there are three categories of data and that for each of it, the price effect will be different: the increase in price by one unit leads to the faster reduction of sales for the blue t-shirts than for the others. Compare this with Figure <a href="dummyVariables.html#fig:tShirtsScatterPlot">3.15</a>, where we had the difference only in intercepts. This implies a different model:
<span class="math display" id="eq:regressionDummies03">\[\begin{equation}
    sales_t = a_0 + a_1 price_t + a_2 price_t \times colourRed_t + a_3 price_t \times colourGreen_t + \epsilon_t .
    \tag{3.34}
\end{equation}\]</span>
Notice that we still include only two dummy variables out of three in order to avoid the dummy variables trap. What is new in this case is the multiplication of price by the dummy variables. This trick allows changing the slope of price, depending on the colour of t-shirt. For example, here what the model <a href="dummyVariables.html#eq:regressionDummies03">(3.34)</a> would look like for the three types of colours:</p>
<ol style="list-style-type: decimal">
<li>Red colour: <span class="math inline">\(sales_t = a_0 + a_1 price_t + a_2 price_t + \epsilon_t\)</span> or <span class="math inline">\(sales_t = a_0 + (a_1 + a_2) price_t + \epsilon_t\)</span>;</li>
<li>Green colour: <span class="math inline">\(sales_t = a_0 + a_1 price_t + a_3 price_t + \epsilon_t\)</span> or <span class="math inline">\(sales_t = a_0 + (a_1 + a_3) price_t + \epsilon_t\)</span>;</li>
<li>Blue colour: <span class="math inline">\(sales_t = a_0 + a_1 price_t + \epsilon_t\)</span>.</li>
</ol>
<p>In R, the interaction effect can be introduced explicitly in the formula via <code>:</code> symbol if you have a proper factor variable:</p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="dummyVariables.html#cb137-1" aria-hidden="true" tabindex="-1"></a>tShirtsInteractionDataFrame <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(tShirtsInteraction[,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>])</span>
<span id="cb137-2"><a href="dummyVariables.html#cb137-2" aria-hidden="true" tabindex="-1"></a>tShirtsInteractionDataFrame<span class="sc">$</span>colour <span class="ot">&lt;-</span> tShirtsDataFrame<span class="sc">$</span>colour</span>
<span id="cb137-3"><a href="dummyVariables.html#cb137-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the model</span></span>
<span id="cb137-4"><a href="dummyVariables.html#cb137-4" aria-hidden="true" tabindex="-1"></a>tShirtsInteractionDataFrameALM <span class="ot">&lt;-</span> <span class="fu">alm</span>(sales<span class="sc">~</span>price<span class="sc">+</span>price<span class="sc">:</span>colour,</span>
<span id="cb137-5"><a href="dummyVariables.html#cb137-5" aria-hidden="true" tabindex="-1"></a>                                      tShirtsInteractionDataFrame, <span class="at">loss=</span><span class="st">&quot;MSE&quot;</span>)</span>
<span id="cb137-6"><a href="dummyVariables.html#cb137-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(tShirtsInteractionDataFrameALM)</span></code></pre></div>
<pre><code>## Response variable: sales
## Distribution used in the estimation: Normal
## Loss function used in estimation: MSE
## Coefficients:
##                    Estimate Std. Error Lower 2.5% Upper 97.5%  
## (Intercept)       1004.0430     4.2858   995.5728   1012.5131 *
## price               -6.7287     0.2157    -7.1550     -6.3024 *
## price:colourGreen    3.6063     0.0514     3.5047      3.7078 *
## price:colourRed      2.5305     0.0521     2.4277      2.6334 *
## 
## Error standard deviation: 5.1914
## Sample size: 150
## Number of estimated parameters: 4
## Number of degrees of freedom: 146
## Information criteria:
##      AIC     AICc      BIC     BICc 
## 923.7266 924.0024 935.7691 936.4602</code></pre>
<p>Note that the interpretation of parameters in such model will be different, because now the <code>price</code> shows the baseline effect for the blue t-shirts, while the interaction effects show how this effect will change for other colours. So, for example, in order to see what would be the effect of price change on sales of red t-shirts, we need to sum up the parameter for <code>price</code> and <code>price:colourRed</code>. We then can say that if price of red t-shirt increases by £1, the sales will decrease on average by 4.2 units.</p>
</div>
</div>

            </section>

          </div>
        </div>
      </div>
<a href="regression-uncertainty.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="variables-transformations.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/config-i1/adam/tree/master/Chapters//03-regression.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["adam.pdf", "adam.epub"],
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
