# Forecasting process and forecasts evaluation {#forecastingProcess}
Before we move to the discussion of models and their estimation it makes sense to discuss the forecasting process and how the forecasts should be evaluated. We should start by saying that forecasting needs to be done for a specific purpose. It should not be done just because you can do that. Forecasts should be useful for specific decisions. And these decisions dictate what forecasts and on what horizons to do.

```{example}
Retailers typically need to order some amount of milk that they will sell over the next week. They do not know, how much they will sell, so they usually order, hoping to satisfy, let us say, 95% of demand. This situation tells us that the forecasts need to be done for a week ahead, they should be cumulative (considering the overal demand during a week before the next order) and that they should focus on an upper bound of a 95% prediction interval. Producing just point forecasts might not be useful in this situation.
```

When you understand how your system works and what sort of forecasts you should produce, then you can start an evaluation process, measuring the performance of several forecasting models / methods and selecting the most appropriate for your data. There are different ways how the performance of models / methods can be measured and compared.


## Measuring accuracy of point forecasts {#errorMeasures}
We start with a situation, when point forecasts are of the main interest. In this case we typically start by splitting the available data into train and test sets, and apply the models under consideration to the first one, producing the forecasts for the second, not showing that part to the model. This is called "fixed origin" approach: we fix the point in time, from which to produce forecasts, we produce them, calculate some sort of error measures and compare the models.

There are different error measures that can be used in this case, the selection of one depends on the specific needs. Here we briefly discuss them, noting that the topic has already been extensively discussed in different sources [@Davydenko2013; @SvetunkovAccuracy2019; @SvetunkovAPEs2017]. Here we discuss only the main aspects of the error measures.

The very basic error measures are Root Mean Squared Error (RMSE):
\begin{equation}
    \text{RMSE} = \sqrt{\frac{1}{h} \sum_{j=1}^h \left( y_{t+j} - \hat{y}_{t+j} \right)^2 },
    (\#eq:RMSE)
\end{equation}
and Mean Absolute Error (MAE):
\begin{equation}
    \text{MAE} = \frac{1}{h} \sum_{j=1}^h \left| y_{t+j} - \hat{y}_{t+j} \right| ,
    (\#eq:MAE)
\end{equation}
where $y_{t+j}$ is the actual value $j$ steps ahead from the holdout, $\hat{y}_{t+j}$ is the $j$ steps ahead point forecast (conditional expectation of the model) and $h$ is the forecast horizon. As you see, these error measures aggregate the performance of competing forecasting methods across the forecasting horizon, averaging out the specific performances on each $j$. If this information needs to be retained, then the summation can be dropped to obtain just "SE" and "AE".

It is well-known [see, for example, @Kolassa2016] that RMSE is minimised by the mean value of a distribution, and MAE is minimised by the median. So, when selecting between the two, you should consider this property.

The main advantage of these error measures is that they are very simple and have a clear interprertation: they show the average distance from the point forecasts to the actual values. They are perfect if you work with only one time series. However, they are not suitable, when you have several time series and want to see the performance of methods across them. This is mainly because they are scale dependent and contain specific units: if you measures sales of bananas in pounds, then MAE and RMSE will show the error in pounds. And, as we know, you should not add up pounds of bananas with pounds of apples - the result might not make sense.

In order to tackle this issue, different error scaling techniques have been proposed over the years, resulting in a zoo of error measures:

1. MAPE - Mean Absolute Percentage Error;
2. MASE - Mean Absolute Scaled Error [@Hyndman2006];
3. rMAE - Relative Mean Absolute Error [@Davydenko2013];
4. sMAE - scaled Mean Absolute Error [@Petropoulos2015];
5. and others.

They have their own advantages and disadvantages, and we will not discuss them here. It should suffice to say that the selection of error measure should be dictated by the needs of the forecaster. If you want a robust measure that works consistently, but do not care about the interpretation, then go with MASE. If you want an interpretation, then either go with rMAE, or sMAE. And you typically should avoid MAPE and other Percentage Error measures, because they are highly influenced by the actual values you have in the holdout. Furthermore, similarly to the measures above, one can propose RMSE-based scaled and relative error measures.

Finally, when aggregating performance of forecasting methods across several time series, sometimes it makes sense to look at the distribution of errors - this way you will know, which of the methods fails seriously, and which does a consistently good job.


## Measuring uncertainty
While point forecasts are useful, prediction intervals are important in many areas of application as well. They allow getting an understanding about the uncertainty around the point forecasts and thus allow making less risky decisions. 


## Rolling origin {#rollingOrigin}


## Statistical tests


