# Exponential smoothing method and ETS

We start our discussion of exponential smoothing with the original Simple Exponential Smoothing (SES) forecasting method, which was formulated by [@Brown1956]:
\begin{equation}
  \hat{y}_{t+1} = \alpha {y}_{t} + (1 - \alpha) \hat{y}_{t},
  (\#eq:BrownMethod)
\end{equation}
where $\alpha$ is the smoothing parameter, defined by analyst and which is typically restricted with (0, 1) region (this region is actually arbitrary and we will see later what is the correct one). This is one of the simplest forecasting method, and the smoothing parameter in it is typically interpretted as a weight between the actual value and the one-step-ahead predicted one. It is a recursive method, meaning that there needs to be some starting point $\hat{y}_1$ in order to apply \@ref(eq:BrownMethod) to the existing data.



If you are interested in more details about the exponential smoothing and its history, the reviews [@Gardner1985] and [@Gardner2006] summmarise the progress in the area up until 1985 and then 2006.
