# Scale model for ADAM {#ADAMscaleModel}
So far, we have focused our discussion on the location of a model (e.g. conditional mean, point forecasts), neglecting the fact that in some situations the variance of a model might exhibit some time-varying patterns. In statistics, this is called "heteroscedasticity" and implies that the variance of the residuals of a model is not constant. In some cases we might get away with multiplicative model, which takes care of heteroscedasticity caused by changing level of data if the variance is proportional to its value. But there might be situations, where variance changes due to some external factors, not necessarily available to the analyst. In this situation, it should be captured separately using a different model. Hereafter the original model producing conditional mean will be called **location model**, while the model for the variance will be called **scale model**.

In this chapter, we discuss the scale model for ADAM ETS / ARIMA / Regression, the model that allows capturing time varying variance and using it for forecasting. We discuss how this model is formulated, how it can be estimated and then move to the discussion of its relation to such models as ARCH and GARCH. This chapter is inspired by GAMLSS model, which models the scale of distribution using functions of explanatory variables. We build upon that introducing the dynamic element in the model.


## Model formulation
We start our discussion with an example of ETS model and then move to the more general one.

### An example with ETS(A,N,N) with Normal distribution
Consider ETS(A,N,N) model (which was discussed in Section \@ref(SESandETS)), which has the following measurement equation:
\begin{equation}
    y_t = l_{t-1} + \epsilon_t,
    (\#eq:ETSANNScaleModel01)
\end{equation}
where the most commonly used assumption for the error term is:
\begin{equation*}
    \epsilon_t \sim \mathcal{N}(0, \sigma^2) .
\end{equation*}
The same error term can be represented as a multiplication of the standard normal variable by the standard deviation:
\begin{equation}
    \epsilon_t = \sigma \eta_t,
    (\#eq:ETSANNScaleModel02)
\end{equation}
where $\eta_t \sim \mathcal{N}(0, 1)$. Now consider the situation when instead of the constant variance $\sigma^2$ we have one that changes over time either because of its own dynamics or because of the influence of explanatory variables. In that case we will add the subscript $t$ to the variance in \@ref(eq:ETSANNScaleModel02) to have:
\begin{equation}
    \epsilon_t = \sigma_t \eta_t.
    (\#eq:ETSANNScaleModel03)
\end{equation}
The variance in the model \@ref(eq:ETSANNScaleModel03) can be modelled explicitly using a model. The thing to keep in mind is that such model needs to be pure multiplicative to guarantee that the variance will not become zero or even negative. For simplicity, consider that we use ETS(M,N,N) for the variance in \@ref(eq:ETSANNScaleModel03). The only thing to keep in mind is that in the case of Normal distribution, the scale is equal to variance rather than standard deviation, so such model can be written in the conventional form as:
\begin{equation}
  \begin{aligned}
    &\epsilon_t^2 = l_{\sigma,t-1} \eta_t^2 \\
    &l_{\sigma,t} = l_{\sigma,t-1} \left(1 + \alpha_\sigma (\eta_t^2-1)\right)
  \end{aligned},
  (\#eq:ETSANNScaleModel04)
\end{equation}
Note that although the part $\left(1 + \alpha_\sigma (\eta_t^2-1)\right)$ looks slightly different than the respective part $\left(1 + \alpha \epsilon_t \right)$  in the conventional ETS(M,N,N), they are equivalent: if we substitute $\xi_t = \eta_t^2-1$ in \@ref(eq:ETSANNScaleModel04), we will arrive to the conventional ETS(M,N,N) model. Another thing to notice in this formulation is that because $\eta_t$ follows standard Normal distribution, its square will follow Chi-squared distribution: $\eta_t \sim \chi^2(1)$. This is just a curious observation. Finally, we can use all the properties of pure multiplicative models discussed in Chapter \@ref(ADAMETSPureMultiplicativeChapter) to get the fitted values and forecasts from the model \@ref(eq:ETSANNScaleModel04):
\begin{equation}
  \begin{aligned}
    &\sigma_{t|t-1}^2 = l_{\sigma,t-1} \\
    &\sigma_{t+h|t}^2 = l_{\sigma,t} 
  \end{aligned}.
  (\#eq:ETSANNScaleModel05)
\end{equation}
In order to construct this model, we need to collect the residuals $e_t$ of the location model \@ref(eq:ETSANNScaleModel01), square them and use in the following system of equations:
\begin{equation}
  \begin{aligned}
    &\hat{\sigma}^2_{t} = \hat{l}_{\sigma,t-1} \\
    &\hat{\eta}_t^2 = \frac{e_t^2}{\hat{\sigma}^2_{t}} \\
    &\hat{l}_{\sigma,t} = \hat{l}_{\sigma,t-1} (1 + \hat{\alpha}_\sigma (\hat{\eta}_t^2-1))
  \end{aligned}.
  (\#eq:ETSANNScaleModel06)
\end{equation}
In order for this to work, we need to estimate $\hat{l}_{\sigma,0}$ and $\hat{\alpha}_\sigma$, which can be done in the conventional way by maximising the log-likelihood function of the normal distribution (see Section \@ref(ADAMETSEstimationLikelihood)) - the only thing that will change in comparison with the conventional estimation is the fitted values of $\hat{\sigma}^2_{t}$ for the variance generated from \@ref(eq:ETSANNScaleModel06):
\begin{equation}
    \ell(\boldsymbol{\theta}, {\sigma}_t^2 | \mathbf{y}) = -\frac{T}{2} \log(2 \pi \sigma_t^2) -\frac{1}{2} \sum_{t=1}^T \frac{\epsilon_t^2}{\sigma_t^2} .
  (\#eq:ETSANNScaleModelLogLik)
\end{equation}
The thing to keep in mind is that the final ETS(A,N,N) model \@ref(eq:ETSANNScaleModel01) with the scale model \@ref(eq:ETSANNScaleModel04) will have four parameters instead of 3 as in the case of a simpler model: 2 for the location part of the model (initial level $l_{0}$ and smoothing parameter $\alpha$) and 2 for the scale part of the model (initial level $l_{\sigma,0}$ and smoothing parameter $\alpha_\sigma$).

As can be seen from this example, constructing and estimating the scale model for ADAM is not a difficult task. Following similar principles, we can apply any other pure multiplicative model for scale, including ETS(Y,Y,Y) (Chapter \@ref(ADAMETSPureMultiplicativeChapter)), log ARIMA (Section \@ref(ADAMARIMAPureMultiplicative)) or a multiplicative regression. Furthermore, the location model ETS(A,N,N) can be substituted by any other ETS / ARIMA / Regression model - the same principles as discussed in this Subsection can be applied to them. The only restriction in all of this is that both parts of the model should be estimated via maximisation of likelihood - other methods typically do not estimate the scale of distribution explicitly.


### General case
More generally speaking, scale model can be created for any ETS/ARIMA/Regression location model. Following from the discussion in Section \@ref(ADAMETSGeneral), the general location model can be written as:
\begin{equation*}
  \begin{aligned}
    {y}_{t} = & w(\mathbf{v}_{t-\mathbf{l}}) + r(\mathbf{v}_{t-\mathbf{l}}) \epsilon_t \\
    \mathbf{v}_{t} = & f(\mathbf{v}_{t-\mathbf{l}}) + g(\mathbf{v}_{t-\mathbf{l}}) \epsilon_t
  \end{aligned}
\end{equation*}
If we assume that $\epsilon_t \sim \mathcal{N}(0,\sigma^2_t)$, then the general scale model with ETS+ARIMA+Reg elements can be formulated as (Section \@ref(ADAMETSPureMultiplicative), Subsection \@ref(eq:ADAMARIMAMultiplicative) and Section \@ref(ADAMXDynamic)):
\begin{equation}
  \begin{aligned}
		& \epsilon_t^2 = \exp \left(\mathbf{w}_E^\prime \log(\mathbf{v}_{E,\sigma,t-\mathbf{l}_E}) + \mathbf{w}_A^\prime \log(\mathbf{v}_{A,\sigma,t-\mathbf{l}_A}) + \mathbf{a}_t \mathbf{x}_t \right)\eta_{t}^2\\
		& \log \mathbf{v}_{E,\sigma,t} = \mathbf{F}_{E,\sigma} \log \mathbf{v}_{E,\sigma,t-\mathbf{l}_E} + \log(\mathbf{1}_k + \mathbf{g}_{E\sigma} (\eta_t^2-1))\\
    & \log \mathbf{v}_{A,\sigma,t} = \mathbf{F}_{A,\sigma} \log \mathbf{v}_{A,\sigma,t-\mathbf{l}_A} + \mathbf{g}_{A,\sigma} \log(\eta_t^2) \\
    & \mathbf{a}_{t} = \mathbf{a}_{t-1} + \mathbf{g}_{R,t} \log(\eta_t^2)
  \end{aligned},
  (\#eq:ADAMSMGeneral)
\end{equation}
where $\mathbf{g}_{R,t}$ is the vector containing division of smoothing parameters for regression part of the model by the respective explanatory variables (see discussion in Section \@ref(ADAMXDynamic) and specifically equation \@ref(eq:linearRegressionDynamicMultiplicative)). The main thing that unites all the parts of the model is that they should be pure multiplicative in order to avoid potential issues with negative numbers. The construction and estimation of the scale model in this case becomes similar to the one discussed for the ETS(A,N,N) example above. When it comes to forecasting of the conditional h-steps-ahead scale, given the limitations of the pure multiplicative model discussed in Section \@ref(pureMultiplicativeExpectationAndVariance), it needs to be obtained via simulations - this way the forecast from the ADAM model will coincide with the expectation, which in case of \@ref(eq:ADAMSMGeneral) will give the conditional h-steps-ahead scale. All the principles discussed in Sections \@ref(ADAMETSPureMultiplicative), \@ref(ADAMARIMAPureMultiplicative) and \@ref(ADAMXDynamic) can be used directly for the scale model without any limitations.


<!-- Connection with the conventional one, ETS, ARIMA and Regression with Scale Model -->

<!-- We extend the general ADAM framework, introduced in Section \@ref(ADAMIntermittentFull) with the introduction of the non-constant variance in the following way: -->
<!-- \begin{equation} -->
<!--   \begin{aligned} -->
<!--     & y_t = o_t z_t \\ -->
<!--     & z_t \sim \mathcal{D}(\mu_{z,t}, \sigma^2_t) \\ -->
<!--     & \mu_{z,t} = w_z(\mathbf{v}_{z,t-\mathbf{l}_z}) \\ -->
<!--     & \sigma^2_t = w_\sigma(\mathbf{v}_{\sigma, t-\mathbf{l}_\sigma}) -->
<!--   \end{aligned}, -->
<!--   (\#eq:ADAMStateSpaceSM) -->
<!-- \end{equation} -->
<!-- where $\mathcal{D}$ is the assumed distribution. -->

<!-- In case of additive error model, the demand sizes part of the model can be written as: -->
<!-- \begin{equation} -->
<!--   \begin{aligned} -->
<!--     & z_t = \mathbf{w}^\prime_z \mathbf{v}_{z,t-\mathbf{l_1}} + \epsilon_t \\ -->
<!--     & \mathbf{v}_{z,t} = \mathbf{F}_z \mathbf{v}_{z,t-\mathbf{l}_z} + \mathbf{g}_z \epsilon_t \\ -->
<!--     & \epsilon_t^2 = \sigma_t^2 \xi_t \\ -->
<!--     & \sigma^2_t = \exp \left(\mathbf{w}^\prime_\sigma \log(\mathbf{v}_{\sigma,t-\mathbf{l}_\sigma})\right) \\ -->
<!--     \log \mathbf{v}_{\sigma,t} = & \mathbf{F}_\sigma \log \mathbf{v}_{\sigma,t-\mathbf{l}_\sigma} + \log(\mathbf{1}_k + \mathbf{g}_\sigma \xi_t) -->
<!--   \end{aligned}, -->
<!--   (\#eq:ADAMStateSpaceSMAdditive) -->
<!-- \end{equation} -->

<!-- where the error term function $\varsigma({\mathbf{v}_{\xi,t-\mathbf{l}}})$ depends on its own states and set of explanatory variables. -->

<!-- In case of multiplicative error model, for example with $\Gamma$ distribution, the SM model assumes that: $1+\epsilon_{t+h} \sim \Gamma(s_{t+h}^{-1}, s_{t+h})$. This should be used in the DGP in simulations. -->


<!-- ## Estimation of ADAM SM -->
<!-- How the residuals are extracted, how the stuff is initialised, estimated and then forecasts are produced -->

<!-- ## Distributional assumptions -->

<!-- ## Forecasting with ADAM SM -->

<!-- ## Example in R -->


<!-- ## Connection with ARCH and GARCH -->
<!-- The formulation, basic principles -->



<!-- ## ADAM SM order selection -- add this to Chapter 16 -->
