# Intermittent State Space model {#ADAMOccurrence}
So far we have discussed data that has regular occurrence. This is a characteristic of a well established product that is sold every observation. For example, sales of bread in a supermarket would have this regularity. However, there are time series, where non-zero values do not happen on every observation. In the context of demand forecasting, this is called "**Intermittent demand**". The conventional example of such demand is monthly sales of jet engines: they will contain a lot of zeroes, when nobody buys the product and then all of a sudden several units, again followed by zeroes.

One of the simplest definitions of intermittent demand is that *it is the demand that happens at irregular frequency*. While at a first glance it might seem that it is an exotic problem, intermittent demand can be encountered in many areas, when the frequency of measurement is high enough. For example, daily sales of a specific type of tomatoes in a store might exhibit regular demand, but the same sales on hourly or minute frequency would exhibit intermittence. So, the problem is universal and might appear in almost any context.

Sometimes the term "count data" (or "integer-valued data") is used in a similar context, but there is a difference between it and intermittent data. This term implies that demand can take integer values only and can be typically modelled via Poisson, Binomial or Negative Binomial distributions. "Count data" does not necessarily contain zeroes and does not explicitly allow demand to happen at random. If there are zeroes, then it is assumed that they are just one of the possible values of a distribution. In case of intermittent demand, we explicitly acknowledge that demand might not happen, but if it happens then the demand size will be greater than zero. Having said that, count distributions can be used in some cases of intermittent demand, but they do not necessarily always provide a good approximation of complex reality.

Before we move towards the proper discussion of the topic in context of ADAM, we should acknowledge that at the heart of what follows, there lies the following model [@Croston1972]:
\begin{equation}
  y_t = o_t z_t ,
  (\#eq:IntermittentDemandModel)
\end{equation}
where $o_t$ is the demand occurrence variable, which can be either zero or one and has some probability of occurrence, $z_t$ is the demand sizes and $y_t$ is the final observed demand. This model in context of intermittent demand was originally proposed by @Croston1972, but similar models (e.g. Hurdle and Zero Inflated Poisson) exist in other contexts.

In this chapter we will discuss the intermittent state space model that consists of two parts, aligned with \@ref(eq:IntermittentDemandModel): demand occurrence model for $o_t$ and demand sizes model for $z_t$. For the latter, any ADAM model can be used.

<!-- ## Occurrence part of the model -->

<!-- ## Additive vs multiplicative error models -->

<!-- ## Conditional means and variance -->

<!-- ## Intermittent ETS -->

<!-- ## Other occurrence models -->
<!-- occurrence with provided values -->
<!-- occurrence estimated by alm() -->

