# Forecasting with ADAM {#ADAMForecasting}
Finally, we come to the technicalities of how to produce forecasts using ADAM. We have already discussed in previous section (e.g. Sections \@ref(pureAdditiveExpectationAndVariance) and \@ref(pureMultiplicativeExpectationAndVariance)) how conditional expectations can be generated from some of the models, but we have not discussed this in necessary detail. Furthermore, as discussed in Section \@ref(forecastingPlanningAnalytics) that forecasts should align with specific decisions, but we have not discussed how to do that. In this chapter, we start the discussion with the principles behind calculating the conditional expectations from ADAM models (including ETS, ARIMA, regression and their combinations). We then move to the discussion of producing cumulative forecasts over the forecast horizon, something that is useful in practice, when inventory decisions need to be made. Finally, we discuss in detail various methods for prediction intervals construction, starting from the basic parametric ones and ending with empirical and those that take uncertainty of parameters into account (see Section \@ref(ADAMUncertainty)).


## Producing conditional expectations
As discussed in sections \@ref(pureAdditiveExpectationAndVariance) and \@ref(pureMultiplicativeExpectationAndVariance), the conditional h step expectations are in general available only for the pure additive models. In the cases of pure multiplicative models, the point forecasts would correspond to conditional expectations only for $h \leq m$ for seasonal models and $h=1$ for models with trend. The one exception is ETS(M,N,N) model, where the point forecast corresponds to the conditional expectation for any horizon. When it comes to the mixed models (Section \@ref(ADAMETSMixedModels)), the situation would depend on the specific model, but in general the same logic as for the pure multiplicative ones applies. In this case, the conditional expectations need to be obtained via other meanse. This is when the simulations come into play.

### Simulating demand trajectories
The general idea of this approach is to use the last obtained state vector (level, trend, seasonal, ARIMA components etc) and the estimate of the scale of distribution in order to generate the possible paths of the data. The simulation itself includes:

1. 


### Cumulative over the horizon


<!-- ## Multistep errors -->


<!-- ## Prediction intervals -->

<!-- ### Parametric -->

<!-- ### Approximate -->

<!-- ### Simulated -->

<!-- ### Semiparametric -->

<!-- ### Nonparametric -->

<!-- ### Empirical -->

<!-- ### Reforecast -->

<!-- ### Confidence -->

<!-- ### Constructing intervals for intermittent model -->

<!-- ### Upper / Lower bounds -->




