# Glossary {-}
In this chapter, I decided to collect all the important definitions that are used in this monograph. I provide not only the specific definitions, but also the references to the sections where they appear.

### A {-}
- **Additive component** is the component that is added to the level of the data. e.g. additive seasonality implies that there is an increase in sales every January by $x$ units in comparison with the baseline level (Section \@ref(tsComponents)).
- **Analytics** is a systematic process of data analysis to support informed decisions (Section \@ref(forecastingPlanningAnalytics)).
- **Applied** model or **estimated** model is the statistical model that is applied to the available sample of data (Section \@ref(modelsMethods)).
- **Autocorrelation** is the correlation of a variable with itself on a different observation (Subsection \@ref(ACF)).

### B {-}
- **Backcasting** is the procedure of obtaining initial values of states by first applying the model to the original data and then to its values in reverse (Subsection \@ref(ADAMInitialisationOptAndBack)).

### C {-}
- **Count demand** is the demand that takes integer values only (see introduction to Chapter \@ref(ADAMIntermittent)).
- **Coverage** is the metric that shows the percentage of observations lying inside the prediction interval (Section \@ref(uncertainty)).

### D {-}
- **Dampening parameter** is the parameter that shows what percentage from the captured trend component should be used in producing the one step ahead point forecast (Subsection \@ref(ETSAAdN)).
- **Data Generating Process** is the mathematical model according to which the data was generated (Section \@ref(modelsMethods)). Only makes sense in case of simulated data.
- **Demand intervals** the values that show the distance between the demand sizes (see introduction to Chapter \@ref(ADAMIntermittent)).
- **Demand occurrence** is the variable that tracks whether the demand occurred on the specific observation or not (see introduction to Chapter \@ref(ADAMIntermittent)).
- **Demand sizes** are the non-zero values of demand. The term is typically used in the intermittent demand domain (see introduction to Chapter \@ref(ADAMIntermittent)).
- **Deterministic component** is the component that does not evolve over time (Section \@ref(tsComponents)). e.g. a deterministic trend is the constant trend that does not change its slope in the data (Subsection \@ref(GlobalTrend)).
- **Direct** forecasting is a procedure of producing a specific h-steps-ahead forecast (e.g., 12 months ahead), skipping all intermediate steps (Section \@ref(multistepLosses)).
- **Dynamic** model is the model that has time varying elements in it. This could be time series components, previous values of variables or time varying parameters (see example for the latter in Section \@ref(ADAMXDynamic)).

### E {-}
- **Error** or **Error term** is an unexplainable part of data (white noise) that happens due to exhistence of many small factors impacting the response variable (Section \@ref(tsComponents)).
- **Error measure** or **error metric** is an indicator that captures performance of an approach in terms of some specific statistics (e.g. mean, median etc. Section \@ref(errorMeasures)).
- **Explanatory**, or **exogenous**, or **input** variable is the variable that impacts the response variable but is not impacted by it (Chapter \@ref(ADAMX)).

### F {-}
- **Fixed origin** evaluation is the scheme when the forecasts performance is assessed only once for a specific test set based on the model estimated on a specific training set (Section \@ref(rollingOrigin)).
- **Forecast** is a scientifically justified assertion about possible states of an object in the future (Section \@ref(forecastingPlanningAnalytics)).
- **Forecast error** is the error calculated for the forecast produced on the specific horizon. Should not be confused with the *error term* or *residuals* (Section \@ref(multistepLosses)).
- **Forecast horizon** is the number of observations for which the forecasting is done (Section \@ref(typesOfForecasts)).
- **Forecastability** condition - A softer version of the "stability condition" that guarantees that with the increase of the sample size, the initial value of the state vector does not have an increasing impact on the final forecast (Section \@ref(stabilityConditionAdditiveError)). e.g. the initial level should not have an increasing weight in the final forecast over time. Global level model satisfies this condition but does not satisfy the stability one.
- **Forecasting** is a process of producing forecasts (Section \@ref(forecastingPlanningAnalytics)).

### G {-}
- **Global level** model is the model that has only the level component, which does not change over time (Section \@ref(SESandETS)).
- **Global trend** model is the model that has level and trend components, where both have zero smoothing parameters, i.e. do not evolve over time (Subsections \@ref(GlobalTrend) and \@ref(ETSAAN)).

### H {-}
- **Heteroscedasticity** is the effect when the variance of the data (or the residuals) does not stay constant (Section \@ref(diagnosticsResidualsIIDHetero)).

### I {-}
- **Identifiability** is the property of a model being uniquely defined for time series. If several different combinations of parameters give exactly the same model fit and forecasts, such model would be considered **unidentifiable** (see some examples in Section \@ref(ETSAndARIMA)).
- **Intermittent demand** is the demand that happens at irregular frequency (see introduction to Chapter \@ref(ADAMIntermittent)).
- **Invertibility** condition - see "Stability condition" (Section \@ref(stabilityConditionAdditiveError)).

### L {-}
- **Level** is the expected (average) demand for a specific time period (Section \@ref(tsComponents)).
- **Local level** model is the model that has only the level component that evolves over time (Section \@ref(SESandETS)).
- **Local trend** model is the model that has level and trend components, where the trend component changes over time (Subsection \@ref(ETSAAN)).
- **Loss function** or "Cost function" is the mathematical function that needs to be optimised to estimate parameters of a model (Sections \@ref(ADAMETSEstimationLikelihood), \@ref(non-mle-based-loss-functions), and \@ref(multistepLosses)).

### M {-}
- **Measurement equation** is the equation that shows how components of time series form the structure of the data (Section \@ref(ETSConventionalModel)).
- **Measurement vector** (measurement function) is the vector that describes how specifically the components form a structure in time series (Section \@ref(ETSConventionalModel)). For example, trend component is added to the level.
- **Method** (forecasting method) is a particular way of doing something (Section \@ref(modelsMethods), @CambridgeMethod).
- **Model** (statistical/forecasting model) is a mathematical representation of a real phenomenon with a complete specification of distribution and parameters (Section \@ref(modelsMethods), @Svetunkov2019a).
- **Multicollinearity** is the effect when some of the explanatory variables of the model (or their combination) are linearly related with each other (Section \@ref(diagnosticsMulticollinearity)).
- **Multistep forecast** or multiple-steps-ahead forecast is the forecast produced for 1 to $h$ steps ahead (Section \@ref(multistepLosses)).
- **Multiplicative component** is the component that is multiplied by the level of the data. e.g. multiplicative seasonality implies that there is an increase in sales every January by $x$% in comparison with the baseline level (Section \@ref(tsComponents)).

### N {-}
- **Nonparametric** is the approach that does not rely on assumptions of the model (Section \@ref(ADAMForecastingPI)). For example, prediction interval can be produced based on the collected in-sample multistep forecast errors, not assuming any distribution and not relying on analytical solutions for the conditional multistep variance.

### O {-}
- **Outlier** (not an outli**n**er!) is the value that lies beyond some selected threshold. These typically imply that some important information was omitted from the model (Section \@ref(diagnosticsOutliers)).

### P {-}
- **Parametric** is the approach for producing a statistics based on the assumed model and distribution (Section \@ref(ADAMForecastingPI)). For example, this is the most restrictive way of generating prediction intervals.
- **Partial autocorrelation** is the autocorrelation that is cleared from all the interim effects between the observations (Subsection \@ref(PACF)). e.g. a correlation between $y_t$ and $y_{t-2}$ without the possible effect on $y_{t-1}$ on either of the two.
- **Persistence vector** (persistence function) is the vector that contains all the smoothing parameters (Section \@ref(ETSConventionalModel)). It shows how the values of components are updated based on the observed forecast error.
- **Point forecast** is the trajectory produced by a model (Subsection \@ref(typesOfForecastsPoint)).

### R {-}
- **Random walk** is the process that implies that the differences of the data have a constant level (Subsection \@ref(Differences)), i.e. the only thing that impacts them is the error term. This is the model underlying the Naïve forecasting method (Subsection \@ref(Naive)).
- **Range** is the metric that shows the width of the prediction interval (Section \@ref(uncertainty)).
- **Recursive** forecasting refers to the approach, when multistep forecasts are produced iteratively, one after the other, typically based on a mathematical formula (see examples in Section \@ref(ADAMForecastingExpectationSimulations)). This is the default way of producing forecasts from *dynamic models*.
- **Regression model** is the model that captures a linear relation between the response and a set of the explanatory variables.
- **Residuals** are the estimated *errors* of the model. Whenever you apply a model to the data, you end up with the structure and residuals (Section \@ref(modelsMethods)).
- **Response** or **output** variable is the variable of interest that we want to forecast (Chapter \@ref(ADAMX)).
- **Rolling origin** evaluation is the scheme when the forecasts performance is assessed iteratively on a moving holdout sample by adding observations to the in-sample. This is sometimes also called "Time series cross-validation" (Section \@ref(rollingOrigin)).

### S {-}
- **Seasonal normalisation** is the process that guarantees that the seasonal indices either add up to zero - in case of the additive seasonality - or have a geometric mean of one - in case of the multiplicative one (Section \@ref(ADAMETSSeasonalNormalisation)).
- **Seasonality** is a pattern that repeats itself with a fixed periodicity (Section \@ref(tsComponents)).
- **Semiparametric** is the approach which lifts some of assumptions of the model, but not all (Section \@ref(ADAMForecastingPI)). For example, prediction interval can still rely on normality, but use empirically evaluated multistep forecast variances.
- **Smoothing parameter** is the parameter that regulates the reactivity in the update of a time series component. Used in SES (Section \@ref(SES)) and ETS (Section \@ref(ETSTaxonomyMaths)).
- **Stability** condition ("invertibility" in case of ARIMA) is the restriction on the models parameters that guarantees that model forgets the old information and puts more weight on the recent observations (Section \@ref(stabilityConditionAdditiveError)).
- **State space model** is the model that describes how different components make up the data and how those components evolve over time (Section \@ref(ETSConventionalModel)).
- **State vector** is the vector that contains components (states) of time series (Section \@ref(ETSConventionalModel)). Can include level, trend, seasonal components together with values of explanatory variables .
- **Stationarity** is the condition that guarantees that the unconditional moments of the model stay the same (Section \@ref(ARIMAIntro). Can be *weak*, implying that only the expectation and the variance need to be constant and *strong*, implying in addition that the probability distribution does not change over time.
- **Static** model is the model, which structure does not change over time. An example of such model would be a Global level, a Global trend, or a regression model (see respective terms in the Glossary).
- **Stochastic component** is the component that can change its value over time. e.g. a stochastic trend can be positive in the beginning of the sample than slowly change its value and become negative by the end of the sample (Section \@ref(tsComponents)).

### T {-}
- **Transition equation** is a system of equations describing how different components of time series interact with each other and evolve over time (Section \@ref(ETSConventionalModel)).
- **Transition matrix** (transition function) is the matrix describing the interactions between the components (Section \@ref(ETSConventionalModel)).
- **Trend** or **growth** is the average increase or decrease of the value over a period of time (Section \@ref(tsComponents)).
- **True model** is the idealistic statistical model that is correctly specified (has all the necessary components in the correct form), and applied to the data in population" (Section \@ref(modelsMethods), @SvetunkovSBA).

